### ISSUE TITLE
Explain what clientid/serviceprincipalsecret are needed for

### ISSUE THREAD

**Issue by strtdusty** [F5Networks/f5-azure-arm-templates#10]
Can you expand the documentation (specifically for the HA deployments) on what the SP clientID/secret are needed for?  Presumably there are some set of permissions it needs as well?  Is this for the failover?

**Comment by edwoodjrjr** [comment]
Hi Jeff, we will add more info about this to the readme in the next release.  We need the service principal to move the public IP address configurations and routes between members of the BIG-IP cluster.  It will need contributor access to the external NICs on both BIG-IPs, as well as any route tables that have routes that will use the BIG-IPs as the next hop.
