### ISSUE TITLE
Add Documentation about creating a Service Principal

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-azure-arm-templates#100]
## Description
Describe the problem you're having or the enhancement you'd like to request.

The details of creating a Service Principal for the API driven failover can be daunting.  Having pointers / step-by-step would be helpful.  An example of docs created for customer demo:

https://f5-azure-saca.readthedocs.io/en/latest/class1/intro.html#create-service-principal-via-azure-cli

I believe in the past there may have also been links to:

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal#create-an-azure-active-directory-application

Currently the README pages are a bit sparse and I do not see anything on CloudDocs.f5.com

## Template
For bugs, enter the template with which you are experiencing issues below.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

**Comment by jsevedge** [comment]
@chen23 Do you have a specific template in mind?  Each template that requires a service principal contains a section describing what roles are required as well as links to how to configure via portal/cli, for example the following readme: https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/autoscale/ltm/via-lb/1nic/new-stack/payg#service-principal-authentication

Is this what you are looking for or something more?

**Comment by ArtiomL** [comment]
We could also potentially link to scripts.  

Something similar to:  

> Azure CLI:
https://github.com/ArtiomL/f5networks/blob/master/azure/ad_spn.sh

> Powershell:
https://github.com/ArtiomL/f5networks/blob/master/azure/ad_spn.ps1

**Comment by chen23** [comment]
@jsevedge that looks perfect.  I think that it got lost in the depth of all the different options.  

It would be helpful for both the GUI/CLI examples to mention what properties they map to either in the ARM template or iApp.  I know that it can be confusing to map what is a secret, tenant-id, etc...  Thanks!

**Comment by jsevedge** [comment]
Closing the loop here, as mentioned see the *Service Principal Authentication* section in relevant templates for advanced instructions on creation, what roles are required, etc.

Closing this issue out, please feel free to reopen or open a new issue for further questions.
