### ISSUE TITLE
Add dnsname to autoscaleconfig object name

### ISSUE THREAD

**Issue by depperson** [F5Networks/f5-azure-arm-templates#102]
## Description
The "autoscaleconfig" object doesn't have a dnsname attached so it might become orphaned in the resource group. 

## Template
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/autoscale/ltm/via-lb/1nic/existing-stack/payg/azuredeploy.json#L825

Perhaps we could simply change "name": "autoscaleconfig", 
to "name": "[concat(parameters('dnsLabel'),'-vmss-autoscaleconfig')]",
in the templates?

Does "autoscaleconfig" have to be named that or can it be modified to match our other naming conventions? 

## Severity Level
4

**Comment by depperson** [comment]
A later attempt to deploy an autoscale template into the previously created resource group will fail.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"code\": \"TargetResourceIdIsImmutable\",\r\n \"message\": \"The autoscale setting 'autoscaleconfig' under resource group 'rg2' is referencing target resource '/subscriptions/x/resourceGroups/rg2/providers/Microsoft.Compute/virtualMachineScaleSets/retest-vmss'. The target resource reference is immutable. If you want to change it, please create a new autoscale setting with a different name.\"\r\n}"}]}

**Comment by edwoodjrjr** [comment]
Thanks, we'll have a look at this.

**Comment by edwoodjrjr** [comment]
Internal issue 1176.

**Comment by mycahb2** [comment]
Any update on this?  It impacts us as well, we cannot deploy multiple clusters to the same rg and have different autoscale configs.

**Comment by jsevedge** [comment]
@mycahb2 This is still in the backlog, added a +1 to the issue for you.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).

Our V2 templates have solved this issue with a uniqueString parameter.
