### ISSUE TITLE
Multiple Custom DNS in vnets stop v12 from working

### ISSUE THREAD

**Issue by svensol** [F5Networks/f5-azure-arm-templates#103]
## Description
When deploying onto existing/production networks, the Linux Agent fails to parse the DNS servers and provisioning fails.

v14 image does not have this problem.

Other reports have highlighted this and has been fixed here in the mainline:
https://github.com/Azure/WALinuxAgent/pull/1303

You can reproduce this on the v12 new-stack by quickly changing the DNS Servers option on the vnet before the VM image boots.

## Template
Any of the single-nic production/existing stacks - when deploying v12 images.  

I've not tried any of the multi-nic templates.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

I only say it's 2 (high) as it stops any deployments of the v12 images into production/existing .

**Comment by edwoodjrjr** [comment]
The ask is to backport new waagent onto v12 images, correct?

**Comment by svensol** [comment]
Yes, it is...  I'm assuming that'll fix it anyway

It's odd.  The version in the F5 is different to the numbering mentioned in the offical agent repo, I'm guessing the the F5 devs may have forked it?

**Comment by svensol** [comment]
Do we know if this is being looked at for a possible fix?

**Comment by svensol** [comment]
As a temporary work around, I managed to quickly change the settings mid deployment:

* Start the depoloyment
* Keep hitting refresh until you see the NIC become available
* Select the NIC, edit the DNS servers
* Change the DNS server from inherited mode and add in the azure gateway ip address
* Adding a 3rd party DNS (e.g. 8.8.8.8) will probably fail.
* Wait for the services to finish provisioning.

The machine should then be available.

**Comment by ajsq** [comment]
This applies to all current versions including 15.1.0 because BIG-IP still ships an archaic version of walinuxagent, 2.2.25. 

This was fixed in walinuxagent release v2.2.32 in September 2018. How long does it take F5 to update to a current version?

**Comment by shyawnkarim** [comment]
The next BIG-IP releases will include a waagent update to 2.2.42.

- 13.1.3.4
- 14.1.2.2
- 15.0.1.2
- 15.1.0.1

**Comment by shyawnkarim** [comment]
Closing due to updates for waagent being posted. Please upgrade from v12 if you would like to use a newer version of the waagent.
