### ISSUE TITLE
Failed to deploy BIG-IP v12 in Azure - Region failure

### ISSUE THREAD

**Issue by svensol** [F5Networks/f5-azure-arm-templates#105]
## Description
This is like #104 but using the scripts launched directly from here.

I'm trying to deploy F5 v12.1.3.0.3000, but it's failing saying that the image isn't available in my location. I have deployed this several times in the same subscription/location.

`{"telemetryId":"4aade59c-8249-411c-97c7-2273f5be372b","bladeInstanceId":"Blade_74c8cb7090cd4b04b12692c6212f5eb9_0_0","galleryItemId":"Microsoft.Template.2.0.0","createBlade":"DeployToAzure","code":"MarketplacePurchaseEligibilityFailed","message":"Marketplace purchase eligibilty check returned errors. See inner errors for details. ","details":[{"code":"BadRequest","message":"Offer with PublisherId: f5-networks, OfferId: f5-big-ip-best cannot be purchased due to validation errors. See details for more information.[{\"The Publisher: f5-networks does not make available Offer: f5-big-ip-best, Plan: f5-bigip-virtual-edition-best-byol in your Subscription/Azure account’s region: GB.\":\"StoreApi\"}]"}]}`

Specifically, the region is "UK South"

## Template

https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/1nic/existing-stack/byol

Release v5.5.0.0

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

**Comment by edwoodjrjr** [comment]
We are tracking this with internal issue #780.

**Comment by f5kuebler** [comment]
We are working on an interim minor release to fix just this issue immediately (next 24hrs) prior to our regularly scheduled R15 release next week. Stay tuned here for the minor release announcement.   In the meantime you can use the custom image field to point to a published image in Azure as described in the release notes here:  https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v5.1.0.0 and each of the template READMEs under the 'customImage' parameter description.

**Comment by crosbygw** [comment]
We have published updates to all BYOL and BIGIQ licensed templates to reflect the correct image names when using version 12 BIG-IP.

https://github.com/F5Networks/f5-azure-arm-templates/tree/v5.5.1.0

**Comment by svensol** [comment]
Thanks all!!  Working a treat!

**Comment by edwoodjrjr** [comment]
Yes, v13 is affected in the WAF solutions.  A fix is currently being pushed.
