### ISSUE TITLE
F5 Azure API Failover Issue

### ISSUE THREAD

**Issue by gc879** [F5Networks/f5-azure-arm-templates#107]
## Description
Describe the problem you're having or the enhancement you'd like to request.
After utilizing the Azure Multi-NIC GitHub template on 13.1.0.2 and upgrading to 13.1.1.2, we are seeing issues with Failover to the backup F5.  Below is the output in the AzureFailover.log

2018-11-30T04:16:47.650Z info: Error:  Failed to acquire token for application with the provided secret. 
Error: getaddrinfo EAI_AGAIN login.microsoftonline.com:443
2018-11-30T04:16:47.652Z info: Error in failover:  Failed to acquire token for application with the provided secret. 
Error: getaddrinfo EAI_AGAIN login.microsoftonline.com:443
2018-11-30T04:31:51.993Z info: Error in failover:  Failed to acquire token for application with the provided secret. 
Error: getaddrinfo EAI_AGAIN login.microsoftonline.com:443
2018-11-30T04:31:51.996Z info: Error:  Failed to acquire token for application with the provided secret. 
Error: getaddrinfo EAI_AGAIN login.microsoftonline.com:443
2018-11-30T04:46:56.747Z info: Error:  Failed to acquire token for application with the provided secret. 
Error: getaddrinfo EAI_AGAIN login.microsoftonline.com:443
2018-11-30T04:46:56.749Z info: Error in failover:  Failed to acquire token for application with the provided secret. 
Error: getaddrinfo EAI_AGAIN login.microsoftonline.com:443
2018-12-06T01:58:03.759Z info: Error:  Failed to acquire token for application with the provided secret. 
Error: getaddrinfo EAI_AGAIN login.microsoftonline.com:443
2018-12-06T01:58:03.762Z info: Error in failover:  Failed to acquire token for application with the provided secret. 
Error: getaddrinfo EAI_AGAIN login.microsoftonline.com:443
2018-12-06T02:14:23.684Z info: Error in failover:  Failed to acquire token for application with the provided secret. 
Error: getaddrinfo EAI_AGAIN login.microsoftonline.com:443
2018-12-06T02:14:23.687Z info: Error:  Failed to acquire token for application with the provided secret. 
Error: getaddrinfo EAI_AGAIN login.microsoftonline.com:443

## Template
For bugs, enter the template with which you are experiencing issues below.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <3>

Severity level definitions:

 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.

**Comment by edwoodjrjr** [comment]
Hi, did you do an in-place upgrade on the BIG-IPs?

**Comment by gc879** [comment]
Yes, we went through the traditional upgrade from the backup unit first.  Attempted the upgrade, which worked.  The only thing we notice is failing over from an F5 standpoint is good, but the API fails.
Gavin

**Comment by edwoodjrjr** [comment]
Some of the files that you need for the failover provider do not get copied over during an upgrade.  Your best bet is probably to contact F5 support so they can assist you with getting back to a working state.

**Comment by gc879** [comment]
That’s exactly what we were thinking.  We have a support case but they’re unable to trace any specific Azure script/files.  We have the gov failover script still in place that are located in config/cloud/azure/node_modules/f5-cloud-libs/node_modules/f5-cloud-libs-azure/scripts/, but the logs indicate we are using public azure login vs the gov.  Is there anything documented to understand what Azure files are needed?  Wouldn’t this be considered a bug?  Seems like redeploying requires many more steps than in place upgrade, especially when modifying the public IPs beyond what the deployment template allows.

We are working with them on getting packet captures during a failover attempt.

Gavin

**Comment by edwoodjrjr** [comment]
Which template did you use to deploy?  Was it existing stack or new stack?  Did you use byol, payg, or bigiq licensing?

**Comment by gc879** [comment]
New Stack Multinic with HA, BYOL was used to deploy originally.  Worked flawlessly until we upgraded.

Gavin

**Comment by edwoodjrjr** [comment]
All of the configuration done on the BIG-IPs is reflected in these two series of commands.  Splitting them on semicolons and parsing the template parameters/variables will tell you everything that happens at deployment time:

https://github.com/F5Networks/f5-azure-arm-templates/blob/cdd050eaa003727ed56d5438922388547535659c/supported/failover/same-net/via-api/n-nic/new-stack/byol/azuredeploy.json#L1146 

and 

https://github.com/F5Networks/f5-azure-arm-templates/blob/cdd050eaa003727ed56d5438922388547535659c/supported/failover/same-net/via-api/n-nic/new-stack/byol/azuredeploy.json#L1174

**Comment by edwoodjrjr** [comment]
I believe this was solved via F5 Support.  If that's incorrect, please reopen this issue.
