### ISSUE TITLE
SSH Public-Key-based deployments failing on GitHub templates

### ISSUE THREAD

**Issue by dannekrose** [F5Networks/f5-azure-arm-templates#108]
## Description
When using the GitHub templates to deploy a BIG-IP, even though the GUI talks about allowing an SSH public-key for auth, it fails.  It only seems to accept passwords.

## Template
All BIG-IP deployments that try to use an SSH-Public Key for admin access.

## Severity Level
5

**Comment by namhly** [comment]
Hi @dannekrose 
How did you define your SSH-Public Key?
I was able to deploy the following template: https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/2nic/new-stack/payg
successfully using a public key in this form:

---- BEGIN SSH2 PUBLIC KEY ----
<PUBLIC KEY.......>
---- END SSH2 PUBLIC KEY ----

**Comment by dannekrose** [comment]
I tried this, but we're getting template validation errors.
When I input the key, I just $ cat .ssh/id_rsa.pub the file, grabbed the string inbetween the "ssh-rsa" and the machine name at the end.  Is this correct or are you converting the public key into a different format?

Mine looks like something like:
---- BEGIN SSH2 PUBLIC KEY ----
AAAAB3NzaC1yc..............S64hk7+otBt
---- END SSH2 PUBLIC KEY ----

Is this correct?

**Comment by namhly** [comment]
Thanks for reporting this issue. We've identified the problem, the fix will come in the next release.
This issue is being tracked by our internal issue 923.

**Comment by namhly** [comment]
Hello,
The fix has been released. Did you have a chance to test it? 

Thanks,

**Comment by edwoodjrjr** [comment]
This was fixed by a subsequent release of cloud templates.  Please reopen if you are still seeing the issue with the latest version.
