### ISSUE TITLE
DNS Label not set to Required

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-azure-arm-templates#109]
## Description
The DNS Label parameter is required for IP addresses however when deploying this ARM you dont get the red asterisk from the validation engine; this causes issues from customer deployments who dont understand the requirement.

<img width="702" alt="dns label" src="https://user-images.githubusercontent.com/20847865/50604310-5dd85f80-0e73-11e9-81f1-e30240bc8d62.png">

This is similar to issue: https://github.com/F5Networks/f5-azure-arm-templates/issues/20, however I'm not the OP so i cant reopen it :)

## Template
Ive seen this on 3Nic and Single Nic

## Severity Level
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.

**Comment by namhly** [comment]
Hi @jmcalalang ,

Thanks for reporting this issue. We are tracking this with internal issue #864.

**Comment by namhly** [comment]
We have fixed this issue. The fix will come out in the next release. Thanks.

**Comment by edwoodjrjr** [comment]
Fixed in release 15.0.1.
