### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by joejcannon** [F5Networks/f5-azure-arm-templates#11]
What exactly is a license token?  We have a registration key and dossier we get back from the license server.  When entering the regkey in the template, it doesn't seem to handle the licensing, still had to do this manually.  Is this expected or is something amiss (either with me or the template).

**Comment by edwoodjrjr** [comment]
Hi Joe, the token is the registration key.  You shouldn't have to do anything manually.  Which template are you using?

**Comment by jsevedge** [comment]
@edwoodjrjr  appears to have answered your question @joejcannon . Please re-open if you need additional information.
