### ISSUE TITLE
Prerequisites for BIG-Q as LM disagree with Version Matrix 

### ISSUE THREAD

**Issue by tthomas0702** [F5Networks/f5-azure-arm-templates#111]
## Do you already have an issue opened with F5 support?
no

## Description
This is about the prerequisites docuemtation at this link:
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/bigiq

The documentation for using BIG-IQ as a License Manager at link says that:

"This solution supports the two most recent versions of BIG-IQ (see the Version Matrix for specific versions), and..."

But the Version Matrix shows BIG-IQ v5.4,v6.01.  The two most recent versions are v6.0.1 and v6.1.0.

I am not sure which is actually supported.

## Severity Level
5
Severity: <Fill in level: 1 through 5>

**Comment by wduongf5** [comment]
Hi Tim,

Thanks for filing the issue. We do support the latest version of big-iq license manager. I created an internal tracking number 1158 for this issue.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
