### ISSUE TITLE
network.js fails with certain licensing and images

### ISSUE THREAD

**Issue by joejcannon** [F5Networks/f5-azure-arm-templates#112]
## Do you already have an issue opened with F5 support?
Yes. C2914143

## Description
Network.js fails to complete with different licensing depending on azure instance size.  This impacts the cluster build for HA deployments as well.  All code versions.

License | Azure Instance   Size | Problem with   network.js?
-- | -- | --
LTM-VE-3G-V16 | Standard_DS3_v2 | No
LTM-VE-1G-V16 | Standard_DS3_v2 | Yes
LTM-VE-200MV16 | Standard_DS3_v2 | Yes
LTM-VE-25MV16 | Standard_DS3_v2 | Yes
BEST-1G-v16 | Standard_DS3_v2 | No
  |   |  
LTM-VE-3G-V16 | Standard_DS4_v2 | No
LTM-VE-1G-V16 | Standard_DS4_v2 | Yes
LTM-VE-200MV16 | Standard_DS4_v2 | Yes
LTM-VE-25MV16 | Standard_DS4_v2 | Yes
BEST-1G-v16 | Standard_DS4_v2 | No
  |   |  
LTM-VE-3G-V16 | Standard_D5_v2 | No
LTM-VE-1G-V16 | Standard_D5_v2 | No
LTM-VE-200MV16 | Standard_D5_v2 | No

## Template
Impacting all supported templates: Standalone/HA BYOL/BIG-IQ

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

**Comment by edwoodjrjr** [comment]
Thanks Joe.  I created internal issue #943 to track this.

**Comment by edwoodjrjr** [comment]
Note, this has been intermittent in our testing.  The fix will account for that.

**Comment by chris-fp** [comment]
Also DS2_v2 200m and 25m also do NOT work

**Comment by chris-fp** [comment]
Another case with this issue:-

C2929189

**Comment by mikeoleary** [comment]
We have hit this issue also. We cannot deploy a Standard_DS3_v2 with a LTM-VE-1G-V16 license. Can we deploy a DS5_v2, and then change VM size to DS3_v2, to see if that works in the meantime?

**Comment by edwoodjrjr** [comment]
Mike, are you an F5 employee? If so I will contact you directly.

**Comment by mikeoleary** [comment]
Hi Mike, yes I am. Please find my contact details in the GAL.

**Comment by edwoodjrjr** [comment]
This has been fixed in https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v6.0.4.0
