### ISSUE TITLE
Service discovery problem in multi-nic setup

### ISSUE THREAD

**Issue by pvude** [F5Networks/f5-azure-arm-templates#113]
## Description
Deployed multiple nic setup.
Result:
--> first nic: mgmt
--> second nic: internal
--> third nic: external
Manually setup of default route on external interface
--> BIG-IP tries to connect to Azure Metadata-Instance-Service (ip: 169.254.169.254) on external interface.
This fails, because Azure does only allow connections from primary nic (in this case: mgmt).
--> Service-discovery does not work
Tried to configure static route on mgmt-interface to ip 169.254.0.0/16
TMSH does not allow this (link-local route)!
Only when configuring static route to this ip through the mgmt-interface on os level the service-discovery does work.

That's why I suggest an improved configuration: Template should include static route to Azure Metadata-Instance-Service on 1st (mgmt) interface.

## Template
Tested with the following templates. Both with same result.
supported/standalone/3nic/existing-stack/payg
supported/failover/same-net/via-api/n-nic/existing-stack/payg

## Severity Level
Severity: 4

**Comment by edwoodjrjr** [comment]
Created internal issue #944 for this.  Thanks for bringing it to our attention.

**Comment by edwoodjrjr** [comment]
Closing as a duplicate of https://github.com/F5Networks/f5-azure-arm-templates/issues/121.  Please use that issue for future reference.
