### ISSUE TITLE
Remove Timezone

### ISSUE THREAD

**Issue by khaiphan9x** [F5Networks/f5-azure-arm-templates#115]
Asia/Saigon

**Comment by edwoodjrjr** [comment]
Hi, are you requesting that we remove it from this list:  https://github.com/F5Networks/f5-azure-arm-templates/blob/master/azure-timezone-list.md
thanks

**Comment by khaiphan9x** [comment]
Asia/Saigon timezone is just the reverse sync time zone for Asia/Ho_Chi_Minh, not the official time zone, so it can be removed.

**Comment by edwoodjrjr** [comment]
Just making sure you meant to remove it from that file, and not from /usr/share/zoneinfo on BIG-IP (which is where the zones in that file came from).

**Comment by khaiphan9x** [comment]
That is my opinion, the decision is yours

**Comment by edwoodjrjr** [comment]
We decided not to remove this timezone from our templates since it is an accepted value on BIG-IP itself.
