### ISSUE TITLE
Experimental template: BIG-IQ 6.1 cluster template is referencing a non working azuredeploy.json

### ISSUE THREAD

**Issue by garyluf5** [F5Networks/f5-azure-arm-templates#117]
## Do you already have an issue opened with F5 support?
No

## Description
When tried to deploy the cluster BIGIQ template, here is an error returned from the Azure portal:

"There was an error loading the template from URI 'https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/v6.0.0.0/experimental/bigiq/licenseManagement/cluster/2nic/existing-stack/byol/azuredeploy.json'. Ensure that the template is publicly accessible and does not have any comments. "

This should be a quick fix if we just update the "v6.0.0.0" to "master" branch...
i.e.
This one works
https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/master/experimental/bigiq/licenseManagement/cluster/2nic/existing-stack/byol/azuredeploy.json

this one does NOT work
https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/v6.0.0.0/experimental/bigiq/licenseManagement/cluster/2nic/existing-stack/byol/azuredeploy.json

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/experimental/bigiq/licenseManagement/cluster/2nic/existing-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by namhly** [comment]
Thanks Gary, we will fix it in the coming release.

**Comment by edwoodjrjr** [comment]
Links should be fixed now.  Gary, let me know directly if not.

**Comment by garyluf5** [comment]
all looking good, thanks!
