### ISSUE TITLE
Azure templates with load balancers creating "Basic" SKU load balancers

### ISSUE THREAD

**Issue by Nailzy** [F5Networks/f5-azure-arm-templates#118]
## Do you already have an issue opened with F5 support?
No

## Description
The Azure Templates that deploy Load Balancers are using "Basic" SKU which don't have any SLA from Microsoft, and therefore should not be used in production.

https://azure.microsoft.com/en-ca/support/legal/sla/load-balancer/v1_0/

Microsoft documentation also says

" Note

New designs should adopt Standard Load Balancer."

https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-overview

## Template

https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 4

**Comment by edwoodjrjr** [comment]
Thanks for the request.  We are tracking this with internal issue #1046.

**Comment by kantkrish** [comment]
Adding to the same, if the LB will be changed to standard, please change the "Public IP" sku to Standard as well.

**Comment by andreasforseth** [comment]
Hi, 
I ran into this issue as well. Is there any estimation of when this will be fixed? 
Br Andréas

**Comment by namhly** [comment]
Hi Andreas,
It was fixed and will be out in the coming release which will be around June 18th.
Thank you.

**Comment by shyawnkarim** [comment]
Closing. Per namhly comment above, our via-lb templates have been enhanced to use the Standard Load Balancer.
