### ISSUE TITLE
VE Console Root Access

### ISSUE THREAD

**Issue by kantkrish** [F5Networks/f5-azure-arm-templates#119]
## Description
I deployed cluster using the LB/3NIC template and I cannot login to console via Root for maintenance. i never changed the password for root/admin after provisioning. Root login is "disabled" under Platform and it was never changed or checked after provisioning.

To run file system check, I need to run root and its not accepting system defaults. Is it different ? 

## Template
For bugs, enter the template with which you are experiencing issues below.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 1

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Hi, root and admin accounts are disabled by default in all our Azure images.  You will need to log in as the user you created at deployment time and go to System>Platform>User Administration to enable root login.

**Comment by edwoodjrjr** [comment]
Closing as solved with configuration notes.  Please reopen if this is still an issue.
