### ISSUE TITLE
Availability Zone Options in Template

### ISSUE THREAD

**Issue by kantkrish** [F5Networks/f5-azure-arm-templates#120]
## Description
Can the option to select "Availability Zones" be added to the Template?

## Severity Level

Severity: 2

**Comment by edwoodjrjr** [comment]
This is a duplicate of https://github.com/F5Networks/f5-azure-arm-templates/issues/74 (tracked with issue 993).

**Comment by edwoodjrjr** [comment]
Closing as duplicate.
