### ISSUE TITLE
f5-service-discover cannot connect to "Azure Instance Metadata service"

### ISSUE THREAD

**Issue by nergalex** [F5Networks/f5-azure-arm-templates#121]
## Description

With the template "f5-azure-arm-templates/supported/failover/same-net/via-lb/3nic/existing-stack/byol/", the data-plane's default gw is on "external subnet".
f5-service-discover iApp need to join "Azure Instance Metadata service" (169.254.169.254) via the primary interface on "mgmt subnet". A specific route to 169.254.169.254 is not allowed by F5:
01020062:3: IP Address 169.254.169.254 is invalid, link-local address not allowed.

My workaround is to set a bigger route: 169.252.0.0/14

Do you have a solution to route only 169.254.169.254/32 or 169.254.0.0/24 via its mgmt GW ?

## Template
f5-azure-arm-templates/supported/failover/same-net/via-lb/3nic/existing-stack/byol/

## Severity Level
Severity: 2

f5-service-discover does not work.

**Comment by edwoodjrjr** [comment]
Can you paste the output of the "route" command here?  In my deployment, I had two default routes.  When I deleted the default route via external interface, service discovery worked.

**Comment by edwoodjrjr** [comment]
Alternately, you can route the metadata traffic out the mgmt interface:

route add 169.254.169.254/32 dev mgmt

**Comment by nergalex** [comment]
Hi,
I have also 2 default routes: 1 for data-plane, 1 for mgmt-plane (see below). The data-plane default route cannot be suppressed, it will be used by monitors. 
I can't add a 169.254.169.254/32 route using tmsh (see below).

root@(hub-adc0)(cfg-sync Standalone)(Active)(/Common)(tmos)# list sys management-route 
sys management-route dhclient_route1 {
    description configured-by-dhcp
    gateway 10.0.0.1
    network 168.63.129.16/32
}
sys management-route default {
    description configured-by-dhcp
    gateway 10.0.0.1
    network default
}
sys management-route 169.252.0.0/14 {
    gateway 10.0.0.1
    network 169.252.0.0/14
}
root@(hub-adc0)(cfg-sync Standalone)(Active)(/Common)(tmos)# list net route
Components:
  route                  route-domain           router-advertisement   
root@(hub-adc0)(cfg-sync Standalone)(Active)(/Common)(tmos)# list net route
net route default {
    gw 10.0.1.1
    network default
}
net route internal {
    gw 10.0.2.1
    network 10.0.0.0/8
}
root@(hub-adc0)(cfg-sync Standalone)(Active)(/Common)(tmos)# create /sys management-route 169.254.169.254/32 gateway 10.0.0.1
01020062:3: IP Address 169.254.169.254 is invalid, link-local address not allowed.

**Comment by edwoodjrjr** [comment]
Try "route add 169.254.169.254/32 dev mgmt" from the shell.

**Comment by nergalex** [comment]
Yes, using "ip route" the route is well inserted in the main table, but not persistent, isn't it ?

**Comment by edwoodjrjr** [comment]
True, you can add a script to /config/startup to create that route at boot time.  Anyway, we already have internal issue #944 to track proper implementation of this.

**Comment by nergalex** [comment]
ok thank you

**Comment by edwoodjrjr** [comment]
This has been addressed in https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v6.1.0.0

Let us know if you have any questions.
