### ISSUE TITLE
f5-service-discover does not discover secundary NIC

### ISSUE THREAD

**Issue by nergalex** [F5Networks/f5-azure-arm-templates#122]
## Description
f5-service-discover iApp does not discover NICs which is not "primary".

Test results:
- VM tagged: the primary NIC is discovered
- VM tagged + secundary NIC tagged: the primary NIC is discovered
- secundary NIC tagged: nothing is discovered

Configuration:
- iApp "discover_app1"
+-- In which cloud provider are the pool members deployed? Azure
+-- Are your BIG-IP and pool members in the same Azure Environment? Yes
+-- What is the tag key on your cloud provider for the members of this pool? app_name
+-- What is the tag value on your cloud provider for the members of this pool? app1
+-- Do you want to search for public or private IP addresses? Private IP

- VM NICs:
                'network_interfaces': {
                    'nic-management': {
                        'subnet': 'net-management',
                        'primary': True,
                        'ip_configurations': [{
                            'name': 'mgt',
                            'primary': True,
                            'private_ip_allocation_method': 'Static',
                            'private_ip_address': '10.1.0.10',
                            'public_ip_address': {
                                'public_ip_address_name': 'sp1-app1-srv01-cloudbuilder',
                            },
                        },
                        ],
                    },
                    'nic-app_1': {
                        'subnet': 'net-app_1',
                        'primary': False,
                        'ip_configurations': [{
                            'name': 'self-static',
                            'primary': True,
                            'private_ip_allocation_method': 'Static',
                            'private_ip_address': '10.1.11.10',
                        },
                        ],
                        'tags': {
                            'app_name': 'app1',
                        },
                    },
                },

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol#service-discovery

## Severity Level
Severity: 2

**Comment by edwoodjrjr** [comment]
I verified that this an issue.  Created internal issue 1074 for tracking.

**Comment by shyawnkarim** [comment]
This issue has been assigned to [Application Services](https://github.com/F5Networks/f5-appsvcs-extension). The internal ID is AUTOTOOL-772.
