### ISSUE TITLE
deploy_via_bash.sh do not work with current Azure CLI (2.0)

### ISSUE THREAD

**Issue by assareh** [F5Networks/f5-azure-arm-templates#123]
## Description
Current Azure CLI version 2.0 command has changed to az 
in addition some command line options have changed
as a result the deploy_via_bash.sh are not working

**Comment by wduongf5** [comment]
Hi Assareh,

Thanks for the suggestion. I've created an internal tracking number for it 1152.

**Comment by jsevedge** [comment]
It appears this is a duplicate of #77.  Closing this one out to track with a single issue.
