### ISSUE TITLE
BIG-IQ-licensed templates fail when bigIqLicenseUnitOfMeasure parameter is capitalized

### ISSUE THREAD

**Issue by mikeshimkus** [F5Networks/f5-azure-arm-templates#124]
## Do you already have an issue opened with F5 support?
No

## Description
When deploying a template that licenses via BIG-IQ, if you specify "Yearly" instead of "yearly" for bigIqLicenseUnitOfMeasure, licensing will fail.

We should provide a list of allowedValues here and then tolower the input before passing to onboard.js.

## Template
All template that licesne via BIG-IQ.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 3

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by wduongf5** [comment]
Hi Mike,

Thanks for filing the issue. An internal tracking number 1153 is created to track this issue.

**Comment by edwoodjrjr** [comment]
Hi Will, I already created issue 1143.
Mike

**Comment by wduongf5** [comment]
Ah cool. I'll delete the 1153 then.

**Comment by rftoccijr** [comment]
Any traction on this?  I'm working on a deployment with my customer on this and it was not very intuitive on the case.  Trial and error resolved it, but it needs to be specified properly.

**Comment by shyawnkarim** [comment]
Closing this issue.

We looked into it and, from code implementation,  a list of valid string values is too long. Maybe we could make a DOC issue with examples or point to a link with examples?
