### ISSUE TITLE
Marketplace Offer for 3-NIC PAYG

### ISSUE THREAD

**Issue by kantkrish** [F5Networks/f5-azure-arm-templates#127]
What product and offer I should use for accepting Maketplace terms via Powershell?

I am trying to deploy 3-NIC, 1G - PAYG 

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic/existing-stack/payg

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by jsevedge** [comment]
@kantkrish  This should be the offer and sku want.  Although if you need good or better bundle swap out best for one of those.

```json
            "best1gbps": {
                "offer": "f5-big-ip-best", 
                "sku": "f5-bigip-virtual-edition-1g-best-hourly"
            }
```

**Comment by kantkrish** [comment]
so for this template, my powershell to accept marketplace is this and it fails:

Get-AzureRmMarketplaceTerms -Publisher "f5-networks" -Product "f5-big-ip-best" -Name "f5-bigip-virtual-edition-1g-best-hourly" | Set-AzureRmMarketplaceTerms -Accept

**Comment by jsevedge** [comment]
What error does it return?  Also, you can accept via the portal if you go "Create a resource" -> "F5 BIG-IP Virtual Edition - BEST  (PAYG)" -> "Want to deploy programmatically? Get started" -> "Enable"

**Comment by kantkrish** [comment]
Enabling it on portal worked. 

Thanks a lot for your help!
