### ISSUE TITLE
Azure autoscale for PAVE LTM fails at onboard script

### ISSUE THREAD

**Issue by MattHembree** [F5Networks/f5-azure-arm-templates#129]
## Description
Trying to provision an autoscale Per App VE LTM 25M. A provisioning error occurs with the autoscaleconfig resource. Affects v13 and v14/latest. Should this be provisioning ASM?

[parameters-redacted.json.txt](https://github.com/F5Networks/f5-azure-arm-templates/files/3302584/parameters-redacted.json.txt)
[autoscale.log](https://github.com/F5Networks/f5-azure-arm-templates/files/3302585/autoscale.log)
[cloudLibsError.log](https://github.com/F5Networks/f5-azure-arm-templates/files/3302586/cloudLibsError.log)
[install.log](https://github.com/F5Networks/f5-azure-arm-templates/files/3302587/install.log)
[metricsCollector.log](https://github.com/F5Networks/f5-azure-arm-templates/files/3302588/metricsCollector.log)
[onboard.log](https://github.com/F5Networks/f5-azure-arm-templates/files/3302589/onboard.log)
[stderr.txt](https://github.com/F5Networks/f5-azure-arm-templates/files/3302590/stderr.txt)
[stdout.txt](https://github.com/F5Networks/f5-azure-arm-templates/files/3302591/stdout.txt)
![Capture](https://user-images.githubusercontent.com/40670053/59703695-11ce6c80-91c0-11e9-8e28-543255dd2cf0.PNG)

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/autoscale/ltm/via-lb/1nic/new-stack/payg

## Severity Level
Severity: 1

**Comment by jsevedge** [comment]
@MattHembree Thank you for bringing this to our attention, ASM should *not* be provisioned in the LTM template(s).  Internal ID 1435 opened to track, anticipate including a fix in our upcoming release.

**Comment by edwoodjrjr** [comment]
@MattHembree The unintended ASM provisioning has been fixed in https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v7.0.0.0.  Let us know if you need anything else.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with release 7.0.0.0.
