### ISSUE TITLE
Post-deployment config checks

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-azure-arm-templates#13]
##### ISSUE TYPE

 - Configuration issue

##### BIGIP VERSION
```
BIG-IP   13.0.0  2.10.1671 
```
##### TEMPLATE

https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/solutions/autoscale/waf/readme.md

##### CONFIGURATION

blockingLevel 	

Select how aggressive you want the blocking level of this WAF. Remember that the more aggressive the blocking level, the more potential there is for false-positives that the WAF might detect. Select Custom to specify your own security policy.

##### SUMMARY
The template includes a parameter called "blockingLevel" that apparently decides the number of signatures used for blocking threats. I left this default and successfully deployed the template but did not find any related policy configuration that reflects this setting. 

Is a security policy supposed to be created on BIG-IP or elsewhere? If not, when does the value of this parameter get used?

##### STEPS TO REPRODUCE
```
1. Configure backend servers in Azure 

2. Configure app registration for purpose of API access

    - confirm tenantID (Directory ID)  

    - confirm clientID (Application ID)

    - confirm service principal secret (API Access key value)

3. Deploy arm template, setting blockingLevel to medium

4. Do post-deployment config as necessary on ALB

5. Confirm BIG-IP config, do BIG-IP pool, VIP config
```
##### EXPECTED RESULTS
A security policy ready to deploy to a virtual server. 

##### ACTUAL RESULTS

No ASM config 

##### TROUBLESHOOTING

checked known documentation
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/solutions/autoscale/waf/readme.md

**Comment by edwoodjrjr** [comment]
This template should configure an iApp named f5.policy_creator that creates both an ASM policy and LTM policy that references it, and then deploys the f5.http iApp that references the LTM policy.  You should end up with a working deployment without having to do any post-deployment config on BIG-IP.  If these objects aren't being created then we'll need to investigate why not (I tested this last Thursday and they all were).

**Comment by tkam8** [comment]
I'll try to take a look at these myself. Also, pasting some ltm logs in case you need to see when mcpd came up
##### /var/log/ltm
Jun 25 08:18:04 terrybip1-vmss_0 info mprov:17807:: 'fyi: mcpd is up'
----snip----
Jun 25 08:21:23 terrybip1-vmss_0 notice sod[6049]: 010c0053:5: Active for traffic group traffic-group-1.
Jun 25 08:21:23 terrybip1-vmss_0 notice sod[6049]: 010c0019:5: Active
Jun 25 08:21:23 terrybip1-vmss_0 notice tmm1[24401]: 01340011:5: HA unit 1 state change: from 0 to 1.
Jun 25 08:21:23 terrybip1-vmss_0 notice tmm[24401]: 01340011:5: HA unit 1 state change: from 0 to 1.
Jun 25 08:21:23 terrybip1-vmss_0 notice sod[6049]: 010c0049:5: Tmm ready - links up.

##### cat /var/lib/waagent/custom-script/download/0/stdout

see attached:
[stdout20170625.txt](https://github.com/F5Networks/f5-azure-arm-templates/files/1101098/stdout20170625.txt)


##### cat /var/lib/waagent/custom-script/download/0/stderr

see attached:
[stderr20170625.txt](https://github.com/F5Networks/f5-azure-arm-templates/files/1101099/stderr20170625.txt)

**Comment by tkam8** [comment]
Looks like an "RBAC" issue...probably screwed up my app registration. Seems the azure CLI is better for setting up the service principal to have the correct permissions for the subscription. I will redo my setup using CLI, if you have any tips at all, please let me know. 

> 2017-06-25T08:21:26.881Z error: [scripts/autoscale.js] The client 'c7904a4a-87e0-48f5-b470-2c4bf5dfc0dd' with object id 'c7904a4a-87e0-48f5-b470-2c4bf5dfc0dd' does not have authorization to perform action 'microsoft.Compute/virtualMachineScaleSets/networkInterfaces/read' over scope '/subscriptions/b52560d2-63bb-4bdd-b883-04c9dbc57b39/resourceGroups/WAF-demo1/providers/microsoft.Compute/virtualMachineScaleSets/terrybip1-vmss'.

**Comment by edwoodjrjr** [comment]
Makes sense, I don't see the iApps being run in your logs, most likely because it never got past electing a master for the cluster.

They've made it app registrations easier to do using the portal:  https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal

Just need to make sure that the app has the Contributor role assigned for the resources you are modifying (for testing it's easiest to just assign it at the subscription level).

**Comment by tkam8** [comment]
Redoing my rbac fixed this, thanks for your help pointing me to the right logs. 

Another thing, any particular reason the bigip vnet is in 10.0.0.0/16 ("vnetAddressPrefix": "10.0.0.0/16",) and not a /24? thanks

**Comment by edwoodjrjr** [comment]
No particular reason, the subnet it's deployed into is a /24 but I suppose we could limit that further to reduce possible "overlapping address space" conflicts in the portal.  We really should allow an address space choice when doing new stack, actually.  

Going to close this issue.
