### ISSUE TITLE
Failure in n-nic existing stack template

### ISSUE THREAD

**Issue by edwoodjrjr** [F5Networks/f5-azure-arm-templates#130]
## Do you already have an issue opened with F5 support?
No

## Description
Looks like we are missing the externalIpSelfAddressRangeStart parameter:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidTemplate\",\r\n \"message\": \"Unable to process template language expressions for resource '/subscriptions/78bac733-f052-4c89-ab62-ac2cd641f255/resourceGroups/zlusslo/providers/Microsoft.Network/networkInterfaces/zlusslo-ext' at line '734' and column '9'. 'The template parameter 'externalIpSelfAddressRangeStart' is not found. Please see https://aka.ms/arm-template/#parameters for usage details.'\",\r\n \"additionalInfo\": [\r\n {\r\n \"type\": \"TemplateViolation\",\r\n \"info\": {\r\n \"lineNumber\": 734,\r\n \"positionNumber\": 9,\r\n \"snippet\": \"\"\r\n }\r\n }\r\n ]\r\n }\r\n}"}]}

## Template
n-nic existing stack

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Tracking with internal issue 1457.

**Comment by jsevedge** [comment]
This issue was resolved in https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v7.0.0.1
