### ISSUE TITLE
ASGs get wiped after failover in HA cluster

### ISSUE THREAD

**Issue by adcccamargo** [F5Networks/f5-azure-arm-templates#134]
## Description
Failover in HA cluster via API on BYOL wipes out any Application Security Groups assigned to the network interfaces

Reproduce:
- Assign an ASG to -ext interfaces to both Active / Standby
- Failover
- ASGs are removed from Active / Standby -ext interfaces

## Template
f5-azure-arm-templates/supported/failover/same-net/via-api/n-nic/existing-stack/byol/

## Severity Level
3

**Comment by edwoodjrjr** [comment]
Hi @adcccamargo, sorry to hear that you are having this issue.  I created internal issue #1533 to track this.  Will update here when a fix is released.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with the [Cloud Failover Extension](https://github.com/F5Networks/f5-cloud-failover-extension).
