### ISSUE TITLE
Support multiple values in restrictedSourceAddress

### ISSUE THREAD

**Issue by mikeshimkus** [F5Networks/f5-azure-arm-templates#135]
## Do you already have an issue opened with F5 support?
No

## Description
We currently only support a single IP, network, or wildcard in the restrictedSourceAddress field (which feeds sourceAddressPrefix in the template NSG rule resource definition).

If we switch to sourceAddressPrefixes, we can support a comma-delimited list of IPs/networks in the restricteSourceAddress parameter.

## Template
AOTK

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Hi edwoodjrjr, I have created internal issue 1566 for tracking this request.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
