### ISSUE TITLE
external ip's compatibility with AS3 

### ISSUE THREAD

**Issue by yossi-r** [F5Networks/f5-azure-arm-templates#136]
## Do you already have an issue opened with F5 support?
No

## Description
I'm deploying the 'failover' template with external ip's. 
after deployment i'm sending an AS3 declaration with the VIP address as one of those public ip's. 
the declaration fails because the ip address already exist in the /Common partition. 
when the template deploys it creates 'virtual addresses' on the bigip in the common partition. i guess that it does that to support the HA script. 

my expectation is that after deploying the template i should be able to immediately send an as3 declaration with the external ip. 

if the template can just create the external ip's as it does today and not create the virtual addresses on the bigip that would be an acceptable solution. 

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/bigiq

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Hi Yossi, that is true but the failover provider script does not currently support recursing through AS3 tenants to find virtual addresses (we have internal issue #1565 to track that work).  I'll ping you offline.
Michael

**Comment by shyawnkarim** [comment]
Closing. Failover is now handled by the [Cloud Failover Extension](https://github.com/F5Networks/f5-cloud-failover-extension) and it supports virtual addresses in tenants.
