### ISSUE TITLE
Support for multiple IP address on internal nic 

### ISSUE THREAD

**Issue by danschuster11** [F5Networks/f5-azure-arm-templates#137]
## Do you already have an issue opened with F5 support? 
No

## Describe the problem you're having or the enhancement you'd like to request.
Using a 3 nic (external, internal, mgmt) template there is an ability to create multiple External IPs via numberOfExternalIps parameter.  

There is a need for internal to Azure load balancing and having a similar parameter available for load balancing on the internal nic, something like numberOfInternalIps.

Do not want to target the private IPs associated with the external nic, but to have the ability through the template to support multiple internal IP addresses on the internal nic.

**Comment by shyawnkarim** [comment]
Thank you for taking the time to submit this issue to us.

I've gone ahead and created an issue in Jira (#1579) to add this functionality.

**Comment by rftoccijr** [comment]
Any traction on this?  I recently had a customer deploy using this model, and had to do a bit of manual work to get it going.

**Comment by shyawnkarim** [comment]
This enhancement is still in our backlog and on the team's radar.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
