### ISSUE TITLE
BIG-IQ cluster 2-nic template(s) contains invalid runtime expression (0/start defined multiple times)

### ISSUE THREAD

**Issue by jsevedge** [F5Networks/f5-azure-arm-templates#138]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Describe the problem you're having or the enhancement you'd like to request.

“Deployment template validation failed: 'The resource 'Microsoft.Compute/virtualMachines/foo-f5vm0/extensions/start' at line '819' and column '9' is defined multiple times in a template. Please see https://aka.ms/arm-template/#resources for usage details.'. (Code: InvalidTemplate)“

https://github.com/F5Networks/f5-azure-arm-templates/blob/cc58dd915709c87135f3a149555dab016b16f154/experimental/bigiq/licenseManagement/cluster/2nic/new-stack/byol/azuredeploy.json#L852

## Template
For bugs, enter the template with which you are experiencing issues below.

/experimental/bigiq/licenseManagement/cluster/2nic/new-stack/byol/azuredeploy.json

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 1

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by jsevedge** [comment]
Instance '0' appears correct, the issue is instance '1' needs the following change:
`"name": "[concat(variables('dnsLabel'), '-', variables('instanceName'), '0/start')]"`
to
`"name": "[concat(variables('dnsLabel'), '-', variables('instanceName'), '1/start')]"`

**Comment by gituser2291** [comment]
I am still receiving this same bug as well.  Has this code been update to represent this change and an acceptable solution?

**Comment by jsevedge** [comment]
@gituser2291 The currently released template does not contain this fix, the short term workaround is to edit a local copy of the template with the above fix.

**Comment by gituser2291** [comment]
@jsevedge  I'm using the 3 nic template with failover over api and byol, the code might be a bit different but I can try this and let you know.

**Comment by jsevedge** [comment]
I am not aware of an issue with that template, can provide more details on link to template using and the error you get back?

**Comment by gituser2291** [comment]
@jsevedge  this is the error I receive: 

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'start'. Error message: \\\"Enable failed: processing file downloads failed: failed to download file[0]: failed to download file: http request failed: Get [REDACTED] dial tcp: i/o timeout\\\".\"\r\n }\r\n ]\r\n }\r\n}"},{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'start'. Error message: \\\"Enable failed: processing file downloads failed: failed to download file[0]: failed to download file: http request failed: Get [REDACTED] dial tcp: i/o timeout\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by jsevedge** [comment]
@gituser2291 That looks like an issue with the BIG-IP not being able to download files from the internet.  Is an NSG or firewall of some sort blocking that connectivity by chance?

**Comment by gituser2291** [comment]
@jsevedge here is a snapshot:

![image](https://user-images.githubusercontent.com/50557488/65463146-46883a80-de25-11e9-8fe8-a330adc43fb1.png)

**Comment by gituser2291** [comment]
@jsevedge there is no NSG or firewall, this is a brand new VNET that I just created and trying to deploy the F5 into this VNET.

**Comment by jsevedge** [comment]
Can you ssh into the BIG-IP and run the following command?

`curl --head https://cdn.f5.com/product/cloudsolutions/f5-cloud-libs/v4.9.2/f5-cloud-libs.tar.gz`

**Comment by gituser2291** [comment]
@jsevedge 
This is what I get:
curl: (6) Could not resolve host: cdn.f5.com

The F5s are not licensed even though I put the license information inside the template along with all the other network details.  It shows up as a standalone with setup utility and no license...

**Comment by gituser2291** [comment]
@jsevedge  I didn't have this problem with paygo, but now having the issue with byol.

**Comment by jsevedge** [comment]
Is the vnet you are deploying into using custom DNS?

**Comment by gituser2291** [comment]
@jsevedge  ah yes!! that may be it!

**Comment by jsevedge** [comment]
@gituser2291 Do you mean the BIG-IP wants you to go through the setup wizard when you log in?  That should not be necessary and typically means something failed during the deployment.  You could look in /var/log/cloud/azure/install.log for clues.

**Comment by gituser2291** [comment]
@jsevedge that's corrrect, the BIG-IP wants me to go through the setup wizard when I log in, even though the deployment completed successfully.

**Comment by gituser2291** [comment]
@jsevedge this is from the syslog of the deployed F5:
ltm 09-24 16:47:09 err localhost.localdomain mcpd[7326]: Configuration error: Invalid mcpd context, folder not found (/var/log/cloud/azure)
ltm 09-24 16:47:28 err localhost.localdomain mcpd[7326]: Configuration error: Invalid mcpd context, folder not found (/var/log)
ltm 09-24 16:47:32 err localhost.localdomain mcpd[7326]: Configuration error: Invalid mcpd context, folder not found (/Common/var)
ltm 09-24 16:49:18 err localhost.localdomain mcpd[7326]: Configuration error: Invalid mcpd context, folder not found (/var/log)
ltm 09-24 16:54:37 err localhost.localdomain mcpd[7326]: Configuration error: Invalid mcpd context, folder not found (/var/log/cloud)
(END)

Has anybody else tried to deploy this template? Wondering if something is wrong with the template?

**Comment by shyawnkarim** [comment]
Internal issue ESECLDTPLT-1930 created for this bug.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 8.1.1.0](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v8.1.1.0).
