### ISSUE TITLE
bigiq chargeback tag support 

### ISSUE THREAD

**Issue by yossi-r** [F5Networks/f5-azure-arm-templates#142]
## Description
Add support for BIGIQ chargeback tag when licensing using BIGIQ

Please expose an option in the template to add a chargeback tag when licensing with BIGIQ.

**Comment by shyawnkarim** [comment]
Thank you for providing this feedback. I've gone ahead and created an issue (#1664) for this request.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
