### ISSUE TITLE
Deploying failover/same-net/via-lb/3nic/existing-stack/byol/ - into Australia East consistently fails at the end of the deployment with VM has reported a failure when processing extension 'start'

### ISSUE THREAD

**Issue by joel-cloud** [F5Networks/f5-azure-arm-templates#144]
## Do you already have an issue opened with F5 support?
no
## Description
Azure deployment consistently fails with:

**
> \"VM has reported a failure when processing extension 'start'. Error message: \\\"Enable failed: processing file downloads failed: failed to download file[0]: failed to download file: http request failed: Get [REDACTED] dial tcp: i/o timeout
**

## What I am doing?

I'm trying to deploy a HA pair with LB into a prod subscription with existing subnets, after a lot of messing around i have the template deploying pretty much to the end. You can see the resource group and all the resource deployed, right at the end of the deployment something doesn't work and it fails. I would like the deployment to complete properly.

After the failed deployment, i can go and login to the F5's and configure them and everything works okay, however i would like the deployment to complete properly so we have confidence nothing was skipped .

BTW, because we are deploying into Australia East, we need to set the "zonesAvailable": false - everything else is as per the template.

## Template

Using this template **f5-azure-arm-templates/supported/failover/same-net/via-lb/3nic/existing-stack/byol/** deploying to a production subscription in Australia East.

## Severity Level

Severity:  annoying.

**Comment by shyawnkarim** [comment]
Thanks for taking the time to reach out to us with your issue. I've  created Jira ticket #1719 to look into this.

**Comment by wafdemos** [comment]
+1

**Comment by joel-cloud** [comment]
just deployed again into Melbourne and same error.
![image](https://user-images.githubusercontent.com/57674846/70118077-e7f7fc00-16b2-11ea-9766-e41abbb82f34.png)

**Comment by jainvijay1** [comment]
We are also seeing the same problem while deploying this template. Is this fixed?or any Workaround?
