### ISSUE TITLE
Deploying 1-nic same-net via-lb fails

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#145]
## Description
Deploying the same-net PAYG 1-nic HA (via LB) template but failed twice already.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/1nic/new-stack/payg

## Severity Level
3

##Error
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'start'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=1\\n[stdout]\\n-25T17:02:59.293Z info: Setting global settings. \\n2019-11-25T17:03:02.305Z info: Setting DB vars. \\n2019-11-25T17:03:04.814Z info: Provisioning modules {\\\"ltm\\\":\\\"nominal\\\"}\\n2019-11-25T17:03:06.548Z info: Installing package at path: /var/config/rest/downloads/f5-appsvcs-3.5.1-5.noarch.rpm \\n2019-11-25T17:03:17.694Z info: Saving config. \\n2019-11-25T17:03:24.281Z info: Waiting for device to be active. \\n2019-11-25T17:03:28.019Z info: Sending metrics \\n2019-11-25T17:03:28.453Z info: Device onboard complete. \\n2019-11-25T17:03:31.566Z info: Onboard finished. \\n2019-11-25T17:03:31.856Z info: /config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs/scripts/cluster.js called with /usr/bin/f5-rest-node /config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs/scripts/cluster.js --output /var/log/cloud/azure/cluster.log --log-level info --host 10.0.1.5 --port 8443 -u svc_user --password-url file:///config/cloud/.passwd --password-encrypted --config-sync-ip 10.0.1.5 --join-group --device-group Sync --sync --remote-host 10.0.1.4 --remote-user svc_user --remote-password-url file:///config/cloud/.passwd \\n2019-11-25T17:03:31.864Z info: Cluster starting. \\n2019-11-25T17:03:31.866Z info: Initializing BIG-IP. \\n2019-11-25T17:03:31.880Z info: This is a BIG-IP \\n2019-11-25T17:03:44.658Z info: Waiting for device to be ready. \\n2019-11-25T17:03:47.266Z info: Waiting for BIG-IP to be ready. \\n2019-11-25T17:03:48.982Z info: BIG-IP is ready. \\n2019-11-25T17:03:49.040Z info: Setting config sync ip. \\n2019-11-25T17:03:53.752Z info: Joining group. \\n2019-11-25T17:03:53.805Z info: This is a BIG-IP \\n2019-11-25T17:04:04.910Z info: Waiting for device to be ready. \\n2019-11-25T17:04:47.666Z info: Checking remote host for cluster readiness. \\n2019-11-25T17:06:48.446Z info: Getting local hostname for trust. \\n2019-11-25T17:06:48.468Z info: Getting local management address. \\n2019-11-25T17:06:49.202Z info: Adding to remote trust. \\n2019-11-25T17:07:15.904Z info: Adding to remote device group. \\n2019-11-25T17:07:25.561Z info: Checking for datasync-global-dg. \\n2019-11-25T17:07:28.293Z info: Telling remote to sync. \\n2019-11-25T17:08:00.448Z info: Waiting for sync to complete. \\n2019-11-25T17:08:39.271Z info: Sync not yet complete. \\n2019-11-25T17:09:09.271Z info: Telling remote to sync. \\n2019-11-25T17:09:41.484Z info: Waiting for sync to complete. \\n2019-11-25T17:10:19.142Z info: Sync not yet complete. \\n2019-11-25T17:10:49.143Z info: Telling remote to sync. \\n2019-11-25T17:11:20.957Z info: Waiting for sync to complete. \\n2019-11-25T17:11:59.747Z info: Sync not yet complete. \\n2019-11-25T17:12:29.747Z info: Telling remote to sync. \\n2019-11-25T17:13:02.096Z info: Waiting for sync to complete. \\n2019-11-25T17:13:38.884Z info: Sync not yet complete. \\n2019-11-25T17:14:08.885Z info: Telling remote to sync. \\n2019-11-25T17:14:40.601Z info: Waiting for sync to complete. \\n2019-11-25T17:15:14.464Z info: Sync not yet complete. \\n2019-11-25T17:15:44.465Z info: Telling remote to sync. \\n2019-11-25T17:16:15.254Z info: Waiting for sync to complete. \\n2019-11-25T17:16:48.618Z info: Sync not yet complete. \\n2019-11-25T17:17:18.619Z info: Telling remote to sync. \\n2019-11-25T17:17:49.226Z info: Waiting for sync to complete. \\n2019-11-25T17:18:21.892Z info: Sync not yet complete. \\n2019-11-25T17:18:51.892Z info: Telling remote to sync. \\n2019-11-25T17:19:22.451Z info: Waiting for sync to complete. \\n2019-11-25T17:19:54.936Z info: Sync not yet complete. \\n2019-11-25T17:20:24.937Z info: Telling remote to sync. \\n2019-11-25T17:20:55.685Z info: Waiting for sync to complete. \\n2019-11-25T17:21:28.517Z info: Sync not yet complete. \\n2019-11-25T17:21:58.517Z info: Telling remote to sync. \\n2019-11-25T17:22:29.039Z info: Waiting for sync to complete. \\n2019-11-25T17:23:01.216Z info: Sync not yet complete. \\n2019-11-25T17:23:31.217Z info: Telling remote to sync. \\n2019-11-25T17:24:01.752Z info: Waiting for sync to complete. \\n2019-11-25T17:24:33.991Z info: Sync not yet complete. \\n2019-11-25T17:24:33.991Z info: join cluster failed: tryUntil: max tries reached: unknown \\n\\n[stderr]\\n{\\n \\\"level\\\": \\\"error\\\",\\n \\\"message\\\": \\\"Cluster failed: tryUntil: max tries reached: unknown\\\",\\n \\\"label\\\": \\\"lib/bigIpOnboard.js\\\",\\n \\\"timestamp\\\": \\\"2019-11-25T17:24:33.994Z\\\"\\n}\\n2019-11-25T17:24:33.994Z error: Cluster failed: tryUntil: max tries reached: unknown \\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by shyawnkarim** [comment]
I just deployed this template without any issue. Can you let me know if this template continues to fail deployment?

**Comment by JeffGiroux** [comment]
I deployed 2x and had same results before opening ticket. I just saw another new issue pop into queue with "existing stack big-iq" also failing. I'll try another region. My first two failed attempts happened in US-West2.

**Comment by JeffGiroux** [comment]
Tried US-West, same error as US-West-2. I'll try a 3-nic template next. By the way, when I logged into each F5 in failed state, they were unlicensed and not setup yet. Deployment fails on task Microsoft.Compute/virtualMachines/extensions for one F5 instance.

**Comment by JeffGiroux** [comment]
I just tried deploying two more times and they both succeeded. Go figure! I tried a Best 1Gb image just in case the 25Mb Good was the culprit. Best 1Gb succeeded, so I tried 25Mb Good and it too succeeded. I already deleted the other F5 instances that failed, so unfortunately the logs on the local instances are gone.

Close this. Must have been a cloud hiccup.
