### ISSUE TITLE
documentation update: HA via api does not use availability set

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#147]
## Do you already have an issue opened with F5 support?
no

## Description
The template for HA via API readme has a references to using availability sets. I just deployed the template, both F5s land in a different zone, but they are not in an available set. In fact, the ARM template doesn't create an AV set.

Do docs need updating? My deployment works, but docs are conflicting with what actually gets deployed.

example README
This solution uses an ARM template to launch two BIG-IP VEs in an Active/Standby configuration with network failover enabled (the template now supports multiple traffic groups which enables active/active deployments). Each pair of BIG-IP VEs is deployed in an Azure Availability Set, and can therefore be spread across different update and fault domains

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/new-stack/payg

## Severity Level
3

**Comment by JeffGiroux** [comment]
Another reference to "availability sets"...

All templates deploy Azure Virtual Machines and Virtual Machine Scale Sets into Availability Zones in supported regions; Availability Sets are still created in unsupported regions. Virtual Machine Scale Sets are distributed across zones 1, 2, and 3; failover Virtual Machines across zones 1 and 2. Standalone Virtual Machines are placed in zone 1 by default; however, you may select zone 1, 2, or 3 using the new zoneChoice parameter

**Comment by shyawnkarim** [comment]
Good catch. The default behavior is to deploy into separate availability zones, if supported, and then to fall back to availability sets if not.

I'll submit a documentation bug right away.

Thanks for raising this issue.

**Comment by JeffGiroux** [comment]
Confirmed. I just deployed a second template to US West and indeed see an availability set there. Depends on region and "if supported". Thx, close. Nothing more on my side.
