### ISSUE TITLE
HA via lb 1nic templates deploy both F5s to same availability zone

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#148]
## Do you already have an issue opened with F5 support?
No

## Description
In my various template testing, it looks like 1nic HA via LB templates using regions that support AZs do NOT deploy the F5 instances to different zones. In my testing, they both were deployed to fault domain 1. This only applies to regions that support AZs. For regions that do not, the template falls back to availability sets which result in the F5s properly deploying to different fault domains.

Further troubleshooting...I tried a few more templates to validate behavior.
1. I tried N-Nic HA via API and that successfully places F5s in different zones.
2. I tried 3-Nic HA via LB and that successfully places F5s in different zones.
3. But...trying 1-nic HA via LB will result in both F5s in zone 1

Other notes...
I have only been trying PAYG templates. Not sure if BYOL or BIGIQ has similar issues.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/1nic/new-stack/payg

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
Marking this as 2. I would mark as 3, but we need corrected ASAP in order to have proper cloud design for failover and resiliency. The F5 instances should land in different fault domains (zones).

**Comment by shyawnkarim** [comment]
Thank you for reporting this issue. I have created internal issue ESECLDTPLT-1963 for this.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
