### ISSUE TITLE
documention update: Azure REST API management FQDN needed

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#149]
## Do you already have an issue opened with F5 support?
No

## Description
It would be nice to make note or supply a link in our templates (all of the READMEs) that indicate the Azure REST API endpoint. I had a customer fail some API calls during failover with connection refused. He asked for the specific endpoint called by the F5 API failover scripts. I could not find this in our ARM templates.

We (F5) know the URL because it's in our failover.js script. 
https://github.com/F5Networks/f5-cloud-libs-azure/blob/master/scripts/failover.js#L197

We should make a note of that FQDN "management.azure.com" somewhere on each ARM template README. The URL might change, so it's also helpful to reference the actual Azure doc links. Example below which shows the URL for REST API.

https://docs.microsoft.com/en-us/rest/api/azure/

## Template
All templates

## Severity Level
4

**Comment by shyawnkarim** [comment]
Thanks for submitting this issue. I've created Jira issue #1742 to get this added into our READMEs.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
