### ISSUE TITLE
documentation update: Add detail around UDR route creation

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#150]
## Do you already have an issue opened with F5 support?
No

## Description
The info in the README files indicate the use of managedRoutes. It says to enter an address prefix during ARM deployment. If you need to add more address prefixes at a later date, then modify the /config/cloud/managedRoutes file. That info makes sense. 

What is missing? The Azure steps. There are references in the README to create a new route table, add appropriate tags, select address prefix and corresponding next hop F5 IP. But, that section is lacking in detail. To a newbie Azure user, they are lost post-F5 deployment. Detailed steps are needed for the F5 end-user to know how to create the route table (or modify existing), and then which subnets should be associated. This of course will depend on customer design, but the current documentation is lacking to the point where failover doesn't work unless customer creates RT correctly, adds tags correctly, has the correct managedRoute prefix, AND also associates that new RT with the required subnets. Suggestions add screenshots of RT creation, tagging, route update, and subnet association in "example network" diagram would help. 

This might not be the place for it (github repo README file). A better alternative place for something of this info detail should go on the F5 clouddocs Azure section https://clouddocs.f5.com/cloud/public/v1/azure_index.html. A new section for "Managing UDR Routes Tables and Routes" would be appropriate.

## Template
For bugs, enter the template with which you are experiencing issues below.

## Severity Level
4

**Comment by JeffGiroux** [comment]
Example screenshot walk through...
[How To - Azure UDR Creation.pdf](https://github.com/F5Networks/f5-azure-arm-templates/files/3924716/How.To.-.Azure.UDR.Creation.pdf)

**Comment by shyawnkarim** [comment]
Thanks for submitting this issue. I've gone ahead and created Jira issue #1743 for this.

**Comment by JeffGiroux** [comment]
Hi, this ticket and documentation result needs to change due to the recent template updates. This applies to all cloud providers where managedRoutes are used and READMEs have not been updated. For example, managedRoutes still is explained in README with incorrect tag requirements. The CFE extension has different requirements. All cloud template README files should be updated with correct docs for managedRoutes.

**Comment by JeffGiroux** [comment]
Also applies to parameter table and the description for each value as well as the link further down in the page here...
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/new-stack/payg#customizing-the-next-hop-of-azure-user-defined-routes

**Comment by JeffGiroux** [comment]
Any updates to this. Docs are still needing updates. There is a dead link too.
https://github.com/F5Networks/f5-azure-arm-templates/tree/main/supported/failover/same-net/via-api/n-nic/existing-stack/byol

"For details, see Customizing the Next Hop of Azure User-Defined Routes."

dead = https://github.com/F5Networks/f5-azure-arm-templates/tree/main/supported/failover/same-net/via-api/n-nic/existing-stack/byol#customizing-the-next-hop-of-azure-user-defined-routes
