### ISSUE TITLE
failover via API taking 8 minutes

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#151]
## Do you already have an issue opened with F5 support?
No

## Description
In my last week of testing, the failover via API is taking 8 minutes to move the secondary IPs. The UDR route updates happen within 10 seconds. In the past, i have seen Azure REST API take anywhere from 30-90 seconds. Now it's consistently 8 minutes to pass the IPs to the other VM NIC.

Is there a known MS issue? Anything F5 can do in the templates to "retry" or force the change to happen faster?

I'm using the CF failover extentions, but the built-in scripts (via ARM template deployment) still hits the same Azure REST API and still has the same delay. UDR routes update quickly (10 seconds) but the private additional IPs take forever.

## Template
Any API method based template

## Severity Level
3

**Comment by JeffGiroux** [comment]
For example...snippet of timing in logs...in this example it took nearly 10 minutes.

Thu, 05 Dec 2019 22:41:28 GMT - info: [f5-cloud-failover: failover.js] Performing failover - execute
Thu, 05 Dec 2019 22:41:28 GMT - info: [f5-cloud-failover: failover.js] Performing Failover - discovery
Thu, 05 Dec 2019 22:41:29 GMT - info: [f5-cloud-failover: failover.js] Performing Failover - update
Thu, 05 Dec 2019 22:41:29 GMT - fine: [f5-cloud-failover: failover.js] Disassociate NIC:  jgdemo-ext0
Thu, 05 Dec 2019 22:41:29 GMT - info: [f5-cloud-failover: failover.js] Update routes successful.
Thu, 05 Dec 2019 22:51:00 GMT - info: [f5-cloud-failover: failover.js] Disassociate NICs successful.
Thu, 05 Dec 2019 22:51:00 GMT - fine: [f5-cloud-failover: failover.js] Associate NIC:  jgdemo-ext1
Thu, 05 Dec 2019 22:52:00 GMT - info: [f5-cloud-failover: failover.js] Associate NICs successful.
Thu, 05 Dec 2019 22:52:00 GMT - info: [f5-cloud-failover: failover.js] Failover complete

**Comment by shyawnkarim** [comment]
Sat, 21 Dec 2019 00:13:23 GMT - info: [f5-cloud-failover: failover.js] Performing Failover - discovery
Sat, 21 Dec 2019 00:15:24 GMT - info: [f5-cloud-failover: failover.js] Failover complete

I just ran it and it took 2 minutes. Let me know if you continue to see slow performance.

**Comment by JeffGiroux** [comment]
I’ll try to repro again.

This was specific to one or two regions in my testing, and I don’t recall which regions. I was testing with customer the day after I opened this ticket and his failover only took 90 seconds in South Central region.
