### ISSUE TITLE
Failover/viaLB/existing stack ARM template fails when "ProvisionPublicIP" parameter is set to NO

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/f5-azure-arm-templates#152]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Deploying following ARM template "https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol" fails when "ProvisionPublicIP" parameter is set to "No"

Error message is :
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidResourceReference\",\r\n    \"message\": \"Resource /subscriptions/1005fe30-e19e-4091-8480-8b61ecb8XXXX/resourceGroups/TEWFIKDEVTEST10/providers/Microsoft.Network/publicIPAddresses/TEWFIKDEVTEST11-EXT-PIP0 referenced by resource /subscriptions/1005fe30-e19e-4091-8480-8b61ecb8XXXX/resourceGroups/tewfikdevtest10/providers/Microsoft.Network/loadBalancers/tewfikdevtest11-ext-alb was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"NotFound\",\r\n        \"message\": \"Resource /subscriptions/1005fe30-e19e-4091-8480-8b61ecbXXXX/resourceGroups/TEWFIKDEVTEST10/providers/Microsoft.Network/publicIPAddresses/TEWFIKDEVTEST11-EXT-PIP0 not found.\"\r\n      }\r\n    ]\r\n  }\r\n}"
    }
  ]
}

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

**Comment by shyawnkarim** [comment]
Thanks for reporting your issue. There is currently a Jira issue #1703 in progress to fix this behavior. When ProvisionPublic=0 the template will create an internal IP.

**Comment by tewfikm** [comment]
Fixed here : https://github.com/tewfikm/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol.
Feel free to pull.
