### ISSUE TITLE
Failover/viaLB/existing stack ARM template fails when "numberOfExternalIps" parameter is set to 0

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/f5-azure-arm-templates#153]
## Description
Deploying following ARM template "https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol" fails when "numberOfExternalIps" parameter is set to 0.

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidResourceReference\",\r\n    \"message\": \"Resource /subscriptions/1005fe30-e19e-4091-8480-8b61ecb8106e/resourceGroups/tewfikdevtest10/providers/Microsoft.Network/loadBalancers/tewfikdevtest11-ext-alb/backendAddressPools/loadBalancerMgmtBackEnd referenced by resource /subscriptions/1005fe30-e19e-4091-8480-8b61ecb8106e/resourceGroups/tewfikdevtest10/providers/Microsoft.Network/networkInterfaces/tewfikdevtest11-mgmt1 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.\",\r\n    \"details\": []\r\n  }\r\n}"
    },
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidResourceReference\",\r\n    \"message\": \"Resource /subscriptions/1005fe30-e19e-4091-8480-8b61ecb8106e/resourceGroups/tewfikdevtest10/providers/Microsoft.Network/loadBalancers/tewfikdevtest11-ext-alb/backendAddressPools/loadBalancerMgmtBackEnd referenced by resource /subscriptions/1005fe30-e19e-4091-8480-8b61ecb8106e/resourceGroups/tewfikdevtest10/providers/Microsoft.Network/networkInterfaces/tewfikdevtest11-mgmt0 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.\",\r\n    \"details\": []\r\n  }\r\n}"
    }
  ]
}

When "numberOfExternalIps" parameter is set to 0, external ALB is not created and hence, adress pools objects are missing but requested MGMT interfaces.

Since external ALB does requires Public IP object, I suggest to exclude the value 0 from the range => range to start from 1.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol

## Severity Level
Severity: 2

**Comment by shyawnkarim** [comment]
Thanks for reporting your issue. There is currently a Jira issue #1703 in progress to fix this behavior. When NumberofExternalIps=0 the template will create an internal IP.
