### ISSUE TITLE
Azure Availability set is not created or used

### ISSUE THREAD

**Issue by vadaszgergo** [F5Networks/f5-azure-arm-templates#154]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.
No case was opened yet

## Description
Describe the problem you're having or the enhancement you'd like to request.

When deploying the following template:
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/3nic/existing-stack/byol
One part is asking for availability set, if already exist, or leave the CREATE_NEW value, if we want to create new AV set. I tried both the default value (CREATE_NEW) and the existing AV set name value, in both cases nothing happened regarding AV sets, no new AV set was deployed, or the VM was not put into the existing AV set.

## Template
For bugs, enter the template with which you are experiencing issues below.
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/3nic/existing-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 4

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with your issue.

I just deployed this template with avSetChoice set to CREATE_NEW and an availability set was created with my vm placed inside of it.

Can you send me the parameters file that you are using so that I can take a look?

**Comment by vadaszgergo** [comment]
Hi, you can download the file via this link:
[parameters](https://drive.google.com/open?id=1KdkpEfl-fjKf0srmzvWKuN1h3Kpso6NP)

**Comment by vadaszgergo** [comment]
Another example parameter file: [link](https://drive.google.com/open?id=1HWy13-rTRXBGWzP3M0gc-yEel7uJOfj9)

**Comment by shyawnkarim** [comment]
I was able to to deploy both of your templates and each created an AV set with a VM inside it. What region are you deploying into?

**Comment by vadaszgergo** [comment]
Tried East US and East US 2.... weird...

**Comment by shyawnkarim** [comment]
I tested out your templates again in East US region and I got the same behavior that you described. I've gone ahead a filed a bug for this with Jira issue #1800.

When I originally was testing, I was able to successfully to deploy to West US region.

**Comment by shyawnkarim** [comment]
Engineering has taken a look at this template and it is working as designed.

This template deploys a Virtual Machine into an Availability Zone, by default, when the region supports them. Virtual Machines are placed in zone 1 by default, however, you may select zone 1, 2, or 3 using the new zoneChoice parameter. When deploying a Virtual Machine into an Availability Zone, the template ignores the avSetChoice parameter entirely. 

If the region does not support Availability Zones, then the avSetChoice parameter is used and a Virtual Machine will be placed inside the newly created one or the existing one that is specified. 

We plan to update the documentation to make this behavior more clear.

Thanks again for raising this issue and please continue to reach out to us.

**Comment by vadaszgergo** [comment]
Thanks for the update. Basically 95% of the regions support av-zone (as far as i remember), but does that mean if I want to use av-set, instead of any av-zone, I should use some other template, because this one forces me to use av-zone? We experienced some issues with av-zone in some specific regions, so we wanted to go for av-set, but then I guess this is not supported by this template or even by F5.

**Comment by shyawnkarim** [comment]
According to Microsoft's [documentation](https://azure.microsoft.com/en-us/global-infrastructure/regions/), only 10/56 regions support Availability Zones. Availability Zones provide a higher SLA, which is why we ignore the Availability Set parameter when Availability Zones are supported. 

We haven't seen a use case for preferring Availability Sets over Zones and do not have a template for that option. 

I'd like to hear more about your use case if you are willing to provide additional details.

**Comment by vadaszgergo** [comment]
Thanks for the update. Well we had some latency issues in some regions, when we used different AV-Zones between some active and standby network devices (for example F5). But yeah I got your point, we will do some workaround if template is built with this default settings. Thanks!
