### ISSUE TITLE
Allowing more than 20 IPs on Azure ARM Template

### ISSUE THREAD

**Issue by oneline99** [F5Networks/f5-azure-arm-templates#157]
Azure is able to support up to 256 IP addresses per interface but ARM template deployment allows only maximum of only 20 IP’s on the External interface of AWAF instance. We need to update the ARM template to allow more than 20 IPs.

**Comment by shyawnkarim** [comment]
Thanks for providing this feedback. I've created internal issue ESECLDTPLT-1854 to get the limit increased to Azure's limit.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
