### ISSUE TITLE
explain the differences between via-api and via-lb failover methods

### ISSUE THREAD

**Issue by depperson** [F5Networks/f5-azure-arm-templates#158]
## Do you already have an issue opened with F5 support?
no

## Description
Can we elaborate on the differences between via-api and via-lb on this page?
https://github.com/F5Networks/f5-azure-arm-templates/blob/v7.0.0.2/supported/failover/same-net/README.md

## Template
See above

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5 documentation request

---

Perhaps we could include the diagrams from via-api and via-lb for comparison.

https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/master/supported/failover/same-net/via-api/n-nic/new-stack/images/azure-example-diagram.png

https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/master/supported/failover/same-net/via-lb/3nic/new-stack/images/azure-example-diagram.png

What are the advantages and disadvantages of each?

**Comment by jmcalalang** [comment]
Maybe adding a link to https://devcentral.f5.com/s/articles/Lightboard-Lessons-BIG-IP-Deployments-in-Azure-Cloud, this could be on the landing README and help guide people down paths.

**Comment by shyawnkarim** [comment]
Thank you for submitting this feedback. I have created internal issue ESECLDTPLT-1926 for this documentation enhancement.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
