### ISSUE TITLE
big-iq cluster template fails mid deployment - duplicate IP address assignment

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#160]
## Do you already have an issue opened with F5 support?
no

## Description
The template fails mid deployment. VMs are not created yet. Azure stops due to failure of 10.0.1.4 already being assigned to the other VM. When checking the code, there is a missing "1" at the end of the variable.

https://github.com/F5Networks/f5-azure-arm-templates/blob/b89661e34bdfc8f07c07d7b78b18ce6ac75f9d71/experimental/bigiq/licenseManagement/cluster/2nic/new-stack/byol/azuredeploy.json#L528

line 528
wrong = "privateIPAddress": "[variables('mgmtSubnetPrivateAddress')]",
correct = "privateIPAddress": "[variables('mgmtSubnetPrivateAddress1')]",

It happens again in the "existing net" stack on line 545

https://github.com/F5Networks/f5-azure-arm-templates/blob/b89661e34bdfc8f07c07d7b78b18ce6ac75f9d71/experimental/bigiq/licenseManagement/cluster/2nic/existing-stack/byol/azuredeploy.json#L545

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/experimental/bigiq/licenseManagement/cluster/2nic/new-stack/byol

and...

https://github.com/F5Networks/f5-azure-arm-templates/blob/master/experimental/bigiq/licenseManagement/cluster/2nic/existing-stack/byol

## Severity Level
3

**Comment by shyawnkarim** [comment]
Internal issue ESECLDTPLT-1930 created for this bug.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 8.1.1.0](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v8.1.1.0).
