### ISSUE TITLE
BIG-IQ - Standalone - 1nic - Template fails at Extensions/start Cmd

### ISSUE THREAD

**Issue by ben21175** [F5Networks/f5-azure-arm-templates#162]
## Do you already have an issue opened with F5 support?
No Issue yet - will update if one is created

## Description
When Deploying the template, there is an error:
```
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'start'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=1\\n[stdout]\\nabout to execute\\nchecking mcpd\\nmcpd not ready yet\\nchecking mcpd\\nmcpd not ready yet\\nchecking mcpd\\nmcpd not ready yet\\nchecking mcpd\\nmcpd not ready yet\\nchecking mcpd\\nmcpd not ready yet\\nchecking mcpd\\nmcpd not ready yet\\nchecking mcpd\\nmcpd not ready yet\\nchecking mcpd\\nmcpd ready\\nloading verifyHash script\\nLoading configuration...\\n  /config/verifyHash\\nloaded verifyHash\\nverifying /config/cloud/f5-cloud-libs.tar.gz\\nverified /config/cloud/f5-cloud-libs.tar.gz\\nverifying f5-appsvcs-3.5.1-5.noarch.rpm\\nverified f5-appsvcs-3.5.1-5.noarch.rpm\\nverifying f5.service_discovery.tmpl\\nverified f5.service_discovery.tmpl\\nverifying f5.cloud_logger.v1.0.0.tmpl\\nverified f5.cloud_logger.v1.0.0.tmpl\\nexpanding /config/cloud/f5-cloud-libs.tar.gz f5-appsvcs-3.5.1-5.noarch.rpm f5.service_discovery.tmpl f5.cloud_logger.v1.0.0.tmpl\\n2020-03-12T13:46:53.519Z info:  /config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs/scripts/encryptDataToFile.js called with /usr/bin/f5-rest-node /config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs/scripts/encryptDataToFile.js --data-file /mnt/cloudTmp/.tmp --out-file /config/cloud/.passwd \\n2020-03-12T13:46:53.525Z info:  Encrypt data to file starting. \\n2020-03-12T13:48:53.669Z info:  Encrypting data. \\n2020-03-12T13:48:53.779Z info:  Writing encrypted data to /config/cloud/.passwd \\n2020-03-12T13:48:53.782Z info:  Encryption done. \\n2020-03-12T13:49:00.964Z info:  /config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs/scripts/encryptDataToFile.js called with /usr/bin/f5-rest-node /config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs/scripts/encryptDataToFile.js --data-file /mnt/cloudTmp/.tmp --out-file /config/cloud/.bigIqPasswd \\n2020-03-12T13:49:00.975Z info:  Encrypt data to file starting. \\n2020-03-12T13:49:02.317Z info:  Encrypting data. \\n2020-03-12T13:49:02.319Z info:  Writing encrypted data to /config/cloud/.bigIqPasswd \\n2020-03-12T13:49:02.320Z info:  Encryption done. \\nAllowUsageAnalytics:No\\n2020-03-12T13:49:03.722Z info:  /config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs/scripts/onboard.js called with /usr/bin/f5-rest-node /config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs/scripts/onboard.js --no-reboot --output /var/log/cloud/azure/onboard.log --signal ONBOARD_DONE --log-level info --cloud azure --install-ilx-package file:///var/config/rest/downloads/f5-appsvcs-3.5.1-5.noarch.rpm --host 172.29.15.50 --port 8443 -u svc_user --password-url file:///config/cloud/.passwd --password-encrypted --hostname vmf5dmzbigiq00.westeurope.cloudapp.azure.com --license-pool --big-iq-host 172.29.15.50 --big-iq-user f5licenseadmin --big-iq-password-uri file:///config/cloud/.bigIqPasswd --big-iq-password-encrypted --license-pool-name Do_Not_Create --big-ip-mgmt-address 172.29.15.50 --ntp 0.pool.ntp.org --tz UTC --modules ltm:nominal --db tmm.maxremoteloglength:2048 \\n2020-03-12T13:49:03.744Z info:  Onboard starting. \\n2020-03-12T13:49:03.746Z info:  Initializing device. \\n2020-03-12T13:49:03.771Z info:  This is a BIG-IP \\n2020-03-12T13:49:07.320Z info:  Waiting for device to be ready. \\n2020-03-12T13:49:09.089Z info:  Waiting for device to be ready. \\n2020-03-12T13:49:09.771Z info:  Device is ready. \\n2020-03-12T13:49:09.771Z info:  Setting up NTP. \\n2020-03-12T13:49:10.588Z info:  Setting hostname to vmf5dmzbigiq00.westeurope.cloudapp.azure.com \\n2020-03-12T13:49:21.852Z info:  Setting global settings. \\n2020-03-12T13:49:22.952Z info:  Setting DB vars. \\n2020-03-12T13:49:23.686Z info:  Getting license from BIG-IQ license pool. \\n2020-03-12T14:04:27.459Z info:  Unable to initialize device tryUntil: max tries reached: connect ECONNREFUSED 172.29.15.50:443 \\n2020-03-12T14:04:27.460Z info:  Unable to initialize BIG-IQ tryUntil: max tries reached: connect ECONNREFUSED 172.29.15.50:443 \\n2020-03-12T14:04:27.460Z info:  Error licensing via BIG-IQ tryUntil: max tries reached: connect ECONNREFUSED 172.29.15.50:443 \\n\\n[stderr]\\n{\\n  \\\"level\\\": \\\"error\\\",\\n  \\\"message\\\": \\\"Onboard failed: tryUntil: max tries reached: connect ECONNREFUSED 172.29.15.50:443\\\",\\n  \\\"label\\\": \\\"lib/bigIq.js\\\",\\n  \\\"timestamp\\\": \\\"2020-03-12T14:04:27.462Z\\\"\\n}\\n2020-03-12T14:04:27.467Z error:  Onboard failed: tryUntil: max tries reached: connect ECONNREFUSED 172.29.15.50:443 \\n\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"
    }
  ]
}
```
Seems that when starting there is a deamon/service not spinning up?

We are trying to instal version 14.1.2000.

## Template
f5-azure-arm-templates/supported/standalone/1nic/existing-stack/bigiq/

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2
(Prevents a deployment and is blocking a project)
Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by JeffGiroux** [comment]
Is this your BIG-IQ license server? 172.29.15.50

In error logs...
connect ECONNREFUSED 172.29.15.50:443

Is that endpoint reachable by your BIG-IP? Do you have proper rules in the firewall and/or network security groups? What happens when you "telnet 172.29.15.50 443" from the BIG-IP cli.

**Comment by ben21175** [comment]
@JeffGiroux 
Thanks for the reply. 
The IP 172.29.15.50 is defined for the Big-IQ server (which is defined as the IP for the params bigIqAddress and mgmtIpAddress in the template that is failing). 
The Big-IQ (172.29.15.50) will be the license server for the Big-IPs. 
The endpoint is not reachable, as its not deployed correctly (its trying to reach itself).

Have I used the wrong values? The description in the template asks for the Big-IQ address (Which is what we are trying to deply).

Does this also explain the s=error "mcpd not ready yet"?

We currently have 3 clusters, and 2 standalone Big-IP VE's deployed (8 VMs) and the intentention to to deploy 2 Big-IQs using this template (Mgt and logging).

**Comment by JeffGiroux** [comment]
The BIG-IQ license manager templates found in experimental are currently not fully onboarding the BIG-IQ device and instead fails. I have a dev branch repo I forked to make some adjustments and also created a few github issues related to the BIG-IQ LM template. That being said, I would suggest you look at the github F5devcentral bucket. The BIG-IQ PM team has a few templates for BIG-IQ that work 100%...just tested last week.

https://github.com/f5devcentral/f5-big-iq-trial-quick-start/tree/7.0.0/azure

This will deploy a single BIG-IQ manager and single BIG-IQ logging node using latest available 7.x code in marketplace. 

Then...once you have a BIG-IQ up and running with some license keys, now you can run a BIG-IP template deployment that pulls licensing from BIG-IQ similar to the template you tried initially when opening this ticket.

**Comment by ben21175** [comment]
@JeffGiroux - I think thats where the confusion lied - we thought this template was for the Big-IQ. 

I used powershell to deploy the Big-IQ vm's in the end (there was a good F5 article about it).
