### ISSUE TITLE
BIG-IQ LM cluster 2-nic fails to launch 2nd VM - bigiq-cluster-int-pip1 not found

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#164]
## Do you already have an issue opened with F5 support?
No

## Description
After manually applying workaround for the following issues (https://github.com/F5Networks/f5-azure-arm-templates/issues/160 and https://github.com/F5Networks/f5-azure-arm-templates/issues/138) my BIG-IQ LM cluster only launches one VM successfully. The other VM fails in Azure resource deploy and never launches.

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidResourceReference\",\r\n    \"message\": \"Resource /subscriptions/xxxxx/resourceGroups/giroux-bigiq-cluster2/providers/Microsoft.Network/publicIPAddresses/jg-bigiq-cluster-int-pip1 referenced by resource /subscriptions/xxxxx/resourceGroups/giroux-bigiq-cluster2/providers/Microsoft.Network/networkInterfaces/jg-bigiq-cluster-int1 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.\",\r\n    \"details\": []\r\n  }\r\n}"
    }
  ]
}

Also, the one VM that successfully launches ends up failing the onboard process similar to current issue https://github.com/F5Networks/f5-azure-arm-templates/issues/161. 

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/experimental/bigiq/licenseManagement/standalone/2nic/existing-stack/byol

## Severity Level
2

**Comment by JeffGiroux** [comment]
Here's the problem line in the code. There is only 1x public IP created for "int". Then when you get to the networkinterface types for both VM self IPs, both VMs try to assign the int public IP. Problem, only one public INT IP was created. Therefore, this fails...

https://github.com/F5Networks/f5-azure-arm-templates/blob/3f72c3428a90fbcf5e9170074a8dfe27716a2ac0/experimental/bigiq/licenseManagement/cluster/2nic/new-stack/byol/azuredeploy.json#L620

                    {
                        "name": "[concat(variables('resourceGroupName'), '-int-ipconfig', '1')]",
                        "properties": {
                            "PublicIpAddress": {
                                "Id": "[concat(variables('intPublicIPAddressIdPrefix'), '1')]"
                            },
                            "primary": false,
                            "privateIPAddress": "[variables('intSubnetPrivateAddress3')]",
                            "privateIPAllocationMethod": "Static",
                            "subnet": {
                                "id": "[variables('intSubnetId')]"
                            }
                        }
                    }

**Comment by shyawnkarim** [comment]
Internal issue ESECLDTPLT-1930 created for this bug.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 8.1.1.0](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v8.1.1.0).
