### ISSUE TITLE
Request for DHCP option on management IP in the ARM templates

### ISSUE THREAD

**Issue by jokoyuliantoro** [F5Networks/f5-azure-arm-templates#165]
## Do you already have an issue opened with F5 support?
No

## Description
I need to configure DHCP option of the BIG-IP management interface for the template.
Please help on adjusting the template to allow DHCP/dynamic IP assignment for the BIG-IP management interface.

## Template
N/A. All templates are using static IP address.

## Severity Level
N/A

**Comment by shyawnkarim** [comment]
Thank you for taking the time to raise this issue. I've created internal issue ESECLDTPLT-1936 for this enhancement request.
