### ISSUE TITLE
Template Index has quick buttons to 7.0.0.2 templates - needs updating to latest

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#166]
## Do you already have an issue opened with F5 support?
No

## Description
The quick launch buttons on the template index page point to older template versions 7.0.0.2 in the hyperlink. Please update to correct links.

https://github.com/F5Networks/f5-azure-arm-templates/blob/master/template-index.md 

For example...
- **Deploying the BIG-IP VE in Azure - N NICs**
    - [New Networking Stack](https://github.com/F5Networks/f5-azure-arm-templates/tree/v7.0.0.2/supported/standalone/n-nic/new-stack)
      - *BYOL* <br><a href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FF5Networks%2Ff5-azure-arm-templates%2Fv7.0.0.2%2Fsupported%2Fstandalone%2Fn-nic%2Fnew-stack%2Fbyol%2Fazuredeploy.json">  <img src="http://azuredeploy.net/deploybutton.png"/></a><br>
      - *PAYG* <br><a href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FF5Networks%2Ff5-azure-arm-templates%2Fv7.0.0.2%2Fsupported%2Fstandalone%2Fn-nic%2Fnew-stack%2Fpayg%2Fazuredeploy.json">  <img src="http://azuredeploy.net/deploybutton.png"/></a>
      - *Using BIG-IQ for Licensing* <br><a href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FF5Networks%2Ff5-azure-arm-templates%2Fv7.0.0.2%2Fsupported%2Fstandalone%2Fn-nic%2Fnew-stack%2Fbigiq%2Fazuredeploy.json">  <img src="http://azuredeploy.net/deploybutton.png"/></a>

## Template
n/a

## Severity Level
3

**Comment by shyawnkarim** [comment]
Thanks for reporting this. Internal issue ESECLDTPLT-1942 created for this.

**Comment by shyawnkarim** [comment]
Closing.

These were last updated with [Release 9.3.0](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v9.3.0.0).
