### ISSUE TITLE
Cant deploy because AV-zone is not supported in region Canada Central

### ISSUE THREAD

**Issue by vadaszgergo** [F5Networks/f5-azure-arm-templates#167]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Describe the problem you're having or the enhancement you'd like to request.
Template is failing with following error when deploying to Canada Central:
failed validation with message: 'The zone(s) '1' for resource 'Microsoft.Compute/virtualMachines/pb47drelb01' is not supported. The supported zones for location 'canadacentral' are '''.'. (Code: InvalidTemplateDeployment)
It looks like template doesnt use the AV-set even if AV-Zone is not supported in the specific region.

## Template
For bugs, enter the template with which you are experiencing issues below.
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/3nic/existing-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 1

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Thank you for submitting this feedback. I was able to duplicate this behavior and have filed a bug for it to get it fixed. Internal ID ESECLDTPLT-1947.

**Comment by JeffGiroux** [comment]
You can workaround the template validation by modifying the json template a bit.

Current snippet (does NOT work…fails Azure template validation)…
        "zoneMappings": "[replace(toLower(string(providers('Microsoft.Compute', 'virtualMachines').zoneMappings)), ' ', '')]",
        "southcentralus": "[equals(variables('location'), string('southcentralus'))]",
        "southafricanorth": "[equals(variables('location'), string('southafricanorth'))]",
        "australiaeast": "[equals(variables('location'), string('australiaeast'))]",
        "zonesAvailable": "[and(contains(variables('zoneMappings'), concat('\"', variables('location'), '\"')), not(variables('southcentralus')), not(variables('southafricanorth')), not(variables('australiaeast')))]",
 
 
Workaround (works, passes validation)…
**notice the addition of canadcentral. Add a new variable line for canadacentral, and then add canadacentral as a check in the "zonesAvailable" line.

        "zoneMappings": "[replace(toLower(string(providers('Microsoft.Compute', 'virtualMachines').zoneMappings)), ' ', '')]",
        "southcentralus": "[equals(variables('location'), string('southcentralus'))]",
        "southafricanorth": "[equals(variables('location'), string('southafricanorth'))]",
        "australiaeast": "[equals(variables('location'), string('australiaeast'))]",
        "canadacentral": "[equals(variables('location'), string('canadacentral'))]",
        "zonesAvailable": "[and(contains(variables('zoneMappings'), concat('\"', variables('location'), '\"')), not(variables('southcentralus')), not(variables('southafricanorth')), not(variables('australiaeast')), not(variables('canadacentral')))]",

**Comment by vadaszgergo** [comment]
Thanks @JeffGiroux 
Is it possible for F5 to modify the template on the github, so other won't run into this same issue?

**Comment by shyawnkarim** [comment]
@vadaszgergo, yes it is. The bug ticket, mentioned above, is in our backlog to fix this.

**Comment by mikeshimkus** [comment]
FYI, created additional internal issue ESECLDTPLT-2491 to implement the pickZones() intrinsic function in our templates.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
