### ISSUE TITLE
5Gbps PAYG licenses are not in the list of available license options

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-azure-arm-templates#168]
## Description
5Gbps options (Good, Better, Best) do not appear in the list of available PAYG licenses. They do not seem to be in the code of the template either. Note that these 5Gbps licenses are available from Azure Marketplace (3Gbps PAYG for some reason is not available even from Marketplace).

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/2nic/existing-stack/payg
(and probably PAYG templates)

## Severity Level
2

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with this issue. I've created internal ID ESECLDTPLT-1962 to get this added into the list.

**Comment by vvt137** [comment]
The route cause of the issue may be related to be be unavailability of 5G PAYG images within Azure MarlketPlace for v14.1.x BIG-IP software. These images are only available for v15.0 and "latest" (v15.1.2) software, e.g. f5-networks:f5-big-ip-good:f5-bigip-virtual-edition-5g-good-hourly:15.1.002000.

There is actually another related issue with the templates - the 10G PAYG images are accessible via the templates, but they are not available within Azure MarlketPlace for v14.1.x BIG-IP software either. For example, one can try to install PAYG f5-bigip-virtual-edition-10g-good whilst also selecting 14.1.200000 software from a template, but the deployment is bound to fail as f5-networks:f5-big-ip-good:f5-bigip-virtual-edition-10g-good-hourly:14.1.200000 is not available as an Azure MarketPlace image.

**Comment by shyawnkarim** [comment]
The reason that these throughput speeds are not available for versions less that 15 is because these speeds require Azure Accelerated Networking and only v15 supports that.

**Comment by shyawnkarim** [comment]
Closing. Work on adding 5Gbps to the templates has concluded and will be included in our next template release on June 4th, 2020.
