### ISSUE TITLE
managedRoutes NOT_SPECIFIED and route table creates route for external subnet

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#169]
## Do you already have an issue opened with F5 support?
No

## Description
I did not supply a value for managedRoutes and instead left it with default of "NOT_SPECIFIED". It resulted in using the route table named defaultRouteTable with one route containing the external network subnet. So...10.0.2.0/24 next hop 10.0.2.4 (self IP on BIG-IP). Then it is associated with the external subnet. I don't see any documentation that states "if you leave NOT_SPECIFIED" then a default route containing external subnet will be created.

Preferred, created a route with address prefix 0.0.0.0/0 if left as NOT_SPECIFIED. Use next hop self IP 10.0.2.4. But...do NOT associated it with a subnet. Instead, make a note in the docs that a UDR is created but that customer will need to associated it with the correct subnet in their Azure network.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/new-stack/payg

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 3

**Comment by shyawnkarim** [comment]
Thank you for providing this feedback. We are now tracking this enhancement internally with ID ESECLDTPLT-2044.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
