### ISSUE TITLE
Readme correction

### ISSUE THREAD

**Issue by selhorn** [F5Networks/f5-azure-arm-templates#17]
The readme says: The BIG-IP Virtual Edition and Microsoft Azure: Setup guide (https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-ve-setup-msft-azure-12-1-0.html) describes how to create the configuration manually without using the ARM template.

This is not correct. The setup guide shows how to create a single NIC and multi-NIC setup only.

**Comment by jsevedge** [comment]
Thanks @selhorn , we will resolve this in the next release.

**Comment by jsevedge** [comment]
This was resolved in release v3.2.1.0.
