### ISSUE TITLE
failover logs no longer exist

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-azure-arm-templates#173]
## Description

Since the templates have moved to Cloud Failover Extension it appears that the failover.log is no longer created. There is, however (and traditionally) an object created in the storage account created by the template, the `f5cloudfailoverstate` has some information, but its overwritten twice in each event, once to say the event is starting and once to say its final state.

Is this the correct situation? should we be removing this statement from the readme?

> F5 ARM templates now capture all deployment logs to the BIG-IP VE in /var/log/cloud/azure. Depending on which template you are using, this includes deployment logs (stdout/stderr), f5-cloud-libs execution logs, recurring solution logs (failover, metrics, and so on), and more.

Are there other files we should be looking at for logging? Is there a status option we can "GET" from CFE?

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/new-stack/payg

Severity: 5

**Comment by JeffGiroux** [comment]
Download the Postman collection. 
https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/postman-collection.html

There is a GET /trigger endpoint. It gives the state of the job. This same state gets copied to the storage account JSON that you mention. The GET /trigger will supply all objects that will move from one device to another as well as RUNNING or SUCCESSFUL status.

**Comment by jmcalalang** [comment]
I had downloaded that too, but that **trigger** endpoint is horribly undocumented too.

So that is the same data that is in the storage account, we should then be updating the readme that the **failover.log** no longer exists as it did historically, and you are going to need to look in either of the two locations.

I would recommend starting with the storage account since the alternative requires the end-user to "know" CFE exists, and were abstracting this magic.

![postman](https://user-images.githubusercontent.com/20847865/78679326-ee83c380-789e-11ea-8e21-c04571870842.png)

![storageaccount](https://user-images.githubusercontent.com/20847865/78679553-3a366d00-789f-11ea-80ea-b9a102bc6214.png)

**Comment by jmcalalang** [comment]
It's also worth writing down someplace if the storage account doesn't exist the failover won't work. Its a crucial object (not called out anywhere too).

**Comment by shyawnkarim** [comment]
An enhancement to our README documentation, that notes that failover.log is no longer being used, is now being tracked with internal ID AUTOSDK-334.

In regards to the storage account objects not being called out anywhere, we do have instructions for each cloud's storage requirements on these pages: [AWS](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/aws.html#tag-your-aws-network-infrastructure-objects), [Azure](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/azure.html#tag-your-azure-network-infrastructure-objects), and [GCP](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/gcp.html#label-your-google-cloud-network-infrastructure-objects).

**Comment by shyawnkarim** [comment]
Closing.

New documentation and help with troubleshooting can be found here:

https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/troubleshooting.html
