### ISSUE TITLE
Standard_D1_v2 and similar VM types cannot be selected in 1nic and 2nic templates

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-azure-arm-templates#174]
## Description
"Standard_D1_v2", "Standard_DS1_v2" and similar single-vCPU VM types cannot be selected from 1-nic and 2-nic templates. Please add them to code.

I realize that Azure limits on number of NICs dictates removing both 1-vCPU and 2-vCPU VMs from the list for all 3-nic and n-nic templates. However, I do not see any reasons for removing 1-vCPU VMs form 1nic and 2nic templates as these VMs support up to 2 NICs (see https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series). One of the 1-CPU VM type (DS1_v2) is also in the "publisher recommended" list of PAYG F5 products in Azure marketplace (up to and including 1Gbps license).

## Templates
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/1nic/existing-stack/byol
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/2nic/existing-stack/byol
and all other 1nic and 2nic templates

## Severity Level
4

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with this request. I've added this enhancement to our backlog, internal ID ESECLDTPLT-1985.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
