### ISSUE TITLE
AS3 declaration causes virtual address conflict on new deployment

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#175]
## Do you already have an issue opened with F5 support?
No

## Description
Deploying a new cluster into existing stack. Using AS3 for app creation. Using ARM template for BIG-IP deployment. Onboarding creates a virtual address in partition /Common. Reference seen here...

https://github.com/F5Networks/f5-azure-arm-templates/blob/2fac82ec2520a8644b0d9e820ab511e6b1237cc2/supported/failover/same-net/via-api/n-nic/existing-stack/payg/azuredeploy.json#L1252

"tmsh create ltm virtual-address $addr address $addr"

Post ARM deployment, a user will then deploy an app (aka VIP, listener) using AS3 with the secondary IP address created by the template assigned to the VM NIC. AS3 tries to deploy as a tenant (aka partition) and tries to create a virtual address (the same secondary IP) in a different partition. This results in an error.

Apr 13 14:50:27 myf5.centralus.cloudapp.azure.com err tmsh[29542]: 01420006:3: 01020066:3: The requested Virtual Address (/Common/10.0.2.10) already exists in partition Common

In this case, 10.0.2.0/24 is my external network. The 10.0.2.10 is the secondary IP and created by tmsh virtual address as well as the IP assigned to the VM NIC in Azure. When I use 10.0.2.10 in an AS3 declaration...error as the virtual address already exists in /Common.

Need ability to reference shared virtual address related to the following AS3 issue. Seems to be an existing AS3 github issue.

https://github.com/F5Networks/f5-appsvcs-extension/issues/219

As for this ticket on ARM...need docs updated on ARM template README to warn user of workaround. Otherwise, AS3 declaration will fail.

Workaround:
1. Launch template as-is
2. post deployment, manually delete virtual address found in common
3. deploy AS3 declaration

Other workaround...
Modify template and remove the command for "tmsh create ltm virtual-address $addr address $addr" prior to ARM deployment.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/payg

I think this affects all Azure templates where onboarding creates a virtual address.

## Severity Level
3

**Comment by shyawnkarim** [comment]
Thanks for reporting this. I've filed internal ID ESECLDTPLT-1997 to update our documentation with the workaround.
