### ISSUE TITLE
With 7.4 HA_API template, Documentation needs to reflect MSI usage instead of Service Principal stored credentials

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/f5-azure-arm-templates#176]
## Description
With 7.4 HA_API template, documentation needs to reflect MSI usage instead of Service Principal stored credentials.

7.4 HA API template leverages CFE which uses Managed Service Identity of the BIG-IP VM.
Service Principal credential stored locally are no more valid.

Github documentation needs to be updated accordingly.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/new-stack/byol#service-principal-authentication

## Severity Level

Severity: 5

**Comment by bacchussr** [comment]
If documentation is being updated, might as well use the appropriate Azure nomenclature:
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

See the note on the above link:
"Managed identities for Azure resources is the new name for the service formerly known as Managed Service Identity (MSI)."

**Comment by tewfikm** [comment]
Agreed

**Comment by shyawnkarim** [comment]
Thanks for reporting this error in our documentation. I've created bug ticket, internal ID ESECLDTPLT-2005, to get this fixed.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
