### ISSUE TITLE
2-nic failover templates are needed to avoid unnecessary Azure costs

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-azure-arm-templates#179]
## Do you already have an issue opened with F5 support?
No

## Description
2-nic failover templates are required as Azure currently limits number of NICs to 2 for VMs with less than 4 vCPU. 

The extra costs associated with these more expensive VMs are not justifiable from the F5 VM capacity perspective all licenses smaller than 3G (5G for PAYG) are limiting the number of TMM CPUs to 2. The impact of the issue will increase as new Dv3/Dsv3-series VMs will be replacing older VMs as in v3 VMs the 2-NIC limit is imposed on the 4-vCPU VMs as well (i.e. the smallest 3-NIC implementation will be forced to even more expensive 8-vCMPu VMs).

## Template
All "failover" templates, e.g.
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol

## Severity Level
4

**Comment by shyawnkarim** [comment]
We understand the frustration that this can cause but this is more complicated than just making changes to a template. Azure also has their own requirements for which instances are compatible with our own images.

This is a known issue and and we'll make updates to this when possible.

**Comment by vvt137** [comment]
Hello Shyawn, 

Would you please clarify where the compatibility image-VM matrix can be found? 
All I can find is recommendations listed here: https://clouddocs.f5.com/cloud/public/v1/matrix.html. Please note that this list contains 2-vCPU VMs such as DS2_v2 and DS11_v2 Azure VMs, which do not support more than 2 NICs. Furthermore, a 1-vCPU VM type DS1_v2 is in the "publisher recommended" list of PAYG F5 products in Azure marketplace (up to and including 1Gbps license).

Regards
Vadim

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
