### ISSUE TITLE
[WAF autoscale] VM scale set threshold values clarification

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-azure-arm-templates#18]
##### ISSUE TYPE

 - RFI

##### BIGIP VERSION
```
BIG-IP   13.0.0  2.10.1671 
```

##### TEMPLATE

https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/solutions/autoscale/waf

##### QUESTION

How are the scaleOutThroughput and scaleInThroughput values translated to the "Network Out" metric threshold values?

I am trying to trigger a scaleout.

##### TROUBLESHOOTING

By default, a 200Mbps licensed 1NIC BIG-IP is deployed. The template defaults for scaleOutThroughput/scaleInThroughput are 90% and 10% of the F5 PAYG image bandwidth (Mbps) size, respectively. So I would assume that at average of 180Mbps for whatever specified time period, a scale out action would be triggered. 

According to below link describing VMSS metrics, "Network Out" units are in bytes and represent total byte count sent on all nw interfaces of the VMs in the VMSS. 
https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-supported-metrics
Metric 		Metric Display Name 	Unit 	Aggregation Type 	Description
Network In 	Network In 				Bytes 	Total 				The number of bytes received on all network interfaces by the Virtual Machine(s) (Incoming Traffic)
Network Out Network Out 			Bytes 	Total 				The number of bytes out on all network interfaces by the Virtual Machine(s) (Outgoing Traffic)

Repro:
1. Deploy WAF autoscale template with default values for scaleOutThroughput/scaleInThroughput/scaleTimeWindow
2. After successful deployment, check the VM scale set values for the thresholds for Scale out/Scale in
3. Not sure what the threshold values mean?

```
"rules": [
                    {
                        "metricTrigger": {
                            "metricName": "Network Out",
                            "metricNamespace": "",
                            "metricResourceUri": "/subscriptions/<id>/resourceGroups/WAF4/providers/Microsoft.Compute/virtualMachineScaleSets/bip4-vmss",
                            "metricResourceLocation": "japaneast",
                            "timeGrain": "PT1M",
                            "statistic": "Average",
                            "timeWindow": "PT10M",
                            "timeAggregation": "Average",
                            "operator": "GreaterThan",
                            "threshold": 23592960         <-------!!!!!
                        },
                        "scaleAction": {
                            "direction": "Increase",
                            "type": "ChangeCount",
                            "value": "1",
                            "cooldown": "PT1M"
                        }
                    },
                    {
                        "metricTrigger": {
                            "metricName": "Network Out",
                            "metricNamespace": "",
                            "metricResourceUri": "/subscriptions/<id>/resourceGroups/WAF4/providers/Microsoft.Compute/virtualMachineScaleSets/bip4-vmss",
                            "metricResourceLocation": "japaneast",
                            "timeGrain": "PT1M",
                            "statistic": "Average",
                            "timeWindow": "PT10M",
                            "timeAggregation": "Average",
                            "operator": "LessThan",
                            "threshold": 2621440   <-------!!!!!
                        },
                        "scaleAction": {
                            "direction": "Decrease",
                            "type": "ChangeCount",
                            "value": "1",
                            "cooldown": "PT1M"
                        }
                    }
```

**Comment by edwoodjrjr** [comment]
Hi Terence, lines 413-421 of the azuredeploy.json template show the calculation.  scaleOutThroughput and scaleInThroughput are percentages that are mulitiplied by the number of bits allowed by the licensedBandwidth choice.  That number is divided by 100 and then divided by 8 to get scaleOutNetworkBytes and scaleInNetworkBytes.

**Comment by tkam8** [comment]
THanks, so it sounds like we are doing something like Mbps to MBps conversion (in the case of 200Mbps it will be around 25MBps). I am in the process of testing this out, please keep this open for a little while longer

**Comment by tkam8** [comment]
Got this to work, thanks again. 
For reference: 
Time aggregation: default Average. divides the Sum by the number of data points received over the interval.
Metric name: Network Out (1 minute time grain)
Time grain statistic: default Average. Metrics (average count) taken every 1 minute. 
Threshold: in Bytes
Duration: default 10min. Everytime autoscale runs, it will query the past 10 minutes.
