### ISSUE TITLE
Internal/private ALB should be created when Provision Public IP is set to NO

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-azure-arm-templates#180]
## Do you already have an issue opened with F5 support?
No

## Description
When template parameter "Provision Public IP" is set to NO the "via-lb" template should create an Azure Load Balancer object and generate the "Fronted IP" ALB configuration objects (their number determined by the "Number of External IPs" parameter). This will be consistent with the way the template works when "Provision Public IP" is set to YES and will significantly reduce the additional configuration required after the template is deployed.

## Template
All "via-lb" templates, e.g.
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol

## Severity Level
5

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with this enhancement request. This issue is not being tracked internally with ID ESECLDTPLT-2042.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
