### ISSUE TITLE
Azure: Assignment in BIG-IQ license pool not revoked when auto scale instance on scalein and also device group not updated

### ISSUE THREAD

**Issue by ramganesh19** [F5Networks/f5-azure-arm-templates#182]
## Do you already have an issue opened with F5 support?
Yes. I have already opened a ticket with F5 - C3271922 

## Description
Following template was used to create 2 minimum and 4 max VM scaleset in azure
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/autoscale/waf/via-lb/1nic/existing-stack/bigiq
1. After scaleout and scalein, we dont see the license revoke in BIG-IQ and the device group not update in the master instance.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/autoscale/waf/via-lb/1nic/existing-stack/bigiq

## Severity Level
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.

**Comment by shyawnkarim** [comment]
This is a known issue and is actively being worked on during the current sprint.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 8.1.0.0](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v8.1.0.0).
