### ISSUE TITLE
HA-API templates fail after multiple replays with error RoleAssignmentUpdateNotPermitted

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/f5-azure-arm-templates#184]
## Description
When you deploy any flavor of HA-API templates that use Manage Identities (7.4.1.0 templates version), in some replay conditions, templates fails with RoleAssignmentUpdateNotPermitted error message.

To reproduce the problem :
- deploy HA-API template 
- Upon successful deployment and VMs running, delete resources from Resource Group
- Redploy same HA-API template with exactly same parameters or parameter JSON file
- Deployement fails with error RoleAssignmentUpdateNotPermitted

## Root cause 
investigations showed that deleting resources under Resource Group does not delete associated Role Assignement objects.
Hence, when redeploying, template generate same Role Assignement name and resources and generates error message as resource with same Name already exists.

•	The template is using the GUID ARM template function to generate the name of the role assignment, and to determine the value is using "dnslabel" and "instancename" in addition to either 0-role or 1-role depend on the number of the VM
•	Based on the documentation for the GUID ARM template function :
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-string#guid
"The returned value isn't a random string, but rather the result of a hash function on the parameters. The returned value is 36 characters long. It isn't globally unique."

i.e if keep passing same variable names, you will always will get the same ID.

## Workaround

Fixed templates are proposed here : https://github.com/tewfikm/f5-azure-arm-templates-CFE-MSI-GUID

proposed fix is using newGuid() function to assign name to Role Assignement resources

Feel free to check and merge.

Customer is expecting supported templates.

Thanks.

## Template
For bugs, enter the template with which you are experiencing issues below.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <3>

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with this issue and for all of your due diligence. This issue is now being tracked internally with ID ESECLDTPLT-2041.

**Comment by shyawnkarim** [comment]
Closing.

The fix to this issue was included with [Release 9.5.0.0](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v9.5.0.0).
