### ISSUE TITLE
GUI stop working when Changing Management IP from DHCP to Static 

### ISSUE THREAD

**Issue by jequihua1337** [F5Networks/f5-azure-arm-templates#185]
## Description
after deploy the template and change the mgmt ip address from dhcp to static on GUI it stop working.

## Template
For bugs, enter the template with which you are experiencing issues below.
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 1

**Comment by shyawnkarim** [comment]
This has been tested by our engineering team and everything works fine when switching from DHCP to static.

Can you open up a support ticket with F5 Support?

**Comment by shyawnkarim** [comment]
Closing. Please reopen if you still need assistance.
