### ISSUE TITLE
Documentation: managedRoutes README description of tags is incorrect

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#186]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
The description for managedRoutes and requirements for tag name:values does not match what is shown on F5 CloudDocs.

https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/new-stack/payg#template-parameters

It states...
To have the UDRs managed by BIG-IP, you will need to create an Azure tag with key ***f5_ha*** and value ***self_2nic***, or the name of a different self IP address configured on the BIG-IP VE. All UDRs with destinations matching managedRoutes and configured in Azure Route Tables tagged with 'f5_ha:' will use the corresponding self IP address on the active BIG-IP VE as the next hop for those routes. You must also associate the route table with a traffic group by creating an Azure tag with key ***f5_tg*** and value ***traffic-group-1***, or the name of a different traffic group configured on the BIG-IP VE

Suggestiong that updates are made to reference clouddocs or enter the correct description in the github readme.
https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/azure.html#tag-your-azure-network-infrastructure-objects

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/new-stack/payg

## Severity Level
3

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with Release 8.0.0.0.

**Comment by shyawnkarim** [comment]
Thank you!

Shyawn Karim  |  Product Management Engineer - Public Cloud & Cloud Solutions
M (425) 343-3719
[cid:image002.jpg@01D51F96.9C437640]

On Jun 4, 2020, at 2:36 PM, Jeff <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL MAIL: noreply@github.com<mailto:noreply@github.com>


Do you already have an issue opened with F5 support?

Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please open an case<https://support.f5.com/csp/article/K2633> with F5 if this is a critical issue.

Description

The description for managedRoutes and requirements for tag name:values does not match what is shown on F5 CloudDocs.

https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/new-stack/payg#template-parameters

It states...
To have the UDRs managed by BIG-IP, you will need to create an Azure tag with key f5_ha and value self_2nic, or the name of a different self IP address configured on the BIG-IP VE. All UDRs with destinations matching managedRoutes and configured in Azure Route Tables tagged with 'f5_ha:' will use the corresponding self IP address on the active BIG-IP VE as the next hop for those routes. You must also associate the route table with a traffic group by creating an Azure tag with key f5_tg and value traffic-group-1, or the name of a different traffic group configured on the BIG-IP VE

Suggestiong that updates are made to reference clouddocs or enter the correct description in the github readme.
https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/azure.html#tag-your-azure-network-infrastructure-objects

Template

https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/new-stack/payg

Severity Level

3

**Comment by shyawnkarim** [comment]
This documentation fix didn't make it into Release 8.0.0.0. I've created a doc ticket for this and added it to our backlog. We are tracking this internally with ID ESECLDTPLT-2059.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
