### ISSUE TITLE
Documentation: update Supported instance types and hypervisors section 

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#187]
## Do you already have an issue opened with F5 support?
No

## Description
The README has a section for Supported instance types and hypervisors and it needs to be updated a little bit.

1. Start here...
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/2nic/existing-stack/payg#supported-big-ip-versions
2. It then says this...
"For a list of supported Azure instance types for this solution, see the Azure instances for BIG-IP VE"
3. And gives you this link...
http://clouddocs.f5.com/cloud/public/v1/azure/Azure_singleNIC.html#azure-instances-for-big-ip-ve

The link above takes you to F5 clouddocs for Microsoft Azure: Single NIC BIG-IP VE. Please update the docs or remove this line as it is not the intended link based on the description "for a list of supported Azure instance types".

The correct statement and link appears in the next sentence of that section.

1. The next link talks about supported hypervisors...
"For a list of versions of the BIG-IP Virtual Edition (VE) and F5 licenses that are supported on specific hypervisors and Microsoft Azure, see supported-hypervisor-matrix"
2. And gives you this link...
https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/ve-supported-hypervisor-matrix.html

## Template
All template READMEs should be validated

## Severity Level
5

**Comment by shyawnkarim** [comment]
Thank you for reporting this issue with our documentation. We are now tracking this internally with ESECLDTPLT-2101

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
