### ISSUE TITLE
v6.0.4 template fails to install 12.1.x

### ISSUE THREAD

**Issue by ghost** [F5Networks/f5-azure-arm-templates#188]
## Do you already have an issue opened with F5 support?
Yes - C3280741

## Description
The recommendation for installing 12.x is to use the v6.0.4 template. Unfortunately the template references v12.1.3.03000 which is no longer available in the market place. Updating this to v12.1.3.03001 would ensure that deployment is successful.

## Severity Level

Severity: 4

**Comment by shyawnkarim** [comment]
Thank you for reporting this issue. We are now tracking this internally with ESECLDTPLT-2102.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
