### ISSUE TITLE
WAF autoscale - policy sync

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-azure-arm-templates#19]
##### ISSUE TYPE

 - Bug

##### BIGIP VERSION
```
BIG-IP   13.0.0  2.10.1671 
```

##### TEMPLATE

https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/solutions/autoscale/waf

##### QUESTION

After deploying the template, BIG-IP0 policy is enforced and blocking but BIG-IP1 is in staging. 
Is this due to an incomplete deployment on BIG-IP1 or is there an expectation for policy syncing to occur?

##### TROUBLESHOOTING

Logged into BIG-IP GUI and checked Security > Options > Application Security > Synchronization > Application Security Synchronization > Device Group is set to "None"

ASM policy is configured by iApp, so not sure of all the consequences of enabling policy sync.

info about the policy sync:
https://support.f5.com/kb/en-us/products/big-ip_asm/manuals/product/asm-implementations-13-0-0/36.html

##### Notes

Historically I believe two separate device groups were created for LTM and ASM policy config sync, but internal checks show that a single device group is sufficient if autosync is enabled on the existing one. (case 1-1422001571)

##### Logs

[waagent-logs.zip](https://github.com/F5Networks/f5-azure-arm-templates/files/1121840/waagent-logs.zip)

[scriptd-log.zip](https://github.com/F5Networks/f5-azure-arm-templates/files/1121881/scriptd-log.zip)

**Comment by edwoodjrjr** [comment]
The ASM sync group should be set to "Sync" (it is in our marketplace WAF deployment, but not autoscale).  We'll get that corrected.

**Comment by edwoodjrjr** [comment]
This has been corrected in the latest release.
