### ISSUE TITLE
No option for using StandardSSD_LRS type storage

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-azure-arm-templates#190]
##  Description
F5 ARM templates provide options to select either Standard (HDD) or Premium storage types, whilst StandardSSD_LRS storage type is not supported. It appears, the underlying problem may be that F5 templates use a very old versions of some Microsoft.Compute APIs (e.g. **"storageApiVersion": "2017-10-01"**), whilst specifying "StandardSSD_LRS" requires 2018-04-01 or later (see **https://docs.microsoft.com/en-us/azure/virtual-machines/windows/using-managed-disks-template-deployments).**

## Template
all ARM templates, e.g.
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/1nic/existing-stack/byol

## Severity Level
4

**Comment by shyawnkarim** [comment]
Thank you for reporting this issue. We are not tracking this enhancement internally with ID ESECLDTPLT-2103.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
