### ISSUE TITLE
Failover via LB templates Azure Loop permanently between 2 mgnt instances

### ISSUE THREAD

**Issue by ljeromets** [F5Networks/f5-azure-arm-templates#192]
## Description
Fresh installation from azure template from this link => https://github.com/F5Networks/f5-azure-arm-templates/tree/master/experimental/failover/same-net/via-lb/3nic/new-stack/byol
Deployement Ok but log in to the managment interface is not possible because de Azure LB perma redirect us between the 2 nodes.

My workarround is to remove one of the node from the backendmgnt pool. Please see the screeshot ( There is only a single nodes )
![image](https://user-images.githubusercontent.com/49157896/84799586-c29e6000-affc-11ea-8cb7-e489ade252ad.png)

Is it normal? how to correct it?

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/experimental/failover/same-net/via-lb/3nic/new-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

**Comment by JeffGiroux** [comment]
That rule is mainly setup in case you have a single-nic BIG-Ip deployment. At that point, mgmt happens through the ALB. Since you are using a 3-nic deployment, the mgmt IP does not need to be access via load balancer. Try accessing direct.

**Comment by ljeromets** [comment]
hello @JeffGiroux thank you for your reply.
For my informaiton, the direct access to the mgmt interface seems to be strictly over a private ip address, isn't it?
As shown on the screen , the redacted public ip address is the LB public ip address causing our precedente issue
![image](https://user-images.githubusercontent.com/49157896/84806246-aa7f0e80-b005-11ea-8cf4-d618e8879045.png)

**Comment by JeffGiroux** [comment]
Hmm, I thought the multi-nic templates created NAT rules on the ALB, but I looked in template JSON code and don’t see load balancer NAT rules in the 3-nic. 

Based on your pic, I’m assuming you chose “no” for public IP? Either way, you can look at adding a NAT rule on the ALB to each BIG-IP. You need port 22 and 443? That will be 4 NAT rules: two to each device. 

Look at single-nic as example. 
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/failover/same-net/via-lb/1nic/existing-stack/payg/azuredeploy.json#L712

Example...
1. Hit ALB on port 8022, map to BIG-IP 1 on port 22
2. Hit ALB on port 8023, map to BIG-IP 2 on port 22
3. Hit ALB on port 50100, map to BIG-IP 1 on port 443
4. Hit ALB on port 50101, map to BIG-IP 2 on port 443

**Comment by ljeromets** [comment]
hello,
I can't find any LB inbound nate rules for the template https://github.com/F5Networks/f5-azure-arm-templates/blob/master/experimental/failover/same-net/via-lb/3nic/new-stack/byol/azuredeploy.json#L1079 .
I have created the nat rule for the ssh, but I can't the port 443 because it conflicts with the existing lb rules https://github.com/F5Networks/f5-azure-arm-templates/blob/master/experimental/failover/same-net/via-lb/3nic/new-stack/byol/azuredeploy.json#L982

Finally I will use a vm as bounce to access to the F5 privates networks.

**Comment by JeffGiroux** [comment]
I would remove the load balancing rule to 443 mgmt. Seems silly to be in the template. Delete the 443 lb rule with mgmt backend. Then you can create a NAT rule for https. 

And yes, ideally you use a secure jumphost for mgmt direct access to F5 boxes.

I would suggest to template team that the lb rules get cleaned up and fixed for mgmt access. And update GitHub README with relevant notes about mgmt access.

**Comment by ljeromets** [comment]
@JeffGiroux  thank you I just did it and it's works.
