### ISSUE TITLE
documentation - align/clarify Traffic group support for templates including CFE

### ISSUE THREAD

**Issue by Klipope** [F5Networks/f5-azure-arm-templates#193]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
In github description page for template https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol version 8.0.0.0 it is said: 
"This solution uses an ARM template to launch two BIG-IP VEs in an Active/Standby configuration with network failover enabled (the template now supports multiple traffic groups which enables active/active deployments). "
however this is a template which deploys CFE and when reading CFE documentation on clouddocs.F5.com it is then said.. 
"Cloud Failover may not be a good fit where:
•	You are using more than one traffic group. For example, devices are in Active/Active or Active/Active/Standby configuration."
it is my understanding that CFE does not support active/active deployments at the moment and that if we want Traffic-groups to be enabled we would need to revert to the old failover scripts. is this correct? 
the documentation is confusing from my perspective.  

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol

**Comment by shyawnkarim** [comment]
Thank you for reporting this issue with our documentation. Active/active configuration is not supported by CFE.

I went through the READMEs of other failover templates and found other mentions of active/active being supported as well. I've created a ticket to update our documentation and we are tracking it with internal ID ESECLDTPLT-2348.

**Comment by shyawnkarim** [comment]
Closing. 

This should have been closed in early 2021 when the doc changes were pushed out.
