### ISSUE TITLE
v8.0 template deploying HA via-api makes active BIG-IP non-accessable after stopping the instance.

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/f5-azure-arm-templates#194]
Deploying BIG-IP HA via-api with v8.0 ARM template works right out of the gate with using the user managed identity and did some extensive testing with and without the use of a PIP. But, before the weekend stopped my VMs and just turned them back on makes that the active BIG-IPs for both (yes both) the external ADC layer (mimicking an often used upfront FW-layer) and the DMZ ADC are not accessible via GUI or SSH. Also the secondary ext privIP (both BIG-IPs) is gone and the extPIP (ext BIG-IP) is there but not associated...

This behavior first was noted by a customer and SE and is consistently reproducible after stopping the instances and restarting it.

restarting restnoded or restjavad does not result in the BIG-IP becoming available again.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by gwolfis** [comment]
PreciseTimeStamp | correlationId | Request Source | Request Action
-- | -- | -- | --
6/26/2020 13:32 | 02561783-ec2b-4463-9cca-b33d9eeed080 | 20.50.243.169 | Remove IP from gert-adc-ext0
6/26/2020 13:36 | 408ad14e-5356-491b-8c57-febf0f8126b6 | 20.50.243.169 | Move IP to gert-adc-ext1
6/30/2020 07:12 | f11d1be4-2855-4599-a6c6-ed9df187a16a | 20.50.243.140 | Remove IP from gert-adc-ext1

**Comment by gwolfis** [comment]
Send additional gathered logging from MSFT to PM

**Comment by shyawnkarim** [comment]
I deployed v9.0 of this BYOL template and didn't experience any of these issues after stopping and starting both VMs. Are you still experiencing issues?

**Comment by gwolfis** [comment]
Hi Shyawn,

When stopping the VM did you waited a day before re-enabling it again?

Kind regards,

Gert Wolfis
EMEA Cloud Solutions Architect
M: +31657022078

**Comment by shyawnkarim** [comment]
I only waited a few minutes. I have them stopped now and I'll start them up tomorrow and check again.

**Comment by gwolfis** [comment]
Yep, that was the way to reproduce. Let me do the same tomorrow and close them to wait over the weekend and let you know.

Kind regards,

Gert Wolfis
EMEA Cloud Solutions Architect
M: +31657022078

**Comment by gwolfis** [comment]
I have tested v9.1 templates and stopped the VMs before the weekend and enabled them on Monday. No sign of lost IP host configs either on the management side as at the external side. So to me this issue is solved.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 8.1.0.0](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v8.1.0.0).
