### ISSUE TITLE
Post deployment cs.dat change only required for 13.1.x

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-azure-arm-templates#196]
## Do you already have an issue opened with F5 support?

No

## Description

In the doc post-deployment talks about modifying cs.dat this only appears to be necessary on a base 13.1.x system. 14.1 and 15.1 do not appear to require any changes.

https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol#post-deployment-configuration-steps

## Template
.
N/A

## Severity Level
Severity: 5

**Comment by shyawnkarim** [comment]
Nice catch. I've filed a documentation bug for this, internal ID ESECLDTPLT-2238.

**Comment by rmcolbert** [comment]
Removing this section of the post-deployment-config-steps caused an outage for my company because they were upgrading from v13 to v15. There should have been a caveat in the doc saying this was only needed for v13.

**Comment by shyawnkarim** [comment]
Closing. Our documentation was updated with [Release 9.8.0.0](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v9.8.0.0).
