### ISSUE TITLE
Failover Network local address is not configured after deployment

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-azure-arm-templates#198]
## Do you already have an issue opened with F5 support?
No, I am an F5 SA and noticed this when helping a customer.

## Description
After deployment of [this template](https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol/azuredeploy.json) my devices are clustered but both are Active. Failover Network local address is not configured on either device, but ConfigSync local address is fine.

After simply configuring the Failover Network on both devices, they immediately go Active/Standby, as expected.

When I check the file /var/log/cloud/azure/install.log I see the following errors at the end of the log file on the last line:
On Device1: `Syntax Error: Invalid IP address: "DYNAMIC"`
On Device2: ` Self-device unicast source address cannot reference the non-existent Self IP (0.0.0.1); Create it in the /Common folder first.`

I have tested this twice with identical results, once in USEast2, and once in CanadaCentral.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol/azuredeploy.json

## Severity Level
5

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. I've created a bug for this, internal ID ESECLDTPLT-2239, to get this fixed.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
