### ISSUE TITLE
Documentation: references to traffic-group-2 in via-api failover README.md files

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-azure-arm-templates#199]
## Do you already have an issue opened with F5 support?
No

## Description
References to "traffic-group-2" and "active/active deployments" should be removed from the via-api failover templates as F5 CFE used by these templates is "not multiple-traffic-group-aware" (see https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/faq.html#faq-active-active).

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/payg
and other via-api failover templates

## Severity Level
5

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue with our documentation. We are now tracking this internally with ID ESECLDTPLT-2447.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
