### ISSUE TITLE
dnsLabel parameter value of REQUIRED should require change

### ISSUE THREAD

**Issue by depperson** [F5Networks/f5-azure-arm-templates#20]
I tried deploying the PAYG template but forgot to change the REQUIRED value on the dnsLabel parameter.  The template failed deployment with an error "DNS record required.westus.cloudapp.azure.com is already used by another public IP."

The template or Azure is not correctly requiring me to change the value.

**Comment by edwoodjrjr** [comment]
Hi depperson, unfortunately it is a limitation of ARM templates that they provide no pre-deployment input validation.

**Comment by grf5** [comment]
That's interesting. I was deploying the 2NIC standalone template in Azure this week and validation failed immediately because we didn't update that field.

Greg Robinson | Systems Engineer – Service Provider

M +1-407-304-9634

f5.com





On Thu, Aug 3, 2017 at 10:27 AM -0500, "Mike Shimkus" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi depperson, unfortunately it is a limitation of ARM templates that they provide no pre-deployment input validation.

**Comment by edwoodjrjr** [comment]
The creation of the public IP address will fail immediately, but that is different from having input validation.

If you look at the F5 VM offers in Azure marketplace, they have input validation that will prevent the deployment from starting at all.

**Comment by jsevedge** [comment]
Hey @grf5, Azure is always updating and as such maybe when deploying an ARM template via the GUI it is doing some pre-checking now.  Via CLI or methods it wouldn't be able to do that until you actually start deployment at least, so basically by defaulting param to "REQUIRED" we are trying to alert template users to make a change to the parameter in lieu of us being able to control the runtime verification.

**Comment by grf5** [comment]
That indeed seems to be the case. Thanks for the information!






On Fri, Aug 4, 2017 at 11:40 AM -0500, "James Sevedge" <notifications@github.com<mailto:notifications@github.com>> wrote:


MESSAGE RECEIVED FROM EXTERNAL SENDER: noreply@github.com


Hey @grf5<https://github.com/grf5>, Azure is always updating and as such maybe when deploying an ARM template via the GUI it is doing some pre-checking now. Via CLI or methods it wouldn't be able to do that until you actually start deployment at least, so basically by defaulting param to "REQUIRED" we are trying to alert template users to make a change to the parameter in lieu of us being able to control the runtime verification.

**Comment by jsevedge** [comment]
For now we will leave dns label as required, please reopen if additional use cases arise.

**Comment by jmcalalang** [comment]
> For now we will leave dns label as required, please reopen if additional use cases arise.

Azure validation doesn't see this parameter as required, we need to have it flag red on the parameter if its missing. I can open a new issue on this if needed, but this seemed like a good spot.

<img width="702" alt="dns label" src="https://user-images.githubusercontent.com/20847865/50603752-6bd8b100-0e70-11e9-9c0e-e29d305b14cb.png">
