### ISSUE TITLE
deploy button shouldn't link to master branch azuredeploy.json

### ISSUE THREAD

**Issue by depperson** [F5Networks/f5-azure-arm-templates#200]
## Do you already have an issue opened with F5 support?
No.

## Description
The deploy links point Microsoft Azure to use the master branch of the template, which isn't always desired. 

Deploy links are broken for older templates and should not point to the master branch.   The 1nic new-stack template was moved from supported to experimental.  This breaks the deploy button for older versions of the template, because they point to the master branch which no longer has the desired azuredeploy.json file.  The links should instead point to the tagged version of the template file instead.  See below. 

older tagged template:
https://github.com/F5Networks/f5-azure-arm-templates/tree/v7.5.0.0/supported/standalone/1nic/new-stack/byol

deploy button points to master:
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FF5Networks%2Ff5-azure-arm-templates%2Fmaster%2Fsupported%2Fstandalone%2F1nic%2Fnew-stack%2Fbyol%2Fazuredeploy.json

it should point to the same tagged version:
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FF5Networks%2Ff5-azure-arm-templates%2Fv7.5.0.0%2Fsupported%2Fstandalone%2F1nic%2Fnew-stack%2Fbyol%2Fazuredeploy.json

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/v7.5.0.0/supported/standalone/1nic/new-stack/byol

## Severity Level
Severity: 5 (trivial)

**Comment by shyawnkarim** [comment]
I've filed a bug for this, internal ID ESECLDTPLT-2237, to get this fixed.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
