### ISSUE TITLE
via-lb 3-nic template improvements

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/f5-azure-arm-templates#201]
## Do you already have an issue opened with F5 support?
The mentioned items in this issue are improvements.

## Description
Using a v8.x ARM template new-stack for BIG-IP A/A 3-NIC. The deployment is not always successful, but this is mentioned in issue: https://github.com/F5Networks/f5-azure-arm-templates/issues/198.

Deploying a new-stack template should be designed as such that when sticking with the defaults and fill in things like resource group, username, password, DNS name and a license (when needed) it should work.

What is lacking:
- The description on Github does not mention clearly what gets deployed. It should say that an ext-lb, 2x BIG-IP and an int-lb gets deployed.
- Once deployed, there is a ext-lb rule of 443 pointing to the bigip-mgmt backend, which is wrong, if you want to create this from the template, it should point to the bigip-ext backend.
- Both bigip-mgmt should get provided with NAT rules to get mgmt access for SSH and HTTPS sorted, this should get deployed from the template and use the one pubIP allocated for VS from the template options (even when more pubIPs are allocated)
- the external NSG should have these NAT ports included.
- If we decide not to pre-configure this through the template, than make this clear as a post-task in the documentation.

## Template
Deploying https://github.com/F5Networks/f5-azure-arm-templates/tree/v8.0.0.0/experimental/failover/same-net/via-lb/3nic/new-stack/bigiq, but this counts for the v8.1 templates as well, though these are all of a sudden 'experimental'.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>
5
Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Thanks for providing this feedback. We are now tracking these improvements internally with ID ESECLDTPLT-2345.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
