### ISSUE TITLE
Deployment Example JPEG link broken

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#204]
## Do you already have an issue opened with F5 support?
No

## Description
The new example folder top folder has a picture link but it is dead. You get an error.

"Cannot proxy the given URL"

Here's the link when I hover on it.
https://camo.githubusercontent.com/7aed3a5bc20864e0393c40c0216e61c7021b5878/68747470733a2f2f676974737761726d2e66356e65742e636f6d2f636c6f7564736f6c7574696f6e732f66352d636c6f75642d666163746f72792f2d2f7261772f646576656c6f70322e302f66352d617a7572652d61726d2d74656d706c617465732f6578616d706c65732f696d616765732f617a7572652d6175746f7363616c652d6578616d706c652d6469616772616d2e706e67

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/examples#deployment-example

## Severity Level
4

**Comment by shyawnkarim** [comment]
Thanks for reporting this broken link. I've filed a documentation bug, internal ID ESECLDTPLT-2230, to get this fixed.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).

Our V2 documentation has been completely redone.
