### ISSUE TITLE
Fix Hardcoded URL for Storage Blob Access

### ISSUE THREAD

**Issue by codygreen** [F5Networks/f5-azure-arm-templates#205]
## Description
The [AzureCloudProvider.prototype.getDataFromUri function](https://github.com/F5Networks/f5-cloud-libs-azure/blob/341a1882a64fdb8fd294fbe6a36816e6adecc3a2/lib/azureCloudProvider.js#L1047) is hardcoded to a URL that does not work for Azure China.  

The URL base needs to be abstracted so BIG-IPs deployed into Azure China or Azure Government Cloud Computing.

For China, the base url needs to be: ```*.chinacloudapi.cn```.  More information on Azure China endpoints can be found [here](https://docs.microsoft.com/en-us/azure/china/resources-developer-guide).

Per the readme in the f5-cloud-libs-azure repo, an issue is being opened in this repository. 

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

**Comment by codygreen** [comment]
@chen23 has a good suggestion of using the AzureEnvironments to detect what environment the script is running in.  He has example code [here](https://github.com/chen23/f5-cloud-libs-azure/blob/v2.11.0-cn/scripts/failoverProvider.js#L172).

**Comment by chen23** [comment]
here's a hardcoded example of how to use Azure China: https://github.com/F5Networks/f5-cloud-libs-azure/compare/v2.9.1...chen23:v2.9.1-custom it looks like you should be able to get this out "environment" variable: https://github.com/F5Networks/f5-cloud-libs-azure/blob/de52a113a10a0ca01525e410a1f8c72a0a7a449d/lib/azureCloudProvider.js#L161

**Comment by shyawnkarim** [comment]
Thanks for bringing this issue to our attention. I've filed a bug, internal ID ESECLDTPLT-2236, to get this fixed.
