### ISSUE TITLE
example 2.0 template mixed use of case for nsgID

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#206]
## Do you already have an issue opened with F5 support?
No

## Description
The new templates have application.json and bigip.json for the various templates. Inside, there are nsgID variables. Some have nsgId, some have nsgID. Please keep case consistent across templates, variables, and files.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/examples

## Severity Level
4

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. I've filed a bug, internal ID ESECLDTPLT-2229, to get this fixed.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
