### ISSUE TITLE
active/active template documentation

### ISSUE THREAD

**Issue by depperson** [F5Networks/f5-azure-arm-templates#21]
This template deploys an active/active HA pair behind ALB.  Please note that somewhere in the readme. 

https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/cluster/1nic/README.md

**Comment by jsevedge** [comment]
@depperson The configuration diagram in the readme does depict that traffic routes from an ALB into a clustered set of BIG-IP's.  There is no reference to active/active though so will update that in the readme for the next release.

Note:  Looks like Mike S. just responded as well via the slack channel.

**Comment by jsevedge** [comment]
@depperson  Additional documentation to make it clear if active/active or active/standby has been added in tagged release v3.3.0.0, please reopen if you feel something is still missing.
