### ISSUE TITLE
SMBus base address unitialized - upgrade BIOS or use force_addr-0xaddr

### ISSUE THREAD

**Issue by SalimHaddou** [F5Networks/f5-azure-arm-templates#210]
## Do you already have an issue opened with F5 support?
No

## Description
Intermittent VM start error. Boot diagnostics shows: SMBus base address unitialized - upgrade BIOS or use force_addr-0xaddr

## Template
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol/azuredeploy.json

# Misc
Instance Type: Standard DS4 v2 (8 vcpus, 28 GiB memory)
Location: France Central 2

Seems similar to this: https://social.technet.microsoft.com/Forums/Windows/en-US/73cbe8ec-2099-4998-aee0-5080c492f0ed/redhat-enterprise-linux-80-will-not-boot-in-hyperv?forum=linuxintegrationservices

**Comment by shyawnkarim** [comment]
This is a known error and is referenced on [AskF5.](https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/releasenotes/product/relnote-ve-11-4-1.html), ID 399046.

This error is caused when a VM does not have SMBus but Linux tries to load the module anyway. It doesn't affect anything and can be safely ignored.

**Comment by shyawnkarim** [comment]
Closing. Please feel to reopen if needed.
