### ISSUE TITLE
Deployment fails with error during f5vm01/start operation

### ISSUE THREAD

**Issue by steveh565** [F5Networks/f5-azure-arm-templates#212]
## Description
Deployment in azure region Canada Central consistently fails at the f5vm01/start operation with the following error:

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "VMExtensionProvisioningError",
                "message": "VM has reported a failure when processing extension 'start'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\n\n[stderr]\n/bin/sh: -c: line 90: syntax error near unexpected token `('\n/bin/sh: -c: line 90: `[concat('### START (INPUT) CUSTOM CONFIGURATION HERE'\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
            }
        ]
    }
}

Results in an F5 VM instance with no running configuration installed.

## Template
experimenal/standalone/3-nic/learning-stack

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

**Comment by shyawnkarim** [comment]
I was able to duplicate this error. We are now tracking this bug internally with ID ESECLDTPLT-2338.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
