### ISSUE TITLE
onboard.js fails for BIG-IP version 15.1.100000

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-azure-arm-templates#213]
## Do you already have an issue opened with F5 support?
No

## Description
Azure VM extension deployments with BIG-IP version 15.1.100000 finish abnormally with the following error message generated by `onboard.js`:

2020-11-03T01:06:52.305Z info:  Device initialization failed tryUntil: max tries reached: tryUntil: max tries reached: Authorization failed: user=https://localhost/mgmt/shared/authz/users/svc_user resource=/mgmt/shared/echo/available verb=GET uri:http://localhost:8100/mgmt/shared/echo/available referrer:10.8.7.7 sender:10.8.7.7

As a result BIG-IP software is implemented, but configuration remains incomplete (GUI shows the setup screen, the system name is "localhost" etc).

Here are the outcomes of tests I performed to analyse the scope of the issue:
- BIG-IP version 15.1.004000 does not seem to be affected
- The issue affects `Best25Mbps` as well as `Good25Mbps` images
- The issue is observed whether the Mgmt Ip Address is set to DYNAMIC or to a static address
- The issue is observed whether template is deployed via the "Deploy button" on F5 GitHub pages or via using Azure CLI command referring to template and template-parameter files.

Additional analysis of API authentication/authorisation (following the [Dealing with authorization failed errors](https://clouddocs.f5.com/training/community/gsts/html/class1/module4/lab07.html) and similar F5 articles) did not reveal any anomalies compared to successful deployments except showing 3 successful authentication events for the user svc_user (instead of one):

Nov  2 16:49:05 localhost.localdomain notice su[13403]: (to tomcat) root on none
Nov  2 16:49:05 localhost.localdomain warning su[13403]: pam_lastlog(su:session): corruption detected in /var/log/btmp
Nov  2 16:51:46 localhost.localdomain notice mcpd[7305]: pam_unix(system-auth:chauthtok): password changed for svc_user
Nov  2 16:51:50 localhost.localdomain info httpd(pam_audit)[18403]: user=svc_user(svc_user) partition=[All] level=Administrator tty=(unknown) host=10.8.7.7 attempts=1 start="Mon Nov  2 16:51:50 2020" end="Mon Nov  2 16:51:50 2020".
Nov  2 16:51:50 localhost.localdomain info httpd(pam_audit)[18403]: 01070417:6: AUDIT - user svc_user - RAW: httpd(pam_audit): user=svc_user(svc_user) partition=[All] level=Administrator tty=(unknown) host=10.8.7.7 attempts=1 start="Mon Nov  2 16:51:50 2020" end="Mon Nov  2 16:51:50 2020".
Nov  2 16:56:51 localhost.localdomain info httpd(pam_audit)[18403]: user=svc_user(svc_user) partition=[All] level=Administrator tty=(unknown) host=10.8.7.7 attempts=1 start="Mon Nov  2 16:56:51 2020" end="Mon Nov  2 16:56:51 2020".
Nov  2 16:56:51 localhost.localdomain info httpd(pam_audit)[18403]: 01070417:6: AUDIT - user svc_user - RAW: httpd(pam_audit): user=svc_user(svc_user) partition=[All] level=Administrator tty=(unknown) host=10.8.7.7 attempts=1 start="Mon Nov  2 16:56:51 2020" end="Mon Nov  2 16:56:51 2020".
Nov  2 17:02:01 localhost.localdomain info httpd(pam_audit)[21879]: user=svc_user(svc_user) partition=[All] level=Administrator tty=(unknown) host=10.8.7.7 attempts=1 start="Mon Nov  2 17:02:01 2020" end="Mon Nov  2 17:02:01 2020".
Nov  2 17:02:01 localhost.localdomain info httpd(pam_audit)[21879]: 01070417:6: AUDIT - user svc_user - RAW: httpd(pam_audit): user=svc_user(svc_user) partition=[All] level=Administrator tty=(unknown) host=10.8.7.7 attempts=1 start="Mon Nov  2 17:02:01 2020" end="Mon Nov  2 17:02:01 2020".

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/2nic/existing-stack/payg

but other templates are likely to be affected as well.

## Severity Level
2

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking this bug internally with ID ESECLDTPLT-2339.

**Comment by hgran** [comment]
Any progress on this?

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
