### ISSUE TITLE
Additional documentation mentioned in 9.2 release notes but not found

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-azure-arm-templates#214]
## Do you already have an issue opened with F5 support?
No

## Description
[v9.2.0.0 Release Notes](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v9.2.0.0) says that documentation was updated for the following:
- validating the success of the deployment (where to find output),
- how to test WAF.

I could not find any new information on these topics neither in the README.md files (e.g. under [failover-lb-3nic-existing-payg](https://github.com/F5Networks/f5-azure-arm-templates/tree/v9.2.0.0/supported/failover/same-net/via-lb/3nic/existing-stack/payg) or [autoscale-waf-lb-1nic-existing-payg](https://github.com/F5Networks/f5-azure-arm-templates/tree/v9.2.0.0/supported/autoscale/waf/via-lb/1nic/existing-stack/payg)) nor in the [BIG-IP VE in Microsoft Azure](https://clouddocs.f5.com/cloud/public/v1/) part of F5 Clouddocs. Would you please advise where I can find this additional information?

## Template
Unclear what templates are referred to in the Release Notes point item in question

## Severity Level
5

**Comment by shyawnkarim** [comment]
Documentation for validating the success of the deployment, where to find output, and how to test WAF can be found on the [README](https://github.com/F5Networks/f5-azure-arm-templates-v2/tree/master/examples/autoscale/payg) for [V2 of our autoscale templates](https://github.com/F5Networks/f5-azure-arm-templates-v2/tree/master/examples/autoscale). Scroll down to the Validation section to find it.

Our release notes were ambiguous and should have specified V2 for clarity.

**Comment by shyawnkarim** [comment]
Closing.

Please reopen if you need anything else.
