### ISSUE TITLE
License key fields not required input for BYOL template

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-azure-arm-templates#215]
## Do you already have an issue opened with F5 support?
No, this was a simple misunderstanding but we'd still like to submit an issue.

## Description
Could we consider making the License Key field mandatory for BYOL templates?

A customer recently deployed a [BYOL failover template](https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol) and did not fully understand the pre-req's. He left the License Key fields blank because they were not mandatory fields, and deployed the template. 

The BIG-IP's deployed but onboarding script failed. Nevertheless he logged into the GUI and then licensed his devices manually, and then asked why the devices were not clustered.

If those fields were mandatory it may be more obvious that the license key is required at time of deployment. Many thanks.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol/azuredeploy.json#L66

## Severity Level
5

**Comment by shyawnkarim** [comment]
Thanks for providing this feedback. We are now tracking this enhancement request with internal ID ESECLDTPLT-2393.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
