### ISSUE TITLE
Per-App Images are not allowed in Failover PAYG templates

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-azure-arm-templates#216]
## Do you already have an issue opened with F5 support?
No

## Description
I believe, the following image names should be added to the `allowedValues` list for the `imageName` parameter:

- PerAppVeLtm25Mbps
- PerAppVeLtm200Mbps
- PerAppVeAdvancedWaf25Mbps
- PerAppVeAdvancedWaf200Mbps

These image names are already listed in the `paygImageMap` variable and they are allowed in the Standalone templates. 

I have tested one of the PerApp images (PerAppVeAdvancedWaf25Mbps) in the via-LB Failover implementation and it works as expected. 

It may be worth noting in the README.md file that a wildcard VIP 0.0.0.0/0 must be used in the via-LB Failover implementations as Per-App license only allows a single VIP with either address/32 and 0.0.0.0/0 destination.

I may have missed (other) issues with using the Per-App licenses in Failover Azure VE implementations. If Per-App image types are not allowed in the template due to such issues, they must be documented in the README.md files.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic/existing-stack/payg
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/failover/same-net/via-api/n-nic/existing-stack/payg/azuredeploy.json
and all other Failover PAYG templates.

## Severity Level
2

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking this bug internally with ID ESECLDTPLT-2394.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).

Additionally, our per App images have since been removed from the Marketplace.
