### ISSUE TITLE
Remove "0" from public ip name

### ISSUE THREAD

**Issue by BDragonReborn1** [F5Networks/f5-azure-arm-templates#217]
## Do you already have an issue opened with F5 support?
No

## Description
Template keeps appeneding 0 to public ip address name

## Template
Current master

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 4

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Our templates append a number to the end of cloud resource names so that when multiples of the same type of resource are deployed they all have unique names.

**Comment by shyawnkarim** [comment]
Closing. Please reopen if necessary.
