### ISSUE TITLE
bigiq template fails to deploy with Azure policies for storage accounts.

### ISSUE THREAD

**Issue by paultaiton** [F5Networks/f5-azure-arm-templates#220]
## Description
The bigiq azure template will fail if you have policies to enforce storage account minimum TLS version or Blob public access. This is due to how old the StorageApiVersion is, since these properties were created after 2017.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/failover/same-net/via-lb/1nic/existing-stack/bigiq/azuredeploy.json

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue and submitting a pull request. I have added this issue, Internal ID ESECLDTPLT-2521, to our backlog for an engineer to review.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
