### ISSUE TITLE
Unable to deploy ARM template - InvalidTemplateDeployment

### ISSUE THREAD

**Issue by minnocentini** [F5Networks/f5-azure-arm-templates#222]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

No

## Description
Describe the problem you're having or the enhancement you'd like to request.

attempting to deploy ARM template: 

https://github.com/F5Networks/f5-azure-arm-templates/tree/v9.3.0.0/supported/standalone/1nic/existing-stack/byol

{"code":"InvalidTemplateDeployment","details":[{"code":"InvalidParameter","target":"imageReference","message":"The following list of images referenced from the deployment template are not found: Publisher: f5-networks, Offer: f5-big-ip-byol, Sku: f5-big-all-2slot-byol, Version: 15.1.200000. Please refer to https://docs.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage for instructions on finding available images."}],"message":"The template deployment 'Microsoft.Template-20210408150047' is not valid according to the validation procedure. The tracking id is '1302c5e2-090f-4a9c-9cda-f149d428fdff'. See inner errors for details."}

## Template
For bugs, enter the template with which you are experiencing issues below.
https://github.com/F5Networks/f5-azure-arm-templates/tree/v9.3.0.0/supported/standalone/1nic/existing-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

2 - High 

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by minnocentini** [comment]
For now if you change BIG-IP version to 'latest' it seems to go thru, however it deploys 16.0.1.1. I want the latest 15.1.2.1 release, but entering 15.1.210010 fails as well. Not sure how to match version number on f5 download site with azure versions.

**Comment by JeffGiroux** [comment]
@minnocentini you can refer to the offer list on the main repo page, which appears to be old. I don't see the 15.1.2.1 equivalent on there which should be 15.1.20100. 

You can get an updated list by running an 'az cli' command below:
```
az vm image list -f big-ip --all
```

The usual output generated by the F5 team at each release is listed at link below.
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/azure-offer-list.yaml

**Comment by minnocentini** [comment]
Thanks, I can see the correct version to use from the output of that command is:
15.1.201000

The template should be updated to reflect this or use the keyword latest.

—Mike

**Comment by shyawnkarim** [comment]
This is a known issue and will be fixed in the new release.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 9.5.0.0](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v9.5.0.0).
