### ISSUE TITLE
Internal LB is confusing

### ISSUE THREAD

**Issue by justinbeckham** [F5Networks/f5-azure-arm-templates#223]
## Do you already have an issue opened with F5 support?
No

## Description
The documentation could be clarified regarding the purpose of the Internal LB and health probe on 3456. My understanding is that it's only required for forward proxy or server-server use cases. It should be more clearly defined what's it's purpose is and what additional BIG-IP configuration components would be required for those uses cases. If it can be left out for client-server (inbound) use cases altogether then that should be explicitly stated. This is a documentation issue only.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol

## Severity Level

 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Thanks for reporting your issue. I've created ticket, internal ID ESECLDTPLT-2628, to enhance our documentation.

**Comment by lmichelino** [comment]
Hi @shyawnkarim do you have any update on this ?

**Comment by shyawnkarim** [comment]
Closing. This diagram should make things clear. 

https://github.com/F5Networks/f5-azure-arm-templates/blob/main/supported/failover/same-net/via-lb/3nic/alternate-deployment-topologies.md
