### ISSUE TITLE
F5 Active/passive support Hub&Spoke

### ISSUE THREAD

**Issue by nahimos** [F5Networks/f5-azure-arm-templates#224]
Sorry for creation of this, since it is more a design question than an issue.
With an cluster of F5 VE in Azure Hub& Spoke architecture , is it possible to have the VIP in the Hub and the loadbalanced nodes in the Spokes?
My second question : for the external subnet part is it possible to have private IP ? or only on Public Ip and 19 secondary Private IPs?

**Comment by shyawnkarim** [comment]
1. Yes, the shared services virtual network is a common architecture.
2. In general, the number of secondary private IPs is tied to the instance size, however, the default template is limited and you would need to customize the template and/or make post deployment modifications. For help with template or deployment customization please reach out to F5 Professional Services.

**Comment by nahimos** [comment]
Thanks for the answers
i saw that the secondary ip is limited to 20 ip, they can be only private ip?

**Comment by shyawnkarim** [comment]
Closing. Please reopen if needed.
