### ISSUE TITLE
issue deploying the ARM template

### ISSUE THREAD

**Issue by paolobeta71** [F5Networks/f5-azure-arm-templates#225]
Using standard information in the template I always receive the errors below and template deployment is not completed:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidTemplate","message":"Unable to process template language expressions for resource '...........>providers/Microsoft.Compute/virtualMachines/bigip-f5vm011/extensions/start' at line '1284' and column '9'. 'The language expression property '16' doesn't exist, available properties are '15, 14, 13, 12, latest'.'"}

{"code":"InvalidTemplate","message":"Unable to process template language expressions for resource '/...........providers/Microsoft.Compute/virtualMachines/bigip-f5vm010/extensions/start' at line '1256' and column '9'. 'The language expression property '16' doesn't exist, available properties are '15, 14, 13, 12, latest'.'"}]}

**Comment by mikeshimkus** [comment]
Hi, thanks for reporting. We are tracking this with internal issue #2717.  For the time being, here is the workaround:

Find this line:
"15": "tmsh modify sys db failover.selinuxallowscripts value enable",
 
and add this line before it:
"16": "tmsh modify sys db failover.selinuxallowscripts value enable",
 
and change this:
"bigIpMajorVersion": "[if(equals(parameters('bigIpVersion'), 'latest'), '15', split(variables('versionToUse'), '.')[0])]",
 
to this:
"bigIpMajorVersion": "[if(equals(parameters('bigIpVersion'), 'latest'), '16', split(variables('versionToUse'), '.')[0])]",

**Comment by shyawnkarim** [comment]
This issue was resolved with [Release 9.6.0.0](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v9.6.0.0).
