### ISSUE TITLE
Issue deploying ARM Template failover/same-net/via-api/n-nic/new-stack/payg/

### ISSUE THREAD

**Issue by frankiejl** [F5Networks/f5-azure-arm-templates#230]
I'm trying to deploy the following template experimental/failover/same-net/via-api/n-nic/new-stack/payg/ to test the CCFE failover but i get the following message:

{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The resource 'Microsoft.Authorization/roleAssignments/bb0b8dc6-6c4c-50f1-b452-705b3c165f29' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'."}

Appreciate any direction in resolving tis issue.

**Comment by shyawnkarim** [comment]
Closing. Please reopen if needed.
