### ISSUE TITLE
ARM Template deployment fails with extension 

### ISSUE THREAD

**Issue by kb185177** [F5Networks/f5-azure-arm-templates#234]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'start'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\n\n[stderr]\n/bin/sh: -c: line 100: unexpected EOF while looking for matching `''\n/bin/sh: -c: line 101: syntax error: unexpected end of file\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "},{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'start'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\n\n[stderr]\n/bin/sh: -c: line 100: unexpected EOF while looking for matching `''\n/bin/sh: -c: line 101: syntax error: unexpected end of file\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "}]}

**Comment by shyawnkarim** [comment]
Can your share the template you used and your parameter file? Please scrub any sensitive data before sending over.

**Comment by shyawnkarim** [comment]
Closing. Please open another issue if you need more assistance.
