### ISSUE TITLE
Provide ability to encrypt BIG-IP disks using SSE CMK

### ISSUE THREAD

**Issue by mwardbopp** [F5Networks/f5-azure-arm-templates#235]
I have a number of customers who want to encrypt the disks of their BIG-IP deployments in Azure using SSE with customer managed keys. AFAIK the current templates do not support this.

Workaround:

https://github.com/F5Networks/f5-azure-arm-templates-v2/issues/9

**Comment by shyawnkarim** [comment]
Thanks for reporting this RFE that your customers are requesting. We are now tracking this request with internal ID ESECLDTPLT-2986.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
