### ISSUE TITLE
Provide support for v4/v5 instance types

### ISSUE THREAD

**Issue by mwardbopp** [F5Networks/f5-azure-arm-templates#236]
Microsoft are advising that v2/v3 instance types have low capacity in certain regions and are recommending using v4 or v5.

**Comment by mikeshimkus** [comment]
@mwardbopp We created issue ESECLDTPLT-3047 for this. It will be addressed in the next templates release.

**Comment by shyawnkarim** [comment]
Closing.

This ticket was included with [Release 9.8.0.0.](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v9.8.0.0)
