### ISSUE TITLE
Virtual IPs are not included in the Common partition after building the LTM with the template

### ISSUE THREAD

**Issue by difzhao** [F5Networks/f5-azure-arm-templates#237]
I am using the template version 9.9.1.0 to build two pairs of LTMs, one for QA and another for PRD. The parameters are almost identical except with different IPs and hostnames. The `numberOfExternalIps` parameter is set to 20 for both. I noticed recently that the QA pair (which was built one month earlier than the PRD pair) has all 20 external IPs listed under the Common partition under the Virtual address list while the PRD pair doesn't. 

I actually don't know if it is the template that creates these virtual addresses or not. I would think that is the case because none of my DO files or AS3 files contain them. However, I do want to confess that I have different version (slightly) of DO and AS3 plugins installed. I don't know if either one could overwrite the existing configuration built by the template. 

I would appreciate if you can point me to the right direction for troubleshooting this. Thanks!

**Comment by difzhao** [comment]
Thanks for your quick response Shyawn! However, I don't have this log file...

***@***.***:Active:In Sync] ~ # less /var/log/cloud/azure/custom-config.log
/var/log/cloud/azure/custom-config.log: No such file or directory
***@***.***:Active:In Sync] ~ # ls /var/log/cloud/azure/
cluster.log  install.log  network.log  onboard.log  stderr  stdout

I don't have the log file on the good pair either. The VM was built in early June... Will the log stay for that long?

Thanks,
Difan

**Comment by difzhao** [comment]
> The creation of the virtual addresses are logged on the first VM in /var/log/audit. You can see them with `egrep -i virtual-address /var/log/audit `
> 
> The output of the custom script to create those addresses can found with `cat /var/lib/waagent/custom-script/download/0/stdout` `cat /var/lib/waagent/custom-script/download/0/stderr`
> 
> These outputs are then copied to `/var/log/cloud/azure/stdout` `/var/log/cloud/azure/stderr`
> 
> and then into `/var/log/cloud/azure/install.log`
> 
> This way, everything can be found in `var/log/cloud/azure`
> 
> Hopefully this helps with tracking down your issue.

Thanks Shyawn for your input. I compared the logs in `/var/log/cloud/azure/stdout` and `stderr` between the working one and none working one and I don't even see the line that says creating the virtual addresses... I saw the one about creating the self IP and the default gateway but not for the virtual addresses
I have opened a case with the support team. I hope they can find out something about this. Thanks!

**Comment by shyawnkarim** [comment]
Closing since a support case was opened.
