### ISSUE TITLE
issue deploying ARM Template

### ISSUE THREAD

**Issue by M0jAcK0L** [F5Networks/f5-azure-arm-templates#238]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidTemplate","message":"Unable to process template language expressions for resource '/subscriptions/.../providers/Microsoft.Logic/workflows/logicapptest' at line '24' and column '5'. 'The language expression property 'definition' doesn't exist, available properties are 'type, name, apiVersion, location, properties, dependsOn'.'"}]}

**Comment by mikeshimkus** [comment]
@M0jAcK0L Which template are you using? The resource /subscriptions/.../providers/Microsoft.Logic/workflows/logicapptest doesn't exist in any of the supported templates.
