### ISSUE TITLE
Disable Network Failover

### ISSUE THREAD

**Issue by aconley245** [F5Networks/f5-azure-arm-templates#240]
When deploying the failover/same-net/via-lb ARM templates, setting Network Failover to No has no effect.  The device group is still deployed with network failover enabled.

**Comment by shyawnkarim** [comment]
You are correct: the template will deploy a device group regardless if the parameter enableNetworkFailover is yes or no, however, the deployment will still be different. 

Enabling failover creates a traditional active/standby deployment with traffic groups and mirroring. When failover is disabled, the devices are active/active and use traffic group none.

**Comment by aconley245** [comment]
I agree disabling network failover should create an active/active pair.  When I disable network failover using the arm template, it still deploys the VEs with network failover enabled.

**Comment by aconley245** [comment]
I see now where Network Failover is being disabled.
