### ISSUE TITLE
New Stack missing or?

### ISSUE THREAD

**Issue by PatricDahl** [F5Networks/f5-azure-arm-templates#242]
Hi,

Have I missed something? New Stack is missing within https://github.com/F5Networks/f5-azure-arm-templates/tree/main/supported/standalone/3nic

BR
Patric

**Comment by shyawnkarim** [comment]
These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).

[New Stack can be found in that repo here.](https://github.com/F5Networks/f5-azure-arm-templates-v2/tree/main/examples/quickstart)

**Comment by shyawnkarim** [comment]
Closing. Please open a new issue if you would still like assistance.
