### ISSUE TITLE
Encrypted storage account

### ISSUE THREAD

**Issue by mtengmo** [F5Networks/f5-azure-arm-templates#25]
## Description
Describe the problem you're having or the enhancement you'd like to request.

The ARM templates doesn´t support encrypted storage account. This is a policy that could be set on subscription level.
The change is larger than just creating the storageaccount because of different api versions. 

## Template
For bugs, enter the template with which you are experiencing issues below.
supported/cluster/3nic/boyl

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>
4

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Steps to add support for encrypted storage:

- Bump storageApiVersion to 2016-12-01 or later
- Add boolean type parameter for blobEncryptionEnabled
- Updated VM storage account resources to use new API version and pass blobEncryptionEnabled parameter to encryption property

**Comment by edwoodjrjr** [comment]
We tested and staged to above changes, then realized that:

- Encryption is now enabled by default for Azure storage accounts created by our templates.
- Specifying blobEncryptionEnabled:true has no effect (accounts are always encrypted). Not sure if this is intended or a bug on Microsoft's part...will revisit adding a parameter of dwindling usefulness for that in the future.
