### ISSUE TITLE
Can´t download cloudlibs

### ISSUE THREAD

**Issue by mtengmo** [F5Networks/f5-azure-arm-templates#26]
## Description
Describe the problem you're having or the enhancement you'd like to request.

The json file looks on wrong uri for cloudlibs. 

                        "[concat('https://raw.githubusercontent.com/F5Networks/f5-cloud-libs/', variables('f5CloudLibsTag'), '/dist/f5-cloud-libs.tar.gz')]", 
                        "[concat('https://raw.githubusercontent.com/F5Networks/f5-cloud-iapps/', variables('f5CloudIappsTag'), '/f5-service-discovery/f5.service_discovery.tmpl')]"

The real path is not having any "version" in f5cloudlibstag. 

## Template
For bugs, enter the template with which you are experiencing issues below.

cluster-3nic-boyl

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>
4

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by jsevedge** [comment]
Hey @mtengmo did you see any issues with the template or are you just pointing this out?  

Fyi - How it determines which branch/tag to pull from is based on the path in the url. This variable 'f5CloudLibsTag' (or something similar for other repos we pull from) is what contains which branch to pull it from and that is included in the URL.

**Comment by jsevedge** [comment]
@mtengmo Ah, issue title says cannot download cloud libs, however i still do not believe it is a result of the path being wrong as i just checked that template in master and the f5cloudlibstag is correct in the template.  Are you trying to deploy the ARM template from master?  Anything else to note about the deployment?

**Comment by jsevedge** [comment]
@mtengmo I believe this was a result of an issue with github based on our analysis and internal test failures around the same time period.  I will close this out, please reopen if you run into this again.
