### ISSUE TITLE
AutoScale Templates have incorrect deploy link in v3.3.1.0

### ISSUE THREAD

**Issue by jsevedge** [F5Networks/f5-azure-arm-templates#28]
## Description
Describe the problem you're having or the enhancement you'd like to request.

If you try and click on the AutoScale template deploy buttons from the main readme you will receive the following error…

There was an error loading the template from URI 'https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/v3.3.1.0/supported/solutions/autoscale/waf/azuredeploy.json'. Ensure that the template is publicly accessible and does not have any comments.

## Template
For bugs, enter the template with which you are experiencing issues below.
AutoScale LTM/WAF - Only MAIN readme

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
This issue was fixed in f5-azure-arm-templates release v3.2.2.0.
