### ISSUE TITLE
[WAF Autoscale] Service Discovery iApp troubleshoot

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-azure-arm-templates#31]
## Description
Seems that when the service principal contains a "+" char, TCL interprets that as a space causing authentication with Azure to fail. 

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/solutions/autoscale/waf/existing_stack

## Severity Level

Severity: 4

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

## Logs /var/log/restnoded/restnoded.log

I obfuscated the secret and IDs but the secret looks very similar to how it originally was

Mon, 04 Sep 2017 15:15:52 GMT - fine: [CloudNodesWorker] onGet
Mon, 04 Sep 2017 15:15:52 GMT - fine: [CloudNodesWorker] using cloud azure
Mon, 04 Sep 2017 15:15:52 GMT - fine: Initializing cloud provider
Mon, 04 Sep 2017 15:15:52 GMT - finest: providerOptions: mgmtPort=8443, resourceGroup=WP-RG1, subscriptionId=1a1a1a1a-1a1a1a-1a1a-1a1a-1a1a1a1a, clientId=1a1a1a1a-1a1a-1a1a-1a1a-1a1a1a1a1a1a1a, tenantId=fd38e1e8-4f0a-4ac4-8865-3299689ba56d, secret=EE2EEEE bOeeeeeeek/8T0u8/9sdofijsSOdSikwQdOI=      <---plus sign is a space!!

Mon, 04 Sep 2017 15:15:52 GMT - severe: Error while getting nodes Error: Failed to acquire token for application with the provided secret. 
Error: Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: 
----snip----
    at /config/cloud/node_modules/f5-cloud-libs/node_modules/f5-cloud-libs-azure/node_modules/ms-rest-azure/lib/credentials/applicationTokenCredentials.js:131:29
    at /config/cloud/node_modules/f5-cloud-libs/node_modules/f5-cloud-libs-azure/node_modules/ms-rest-azure/node_modules/adal-node/lib/token-request.js:150:11
    at Request._callback (/config/cloud/node_modules/f5-cloud-libs/node_modules/f5-cloud-libs-azure/node_modules/ms-rest-azure/node_modules/adal-node/lib/util.js:133:7)
    at Request.self.callback (/config/cloud/node_modules/f5-cloud-libs/node_modules/f5-cloud-libs-azure/node_modules/ms-rest-azure/node_modules/adal-node/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/config/cloud/node_modules/f5-cloud-libs/node_modules/f5-cloud-libs-azure/node_modules/ms-rest-azure/node_modules/adal-node/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/config/cloud/node_modules/f5-cloud-libs/node_modules/f5-cloud-libs-azure/node_modules/ms-rest-azure/node_modules/adal-node/node_modules/request/request.js:1091:12)
Mon, 04 Sep 2017 15:15:52 GMT - severe: [ErrorHandlingModule] RestOperation failed: "/shared/cloud/nodes?memberAddressType=private&mgmtPort=8443&cloud=azure&memberTag=application%3Dwordpress&providerOptions=resourceGroup%3DWP-RG1%2C
----snip----
%2Csecret%EE2EEEE+bOeeeeeeek/8T0u8/9sdofijsSOdSikwQdOI=memberPort=80".   <---the plus sign exists here tho

**Comment by edwoodjrjr** [comment]
This affects more than just the service discovery iApp.  The Azure autoscale and failover providers also use service principal.

**Comment by jsevedge** [comment]
@tkam8 Thanks for bringing this to our attention, we are working on reproducing this and then getting it fixed within the service discovery iApp.

**Comment by jsevedge** [comment]
This should now be resolved, please use the latest version of the service discover iApp.
