### ISSUE TITLE
post deployment scripts are not working on cluster-1nic-existingstack setup

### ISSUE THREAD

**Issue by mtengmo** [F5Networks/f5-azure-arm-templates#32]
## Description
After deployment, boxes are setup as standalone without license. 

## Template
cluster-1nic-existingstack

.\Deploy_via_PS.ps1 -licenseType BYOL -licensedBandwidth 200m -adminUsername azureuser -adminPassword xxxxxx -dnsLabel t-hostname -instanceName bigip -instanceType Standard_DS12_v2 -imageName Best -bigIpVersion 13.0.021 -numberOfExternalIps 1 -vnetName T-EUN-VNET-010-100 -vnetResourceGroupName T-EUN -mgmtSubnetName T-EUN-SUB-010-100-001 -mgmtIpAddressRangeStart 10.100.1.10 -externalSubnetName T-EUN-SUB-010-100-001 -externalIpSelfAddressRangeStart 10.100.1.12 -externalIpAddressRangeStart 10.100.1.14 -internalSubnetName T-EUN-SUB-010-100-001 -internalIpAddressRangeStart 10.100.1.18 -ntpServer 0.pool.ntp.org -timeZone UTC -restrictedSrcAddress "*" -resourceGroupName T-EUN-ADC10 -licensekey1 xxxxxxxx-licensekey2 xxxxxxx -region NorthEurope

## Severity Level
medium

#logfile
waagent.log
device0
2017/09/06 05:24:51 Windows Azure Linux Agent Version: WALinuxAgent-2.0.10
2017/09/06 05:24:51 Linux Distribution Detected      : centos
2017/09/06 05:24:51 Module /lib/modules/3.10.0-327.36.3.el7.ve.x86_64/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM is already present.
2017/09/06 05:24:52 mount: block device /dev/sr0 is write-protected, mounting read-only
2017/09/06 05:24:52 mount: you didn't specify a filesystem type for /dev/sr0
2017/09/06 05:24:52        I will try type udf
2017/09/06 05:24:52 mount: you didn't specify a filesystem type for /dev/sr0
2017/09/06 05:24:52        I will try type udf
2017/09/06 05:24:52 /dev/sr0 on /mnt/cdrom/secure type udf (ro)
2017/09/06 05:24:52 mount succeeded on attempt #1
2017/09/06 05:24:52 VMM Init script not found.  Provisioning for Azure
2017/09/06 05:24:52 IPv4 address: 10.100.1.10
2017/09/06 05:24:52 MAC  address: 00:0D:3A:B7:9D:EF
2017/09/06 05:24:52 Probing for Windows Azure environment.
2017/09/06 05:24:52 DoDhcpWork: Setting socket.timeout=10, entering recv
2017/09/06 05:24:52 Discovered Windows Azure endpoint: 168.63.129.16
2017/09/06 05:24:52 Fabric preferred wire protocol version: 2015-04-05
2017/09/06 05:24:52 Negotiated wire protocol version: 2012-11-30
2017/09/06 05:24:52 SetBlockDeviceTimeout: Update the device sda with timeout 300
2017/09/06 05:24:52 SetBlockDeviceTimeout: Update the device sdb with timeout 300
2017/09/06 05:24:52 EnvMonitor: Moved /lib/udev/rules.d/75-persistent-net-generator.rules -> /var/lib/waagent
2017/09/06 05:24:52 Retrieved GoalState from Windows Azure Fabric.
2017/09/06 05:24:52 ExpectedState: Started
2017/09/06 05:24:52 ContainerId: ed765d05-d687-49e7-829b-d1685fe6acf5
2017/09/06 05:24:52 RoleInstanceId: 87b92c9c-559e-471f-ae8b-3994d2be129e._t-seunadc10-bigip0
2017/09/06 05:24:52 Provisioning image started.
2017/09/06 05:24:52 mount: block device /dev/sr0 is write-protected, mounting read-only
2017/09/06 05:24:52 mount succeeded on attempt #1
2017/09/06 05:24:52 Provisioning image using OVF settings in the DVD.
2017/09/06 05:25:00 Resource disk (/dev/sdb1) is mounted at /mnt/resource with fstype ext4
2017/09/06 05:25:32 EnvMonitor: Detected dhcp client restart. Restoring routing table.
2017/09/06 05:26:22 Created user account: azureuser
2017/09/06 05:26:25 Ovf XML process finished
2017/09/06 05:26:25 ERROR:CalledProcessError.  Error Code is 1
2017/09/06 05:26:25 ERROR:CalledProcessError.  Command string was ssh-keygen -lf /etc/ssh/ssh_host_rsa_key.pub
2017/09/06 05:26:25 ERROR:CalledProcessError.  Command result was /etc/ssh/ssh_host_rsa_key.pub: No such file or directory
2017/09/06 05:26:25 Posted Role Properties. CertificateThumbprint=No
2017/09/06 05:26:25 Root password deleted.
2017/09/06 05:26:25 Provisioning image completed.
2017/09/06 05:26:25 ERROR:Can't find host key: /etc/ssh/ssh_host_rsa_key.pub

device1

2017/09/06 05:24:16 Windows Azure Linux Agent Version: WALinuxAgent-2.0.10
2017/09/06 05:24:16 Linux Distribution Detected      : centos
2017/09/06 05:24:16 Module /lib/modules/3.10.0-327.36.3.el7.ve.x86_64/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM is already present.
2017/09/06 05:24:17 mount: block device /dev/sr0 is write-protected, mounting read-only
2017/09/06 05:24:17 mount: you didn't specify a filesystem type for /dev/sr0
2017/09/06 05:24:17        I will try type udf
2017/09/06 05:24:17 mount: you didn't specify a filesystem type for /dev/sr0
2017/09/06 05:24:17        I will try type udf
2017/09/06 05:24:17 /dev/sr0 on /mnt/cdrom/secure type udf (ro)
2017/09/06 05:24:17 mount succeeded on attempt #1
2017/09/06 05:24:17 VMM Init script not found.  Provisioning for Azure
2017/09/06 05:24:17 IPv4 address: 10.100.1.11
2017/09/06 05:24:17 MAC  address: 00:0D:3A:B7:9C:F6
2017/09/06 05:24:17 Probing for Windows Azure environment.
2017/09/06 05:24:17 DoDhcpWork: Setting socket.timeout=10, entering recv
2017/09/06 05:24:17 Discovered Windows Azure endpoint: 168.63.129.16
2017/09/06 05:24:17 Fabric preferred wire protocol version: 2015-04-05
2017/09/06 05:24:17 Negotiated wire protocol version: 2012-11-30
2017/09/06 05:24:17 SetBlockDeviceTimeout: Update the device sda with timeout 300
2017/09/06 05:24:17 SetBlockDeviceTimeout: Update the device sdb with timeout 300
2017/09/06 05:24:17 EnvMonitor: Moved /lib/udev/rules.d/75-persistent-net-generator.rules -> /var/lib/waagent
2017/09/06 05:24:17 Retrieved GoalState from Windows Azure Fabric.
2017/09/06 05:24:17 ExpectedState: Started
2017/09/06 05:24:17 ContainerId: 300e6519-521d-4e87-b801-12ae914d0e65
2017/09/06 05:24:17 RoleInstanceId: 87b92c9c-559e-471f-ae8b-3994d2be129e._t-seunadc10-bigip1
2017/09/06 05:24:17 Provisioning image started.
2017/09/06 05:24:17 mount: block device /dev/sr0 is write-protected, mounting read-only
2017/09/06 05:24:17 mount succeeded on attempt #1
2017/09/06 05:24:17 Provisioning image using OVF settings in the DVD.
2017/09/06 05:24:25 Resource disk (/dev/sdb1) is mounted at /mnt/resource with fstype ext4
2017/09/06 05:24:57 EnvMonitor: Detected dhcp client restart. Restoring routing table.
2017/09/06 05:25:46 Created user account: azureuser
2017/09/06 05:25:49 Ovf XML process finished
2017/09/06 05:25:49 ERROR:CalledProcessError.  Error Code is 1
2017/09/06 05:25:49 ERROR:CalledProcessError.  Command string was ssh-keygen -lf /etc/ssh/ssh_host_rsa_key.pub
2017/09/06 05:25:49 ERROR:CalledProcessError.  Command result was /etc/ssh/ssh_host_rsa_key.pub: No such file or directory
2017/09/06 05:25:49 Posted Role Properties. CertificateThumbprint=No
2017/09/06 05:25:49 Root password deleted.
2017/09/06 05:25:49 Provisioning image completed.
2017/09/06 05:25:49 ERROR:Can't find host key: /etc/ssh/ssh_host_rsa_key.pub

/var/lib/waagent/custom-script don´t exists.

**Comment by edwoodjrjr** [comment]
If the custom-script directory doesn't exist, that points to a problem with Azure, not the deployment scripts.

Did you use a "#" in the admin password? Does this work in other regions?

**Comment by mtengmo** [comment]
Not # in pw, using the "standard" password without strange characters. 
I will say that North Europe have been one region that got problem, often fails to deploy here.

**Comment by mtengmo** [comment]
I have been running wrong json with wrong ps1 script. My fault.
