### ISSUE TITLE
[RFI] Template Customization Guidelines

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-azure-arm-templates#33]
## Description

Are there any guidelines for further customizing the provided templates to meet various customer requirements? 

For instance: 

- List of configuration objects that should not be modified or removed, or caveats if modified/removed
- List of requirements that need to be met in order for a completely customized template to be considered a  "supported" F5 template

Also if any info about below, please advise:

- Any support for install of custom waagent (ie. for a custom monitoring agent component)?
- Any supported restoration process for a deployed solution?

## Template

Any 

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 4

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by jsevedge** [comment]
@tkam8 We do in fact support customization within the template in one specific way and it will still be fully supported.  That is if you want to configure the BIG-IP after initial on boarding by running tmsh, etc.. that can be done and is outlined in each readme such as [here](https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/standalone/3nic/new_stack/README.md#deploying-custom-configuration-to-the-big-ip-azure-virtual-machine) for standalone/3nic on how to do it.

If you want to customize the ARM template resources themselves though to add NSG rules or something of that nature then assistance on that would be best effort and the template would not be officially supported.

**Comment by tkam8** [comment]
@jsevedge this is the latter, customizing the template itself like nsg etc. let me gather more details as to what kinds of settings to give a better idea of whether they could be default fields.

**Comment by tkam8** [comment]
In the meantime, would you be able to consider the below request? For instance, in order for a module to be "upstreamed" to the core Ansible repo, the module must be tested to pass specific qualifications (see: http://f5-ansible.readthedocs.io/en/devel/development/upstreaming.html#id3).  :

- List of requirements/qualifications that need to be met in order for a completely customized template to be considered a "supported" F5 template

The idea is that this will allow the community to build custom templates according to our standard, and maybe allow it to eventually become part of our supported templates if it's a reasonable use case.

**Comment by edwoodjrjr** [comment]
https://github.com/f5devcentral is the site for community contributions.  As far as an official upstreaming process, I will check into that.

**Comment by jsevedge** [comment]
At this time there are still no plans for official customization support and related guidelines (aside from the previously mentioned custom script section), if this is something that is still very valuable please feel free to reopen or open a new issue, thanks!
