### ISSUE TITLE
Expanding the 1NIC template to support Internal Load Balancer

### ISSUE THREAD

**Issue by pcloup** [F5Networks/f5-azure-arm-templates#34]
## Description
A customer is willing to have 1NIC Template using External LB and Internal LB, while using 1NIC template. we have updated the 3NIC template to support this (experimental branch), but there is no specific reason to not provide the same addition in the 1NIC template ?

## Severity Level
Severity: 5

**Comment by Klipope** [comment]
any feedback on this issue/enhancement request? thanks

**Comment by edwoodjrjr** [comment]
I am still researching if this is feasible or not.  Did some testing and it is not possible to configure the ALB and the all-protocol ILB load balancing rules to target the same IP config in Azure.  With 1NIC, we only have the single NIC to target, so this becomes a limitation.

**Comment by edwoodjrjr** [comment]
Sounds like the initial request was satisfied by using the 3 NIC template.  Let me know directly if that's not the case.
