### ISSUE TITLE
BIG-IP OMS Integration

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-azure-arm-templates#35]
## Feature Request

Looking for OMS integration with BIG-IP (outside of ASC), this can either be with an iApp/Script/iRule or support for the native [OMS Linux Agent](https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-agent-linux). **Support** for the Agent could also be similar to other 3rd party agents that exist on the BIG-IP, which are not covered by F5, but also do not invalidate the BIG-IP for support cases.

## Template
N/A though ASC deployments already have this, so everything else.

## Request Level
**Medium** this request should have some priority behind it, the Slack channel and DL's have seen multiple requests.

**Comment by jsevedge** [comment]
@jmcalalang Do you have any specifics on which metrics are being asked for the most?

**Comment by jmcalalang** [comment]
Ironically, its ASM, but it’s for people that deployed from the ARM templates, and not from ASC. The second most is APM logs, for people tracking logging into O365 (federation from marketplace) or other SaaS apps. Keep in mind the API Management from azure will log to OMS, so if we wanted to keep a feature parity and offer that as a solution in the future, APM would need to log into OMS too.

**Comment by mtengmo** [comment]
Would be great.

**Comment by jsevedge** [comment]
Thanks @mtengmo for the +1, any more details you can share on specific logs that you would like to be able to send?

**Comment by mtengmo** [comment]
Basic "health" of Bigip platform. (Disk, memory, cpu and so).  
LTM - Pool status, Node status, Devicesync status. 
ASM - CEF logging to Azure Security Center
APM - Audit of authentication
Probably it´s possible to reuse some of the alerts from alertd.conf from Syslog.

**Comment by jsevedge** [comment]
@mtengmo Thanks for the feedback.

**Comment by jsevedge** [comment]
@mtengmo @jmcalalang  There is now an experimental iApp available to send event driven logs from LTM, APM, AFM, ASM to Azure OMS.  Each azure readme has a section on this and links to how to use it, here is a link to that section in one of the readmes: https://github.com/F5Networks/f5-azure-arm-templates/tree/v4.3.0.0/supported/standalone/3nic/new_stack#experimental-logging-iapp

Closing this out as a result of this solution release, please feel free to provide feedback on the iApp either via here or the slack channel.

**Comment by jmcalalang** [comment]
Already installed and working with it! Awesome work!
