### ISSUE TITLE
Azure Tagging Request

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-azure-arm-templates#36]
## Feature Request
Request to standardize on a tagging mechanism that doesn't invalidate previous ARM templates when a new instance is released. 

Something like: 
- Instance:**12**
- Instance:**13**
- Instance:**latest**

This could allow for someone to always pull the latest edition of the software branch they are standardized on (12/13) and also pull the latest software edition

## Feature Request Level
**LOW**
Only seen 1-2 requests for this, these customers are likely to Pave and Nuke solutions weekly/monthly, when the instance name shifts out from underneath the ARM template it causes failures.

**Comment by jsevedge** [comment]
@jmcalalang Understood, we thought of doing this early on but instead opted for transparency and used the name of the platform image itself.  Will take this under advisement.

Keep in mind that if using a specific github tagged release to pull down the ARM template then the template itself wont ever change.  The image may still disappear at some point from Azure if it is out of date but that would cause issues whether or not we are masking the actual image SKU.  Note: This however would be useful if pulling directly from master as the templates would definitely be changing every release, as well as when going from an old release to a newer one without changing the big image version parameter.

**Comment by jsevedge** [comment]
It was decided the templates would continue to use the complete version in the parameters, however since this issue was opened the customImage parameter was added to support scenarios similar to this one.  If that is not a viable solution here or feel strongly about this support please feel free to reopen.
