### ISSUE TITLE
Instance type link in ReadMe.md broken

### ISSUE THREAD

**Issue by itblaked** [F5Networks/f5-azure-arm-templates#38]
## Description

Link broken in ReadMe.md for supported instance types

Supported instance types and hypervisors

For a list of supported Azure instance types for this solutions, see the Azure instances for BIG-IP VE section of [https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-ve-setup-msft-azure-12-1-0/1.html#guid-71265d82-3a1a-43d2-bae5-892c184cc59b](https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-ve-setup-msft-azure-12-1-0/1.html#guid-71265d82-3a1a-43d2-bae5-892c184cc59b)

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.
Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by jsevedge** [comment]
This has now been fixed in the latest release, closing this out.
