### ISSUE TITLE
Update ARM template tool-tip - image type disk size.

### ISSUE THREAD

**Issue by guydahan** [F5Networks/f5-azure-arm-templates#39]
## Description

when using the arm template, disk size will be provisioned depending on the image type (good, better, best) and not necessarily by selected instance type.
it would be helpful if you can update the tool-tip to include this information also.

**Comment by jsevedge** [comment]
@guydahan , Thanks for the feedback.  We will add a more descriptive note for this parameter.

**Comment by jsevedge** [comment]
A more descriptive tip is now provided, closing this out.
