### ISSUE TITLE
documentation for azure supported 3nic new stack image size "page not found"

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#41]
## Description
The documentation for the 3nic new stack has a link for supported Azure image sizes. Click the link and it takes you to support.f5.com, but you get "page not found". Please correct link.

https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-ve-setup-msft-azure-12-1-0/1.html#guid-71265d82-3a1a-43d2-bae5-892c184cc59b

## Template
supported 3nic new stack

I didn't check other template documentation. Might want to give them all a sanity check for clean documentation and correct links.

## Severity Level
n/a

**Comment by JeffGiroux** [comment]
specifically, in this tree...
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/3nic/new_stack

**Comment by jsevedge** [comment]
Hello Jeff, we are aware of this issue and are working on getting the correct links.  Thanks for bringing this to our attention in case we were not aware.

**Comment by jsevedge** [comment]
This link has been corrected, closing this out.
