### ISSUE TITLE
Documentation omits ALB and NSG guidance

### ISSUE THREAD

**Issue by s-archer** [F5Networks/f5-azure-arm-templates#49]
## Description
The documentation doesn't mention the need to configure the NSG and ALB configuration required to provide access to the BIG-IP Virtual Servers.  If you follow the documentation, the resulting configuration does not work.  I assumed that since the ARM template creates the NSG and ALB configuration, that it would 'just work'.  In order to gain access to a HTTP:80 Virtual Server, I had to create an inbound NSG 'permit-80' rule, and an ALB rule, also for port 80.  

I think it would be beneficial to have an end-to-end example the creation of [a] fully functioning simple HTTP Virtual Server[s] for each of the deployment options (active/active-no-failover, active/active-with-failover, active/standby-with-failover).

Also, adding an Ansible playbook (using the http://docs.ansible.com/ansible/latest/azure_rm_deployment_module.html module) to the programmatic deployment options would be extremely beneficial.  

## Template
f5-azure-arm-templates/supported/cluster/3nic/existing_stack/README.md

## Severity Level

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Hi Stephen, our intention is to publish the kind of template you mention here:  https://github.com/F5Networks/f5-azure-arm-templates/tree/master/experimental/reference

We don't currently have a reference template for cluster 3 NIC, but we can put that on the list of things to consider for a future release.

For a supported template, we can't presume which ports the customer will want to have open externally, and feel like opening access without their knowledge is worse than making them configure Azure post-deployment.  So an unsupported reference template is how we will address this.

We also have a set of detailed network diagrams that will be published to clouddocs.f5.com that will specify all the necessary post-deployment config steps.  I will check on the ETA for that.

**Comment by stjbrown** [comment]
Hey Arch,
I have some Ansible roles built out in my repo. It is a work in progress but I have six roles that correspond directly to specific ARM templates. My goal is to complete a role for all of the ARM templates and to make it more generic so that it can be published elsewhere. If you have feedback I would appreciate it. 

https://github.com/stjbrown/f5-azure-ansible

**Comment by s-archer** [comment]
@edwoodjrjr : Thanks for the quick response.  It's great to hear that we have additional documentation on the way.  i just thought we should, at least, add notes about configuring NSG and ALB in the same way that we explain that you need to create virtual servers 'In order to pass traffic from your clients to the servers through the BIG-IP system'.

@stjbrown : Nice work, I'll take a look and provide feedback :)  I've created playbooks for a few of the templates too, but thought it would be nice if they were updated by f5networks, as and when the template parameters change.

**Comment by stjbrown** [comment]
@s-archer I have been trying to update my roles as we release new code, but managing these for all is a decent amount of work even if it is just the 6 I have so far.

**Comment by edwoodjrjr** [comment]
Documented ALB/NSG post-deployment reqs in cloud release 8.
