### ISSUE TITLE
Does it support a existing vnet? 

### ISSUE THREAD

**Issue by mtengmo** [F5Networks/f5-azure-arm-templates#5]
I got a template that does this.

**Comment by edwoodjrjr** [comment]
Hi mtengmo, these templates currently do not support deploying into existing virtual networks.  Because it requires static IP addresses, the cluster template will not support this, but for the 1NIC and 2NIC_limited templates, we will look into adding this functionality.

**Comment by jsevedge** [comment]
H mtengmo,  as an additional note the templates currently deploy big ip(s) into a new vnet with the expectation that vnet peering would be setup to connect to the vnet(s) where the web/app servers are running.  This typically allows for more flexibility then requiring all web/app servers to be in a single vnet(including big ip).  As edwoodjrjr suggested though we will definitely look into adding support for existing vnets where possible to handle both scenarios.

**Comment by mtengmo** [comment]
Ok, you can compare the code from this: https://github.com/jonaserikson/Azure/tree/master/JSON/quick-redeploy-f5-big-ip
It´s rebuilt and work with existing vnet, but hardcoded IP, not perfect but a start. It´s built on old template from Greg´s blogpost on F5.

**Comment by mtengmo** [comment]
edwoodjrjr: The template I used got static IP and using a cluster, so I don´t see why it´s impossible? 
We already got VNET deployed with NGF between subnets. It makes it harder to use a seperate vnet with peering.

**Comment by razakkn** [comment]
Hi,
I want to use this template for existing vnet, i tried modifying the variables, but then while validation it throws me error that resource doesn't exist. While the resource is declared for subnets in templates.  could someone help me with this?

**Comment by edwoodjrjr** [comment]
Hi razakkn, we usually see that message when a resource has dependencies that aren't in the template.  Can you check the dependsOn for all resources to make sure that the Vnet is not referenced there?

**Comment by jsevedge** [comment]
Hello @mtengmo @razakkn , we now have an experimental 3nic template that will accept user input for existing network entities and deploy into those, location below.

https://github.com/F5Networks/f5-azure-arm-templates/tree/v3.0.0.0/experimental/standalone/3nic/existing_stack
