### ISSUE TITLE
Update ha-avset ReadMe prerequisites to include "Allow Azure API calls over port 443"

### ISSUE THREAD

**Issue by cabral1038** [F5Networks/f5-azure-arm-templates#50]
## Description
 Per my understanding in order for HA to work, The BIG-IP devices must be able to make API calls over to the Azure environment  over port 443. 

If in fact a requirement then please update the "Deploying the BIG-IP VE in Azure - HA Cluster (Active/Standby)" ReadMe guide "Prerequisites" section to include allowing the needed ports of 443 from the BIG-IP devices over to the Azure environment as I ran into a situation where the communication was failing due to restriction rules setup within the Azure network security group (NSG). Thanks

## Template
f5-azure-arm-templates/supported/ha-avset

## Severity Level

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
This will be fixed in the next release, thanks for the feedback.

**Comment by edwoodjrjr** [comment]
Documented in cloud release 8.
