### ISSUE TITLE
ResourceDeploymentFailure

### ISSUE THREAD

**Issue by jonasnorlund** [F5Networks/f5-azure-arm-templates#51]
## Description
I tried to deploy the "Deploying the BIG-IP VE in Azure - HA Cluster (Active/Standby)" ARM template with BYOL and I got this error. 

***********************************************
"status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMAgentStatusCommunicationError",
        "message": "VM 'xxxxx-f5vm011' has not reported status for VM agent or extensions. Please verify the VM has a running VM agent, and can establish outbound connections to Azure storage."
***********************************************

All the resources has been created and the two VM's are running, but I'm not sure if the Custom script has run? I get status unavailable for the script extension. 

## Template
Deploying the BIG-IP VE in Azure - HA Cluster (Active/Standby)

## Severity Level
Severity: 2

**Comment by edwoodjrjr** [comment]
Hi, can you tell me which Azure region and version of BIG-IP you selected from the template?  We believe this is an Azure issue and have a support case with Microsoft about it.

If the two devices are configured in a cluster, that means the script ran successfully.

**Comment by jonasnorlund** [comment]
Hi, thanks for the quick reply. I have deployed it in West Europe, with the "Good" imag and version 13.0.0300, both VM's are apart of the availability set. Does that mean that it worked?

**Comment by edwoodjrjr** [comment]
Not the availability set.  Log into both BIG-IPs and check that the failover status of one is "Active" and the other "Standby".  This will be in the upper left corner of the GUI, or in the command prompt message.

**Comment by jonasnorlund** [comment]
No both of the nodes are active. None of them is "Standby".

**Comment by edwoodjrjr** [comment]
Usually that means that something was mistyped in the template parameters, or that the password had an illegal character (see prereqs here: https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/ha-avset/new_stack).  You can check /var/log/onboard.log, /var/log/network.log, and /var/log/cluster.log on the BIG-IPs for more details.  Please post them to https://f5cloudsolutions.slack.com where we can help further.

**Comment by jonasnorlund** [comment]
Ok thanks, need to choose another password... ;-) 
I will redeploy the ARM template. 
Thanks for the quick support, please close this issue.

**Comment by jonasnorlund** [comment]
Hmm... it didn't help to remove special chars from the password still the same error. 

VMAgentStatusCommunicationError",
        "message": "VM 'xxxxx-f5vm011' has not reported status for VM agent or extensions. Please verify the VM has a running VM agent, and can establish outbound connections to Azure storage.

**Comment by edwoodjrjr** [comment]
Can you post the contents of /var/log/waagent.log from each BIG-IP please, preferably on our slack channel?
