### ISSUE TITLE
[RFE] Customization of Azure Resource Names

### ISSUE THREAD

**Issue by DonPetry-EY** [F5Networks/f5-azure-arm-templates#54]
## Description
Due to customer naming conventions, we require the ability to provide fully customized names for the various Azure resources which are deployed as part of the ARM templates.  The deploy script should allow us to optionally provide parameter names for each Azure object to ensure it is named according to client requirements.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/cluster/3nic/new_stack/Deploy_via_PS.ps1

**Comment by jsevedge** [comment]
I could potentially see additional support for different prefix/suffix styles, however providing the entire name for each of the resources in each of the templates seems like a limited use case that might not be addressable with these standard supported templates.  Closing out, please feel free to reopen with additional information around the naming convention requirements and/or other suggestions, thanks!
