### ISSUE TITLE
[RFE] Public Mgmt IP should be optional

### ISSUE THREAD

**Issue by DonPetry-EY** [F5Networks/f5-azure-arm-templates#55]
## Description
For security conscious customers with existing private networking, provide the ability to decide if the mgmt IP should be exposed via a Public or Private IP.  Allow the ability to deploy appliances using a private IP only. 

## Template
For bugs, enter the template with which you are experiencing issues below.
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/cluster/3nic/new_stack/Deploy_via_PS.ps1

**Comment by jsevedge** [comment]
@DonPetry-EY We deem this as a "prod_stack", which is essentially the existing networking stack deployment but without any public IP's.  We have some prod_stack templates rolled out already such as here: https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/3nic/prod_stack

**Comment by jsevedge** [comment]
@DonPetry-EY We have not yet considered implementing no public IP only for mgmt in the other "stack" types as a parameter. 
So for right now the options are to deploy our "prod_stack" templates or deploy "new/existing" stack templates and just strip off the public IP from the mgmt ipconfig.

**Comment by jsevedge** [comment]
Production stack templates (available for most deployment options) provide this functionality, removing the IP address post deployment is also a possible option.   Please reopen if neither of those are valid solutions here.
