### ISSUE TITLE
[RFE] Allow vNIC NSG rules to be customized

### ISSUE THREAD

**Issue by DonPetry-EY** [F5Networks/f5-azure-arm-templates#56]
## Description
For customers who deploy appliances to existing subnets which leverage subnet level NSG's, the use of hard coded vNIC level NSG's is redundant and conflicting.  Therefore, requesting template be enhanced to allow customization of vNIC level NSG's so customer can decide which (if any) NSG's should be applied.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/cluster/3nic/new_stack/Deploy_via_PS.ps1

**Comment by jsevedge** [comment]
@DonPetry-EY The thought as of now is customization of NSG rules and/or removing entirely is a post-initial deployment step.  It will not conflict with a subnet level NSG so if stricter rules are applied there it will still apply.

This seems like a valid request however and could potentially be addressed if we introduce an "advanced" parameter as an option.

**Comment by jsevedge** [comment]
Internal ID 1198 filed to officially track this.  Note that this is low priority given the above feedback.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
