### ISSUE TITLE
BUG: unable to login with specified username

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-azure-arm-templates#57]
## Description

Just deployed.  Unable to login with the user "azureuser".  Only able to use "admin".

## Template

https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/v4.4.0.0/supported/ha-avset/new_stack/BYOL/azuredeploy.json

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

workaround is to login as "admin", but unexpected behavior compared to the past.

**Comment by edwoodjrjr** [comment]
Which version of BIG-IP did you choose?  Is there anything funny in /var/log/waagent.log?

Our nightly tests use a non-admin account, and are passing (although they don't use azureuser).  I did test with azureuser before we released and it worked as expected...will try to repro today.

**Comment by chen23** [comment]
Version 13.1.  Using the same password that I used in the previous version of the ARM template.  Contains the following special characters. " (double-quote), $, and ! among other characters.  
```
2018/02/21 07:21:59.238505 ERROR Failed to modify the user 'azureuser': /bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
```

```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "adminUsername": {
      "value": "azureuser"
    },
    "adminPassword": {
      "value": null
    },
    "dnsLabel": {
      "value": "XXX"
    },
    "instanceName": {
      "value": "f5vm01"
    },
    "instanceType": {
      "value": "Standard_DS3_v2"
    },
    "imageName": {
      "value": "Good"
    },
    "bigIpVersion": {
      "value": "13.1.0200"
    },
    "licenseKey1": {
      "value": "XXX"
    },
    "licenseKey2": {
      "value": "XXX"
    },
    "numberOfExternalIps": {
      "value": 1
    },
    "vnetAddressPrefix": {
      "value": "10.0"
    },
    "tenantId": {
      "value": "XXX"
    },
    "clientId": {
      "value": "XXX"
    },
    "servicePrincipalSecret": {
      "value": null
    },
    "managedRoutes": {
      "value": "0.0.0.0/0"
    },
    "routeTableTag": {
      "value": "f5_ha"
    },
    "ntpServer": {
      "value": "0.pool.ntp.org"
    },
    "timeZone": {
      "value": "UTC"
    },
    "restrictedSrcAddress": {
      "value": "*"
    },
    "tagValues": {
      "value": {
        "application": "APP",
        "cost": "COST",
        "environment": "ENV",
        "group": "GROUP",
        "owner": "OWNER"
      }
    },
    "allowUsageAnalytics": {
      "value": "No"
    }
  }
}
```

**Comment by edwoodjrjr** [comment]
Must be the password as I wasn't able to repro.  Please send me your example password via email.

**Comment by chen23** [comment]
Can we reference the following page from the adminPassword description in the docs? https://support.f5.com/csp/article/K2873

**Comment by jsevedge** [comment]
@chen23 Sure, that seems like a good request.  I will add it to the list of items to do for next release.

**Comment by jsevedge** [comment]
@chen23 Just FYI, it is also provided in the prereq of all of the template readmes.  However, adding it to the parameter itself has been added to the list of improvements we could make.
