### ISSUE TITLE
Enhancement: Optional DNS records

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-azure-arm-templates#59]
## Description
Currently the templates require a DNS prefix for Public IP Addresses that is unique per region and global to all subscriptions.  This can create conflicts across accounts that have no relation (i.e. if a user opts to use the "REQUIRED" input w/out modification).

It would nice to have an option / default to not create DNS records to avoid name conflicts.

**Comment by edwoodjrjr** [comment]
The DNS label parameter is the prefix for all objects in the deployment, which is important for preventing conflicts in storage account names (which must be globally unique).  We could remove the default value for it so customers are forced to type something.

**Comment by chen23** [comment]
Removing "REQUIRED" and having a customer enter a real value would be a great start.  To be clear I'm really talking about leaving empty the field in the Public IP Address.

![image](https://user-images.githubusercontent.com/63689/36688442-82812f50-1afa-11e8-9580-e0e6798b9eaa.png)

**Comment by edwoodjrjr** [comment]
Understood, but if we do that then we need to add a parameter for a globally unique value to populate the storage account names with.  Azure doesn't provide a function to return a truly unique value.

**Comment by jsevedge** [comment]
Internal ID 1197 created to officially track this.  Note that this is low priority per reasons mentioned above.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).

Our V2 templates have solved this issue with a uniqueString parameter.
