### ISSUE TITLE
Unable to login to VE created from 4.4.0.0 template

### ISSUE THREAD

**Issue by jim-number2** [F5Networks/f5-azure-arm-templates#60]
## Description
Created 1 VE with new 4.4.0.0 template and entered password for azureuser account.  After Ve was created, I was unable to login as azureuser with defined password.  Since the template does not ask for password verification I thought maybe I mistyped it the first time and created a 2nd VE being very careful on entering the password.  Again, I was unable to login to VE as azureuser with defined password.  I use the same password for F5 test VEs created in Azure Portal without the ARM template and am able to login so the password meets Azure password requirements.  The same password worked with F5 ARM templates prior to 4.4.0.0.

## Template
'Deploying the BIG-IP VE in Azure - Single NIC' - New Network Stack/BYOL V4.4.0.0

## Severity Level
Severity: 2

**Comment by edwoodjrjr** [comment]
Hi, did your password contain any of the characters from this KB: https://support.f5.com/csp/article/K2873

Did the Azure deployment finish successfully?

**Comment by jim-number2** [comment]
Yes…  password contains !  I’ve been using the same password for my customer validation test VEs for several months.  I create 2 last week directly in from Azure Marketplace and the password worked OK.  I just create a new one from Marketplace after opening this ticket and the password no longer works.  Could this be a change from v13.0.0 to v13.1.2?  My previous Marketplace VEs were v13.0.0.

Thanks,

Jim Hart
SP Systems Engineer
j.hart@f5.com<mailto:j.hart@f5.com> | M: 714-886-7861
www.f5.com<http://www.f5.com/> | synthesis.f5.com<https://synthesis.f5.com/>

**Comment by edwoodjrjr** [comment]
It's quite possible that something changed in v13.1.0.2.  Can you verify that removing the "!" solves the issue?

**Comment by jim-number2** [comment]
I created 2 new VEs from Marketplace…  one with azureuser and a password without ! and another with <firstinitial><lastname> as the username and a different non ! password and I can’t login to either one.  This looks more like a v13.1.2 issue and not an ARM template problem

Jim Hart
SP Systems Engineer
j.hart@f5.com<mailto:j.hart@f5.com> | M: 714-886-7861
www.f5.com<http://www.f5.com/> | synthesis.f5.com<https://synthesis.f5.com/>

**Comment by jsevedge** [comment]
Is this still an issue or can this issue be closed out?

**Comment by jsevedge** [comment]
Idle issue, closing.
