### ISSUE TITLE
arm template parameter typo

### ISSUE THREAD

**Issue by jtri** [F5Networks/f5-azure-arm-templates#61]
## Description
Describe the problem you're having or the enhancement you'd like to request.

It looks like there is a typo in the template. The text for arm template parameter `enableNetworkFailover`
says `Enabling failover creates a traditional active/active deployment with traffic groups and mirroring. When failover is disabled, all devices are active; use traffic group none`.  Should this say `active/passive` not `active/active`? Thanks

## Template
For bugs, enter the template with which you are experiencing issues below.
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/cluster/3nic/new_stack
## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Hi, by traditional active/active, we mean multiple traffic groups spread across the BIG-IPs.  This is what network failover enables, in addition to active/standby.  Without network failover, it's config-sync only active/active, without stateful failover.  We should probably add active/standby to the first sentence.
