### ISSUE TITLE
Documentation: routeTableTag

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-azure-arm-templates#62]
## Description

The HA-AVSET documentation for routeTableTag can lead to an incorrect configuration.

Currently the documentation reads:

```
Azure tag value to identify the route tables to be managed by this cluster. For example tag value: myRoute. Example Azure tag: f5_ha:myRoute.
```

The issue is that a customer can enter the literal "f5_ha:myRoute" instead of the expected "myRoute".  This can lead to the failover script failing because it is looking for the wrong value.

## Template
For bugs, enter the template with which you are experiencing issues below.

https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/ha-avset/new_stack

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

**Comment by edwoodjrjr** [comment]
We'll update this to specify that f5_ha is the key and myRoute is the example value.

**Comment by JosephPJordan** [comment]
This change is staged to go out in our next release
