### ISSUE TITLE
Link to Github time zone list from input parameter table

### ISSUE THREAD

**Issue by edwoodjrjr** [F5Networks/f5-azure-arm-templates#63]
## Description
Should link to https://github.com/F5Networks/f5-azure-arm-templates/blob/master/azure-timezone-list.md from the input parameters table on each solution's README.  Currently it points to the local time zone database file on BIG-IP, which is less helpful if you don't have an existing BIG-IP deployed. 

## Template
All ARM templates that have the timeZone parameter (everything but Autoscale WAF).

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by JosephPJordan** [comment]
committed for the next release
