### ISSUE TITLE
Recent change will force a rebuild of all 12.1.x VMs

### ISSUE THREAD

**Issue by strtdusty** [F5Networks/f5-azure-arm-templates#64]
## Description
Commit 4.4.0.1 pulled out the 12.1.2200 image from the examples because of problems you guys are having deploying that version in azure.  It also changed the offer for 12.1.2200 to "f5-big-ip-best" (good/better etc) from "f5-big-ip".  This has broken all of our ARM deployments for 12.1.x.  We are forced to change our "offer."  However, Azure will not let us update an existing VM with the new offer (Resource plan can not be changed).  Our only recourse is to rebuild the VM.

## Severity Level

Severity: 2

**Comment by jsevedge** [comment]
@strtdusty That is correct, we have pulled 12.1.2200 as a version of BIG-IP to deploy until an updated version of 12.1.x  cam be published that resolves the original issue mentioned in the base readme of this repo.

New deployments must us 13.1.0200 in the meantime.

**Comment by strtdusty** [comment]
I understand that I cannot deploy any new VMs with 12.1.2200.  But what is killing me is that I can't run my deployment of existing VMs.   I need to make other changes to our ARM templates (load balancers etc) but this is forcing me to break them apart so that I can avoid deploying any F5 VMs.

**Comment by jsevedge** [comment]
Which F5 ARM template are you using?  Is it being included as a part of a "full stack service" or was it modified to include additional resources?

**Comment by jsevedge** [comment]
Does one of our cluster or autoscale solutions not create the frontend (load balancer, pub IPs) configuration in an expected manner to avoid having to modify the ARM template manually?  I would suggest reviewing the latest templates to see if you can use one of them without modifications so as to continue deploying in a supported fashion.  

As far as 12.1.x support as stated that will be reintroduced to the templates when the new images is available.

**Comment by strtdusty** [comment]
Even if I was using your HA template and wanted to add a new PIP ... I would be blocked right now wouldn't I?  That is essentially what I am trying to do with our templates ... I need to add a new virtual server and, therefore, a new PIP.  

It seems our support has just been dropped for 12.1.x.  My only options are to rebuild or upgrade to 13.

**Comment by jsevedge** [comment]
If you are having issues with existing instances that have already been deployed i would suggest reaching out to F5 Support as they may be able to provide further assistance for that specifically.  For new deployments using ARM templates at this time we do only include v13.1.x in the template, v12.1.x will be added back as mentioned.

The HA template supports deploying up to a configurable number of PIP's.  If more are needed after initial deployment then the appropriate additions in Azure could be made to the external NIC(s) of the BIG-IP as described in the readme for a specific solution, as well as logging into the BIG-IP directly (or using automation) and creating the objects to pass traffic as desired.  The template is meant primarily for bringing the BIG-IP up in a specific desired state based on common use cases, it should then be managed directly.

**Comment by jsevedge** [comment]
12.1.x is now available within the templates, it can be referenced as 12.1.303000
