### ISSUE TITLE
Allow template deployment into different region than resource group

### ISSUE THREAD

**Issue by mikeshimkus** [F5Networks/f5-azure-arm-templates#65]
## Description
Customer would like to create several deployments of the HA-AVSET template in the same resource group, with each template deployed to a different Azure region.

Preferred option is to create a location parameter and if provided, that location is used.  If not provided, default to the resource group's location property.

## Template
All ARM templates.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Internal issue 1185.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
