### ISSUE TITLE
enhancement: f5-cloud-libs from restricted networks

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-azure-arm-templates#66]
## Description
There are customer Azure environments that do not have access to GitHub.  Ideally there should be guidance on retrieving f5-cloud-libs from alternate location (i.e. customer Azure Blob Storage).  Similarly there are cases where retrieval from Azure Blob Storage is permitted and it would be helpful if these files were stored there instead of GitHub.

**Comment by edwoodjrjr** [comment]
Internal issue 1183.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
