### ISSUE TITLE
Azure throughput Speeds are wrong

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-azure-arm-templates#67]
## Description
Information on throughput doesnt match the official K Article

GitHub:
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/azure-bigip-version-matrix.md
Good/Better/Best: 1Gbps, 200Mbps, 25Mbps

K Article:
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/azure-bigip-version-matrix.md
Production licenses support throughput speeds of up to 3 Gbps, 1 Gbps, 200 Mbps, or 25 Mbps.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>
 5. **Severity 5 (Trival)**

**Comment by jsevedge** [comment]
@jmcalalang It looks like you included the github link as both links, i believe the underlying discrepancy is F5 does not publish a 3 Gbps PAYG image and so we cannot offer one in the template.

**Comment by jmcalalang** [comment]
(Fixed the link) that's a bit confusing though since we offer both BYOL and PAYG from the templates. Should there be a note in the description that this is only for PAYG speeds or maybe a different style for BYOL vs PAYG?

Also, if that's the case the v3.3.1.0 note on the Matrix calls out a 5Gbps

**Comment by jsevedge** [comment]
Will fix the 5gbps item, i get what you are saying about 3gbps could be possible if using the BYOL template and matrix does not account for that or call that out in any way.

**Comment by jsevedge** [comment]
This has been resolved as of v5.1.0.0 release.
