### ISSUE TITLE
Supported BIG-IP versions remove Note

### ISSUE THREAD

**Issue by assareh** [F5Networks/f5-azure-arm-templates#68]
## Description
In the Supported BIG-IP versions section, 12.1.3 was added therefore I believe the following note can be removed. 
> NOTE: Due to changes within the Azure environment, only BIG-IP version 13.1.0200 is available (even if you select Latest in the template). We will update the template to include a new BIG-IP v12.1 image as soon as it is available.

## Template
Looks like all or most.

## Severity Level
Severity: 5 (Trivial)

**Comment by jsevedge** [comment]
Good catch, we will remove this from a future release.

**Comment by jsevedge** [comment]
This has been resolved as of v5.1.0.0 release.
