### ISSUE TITLE
Deployment Topologies Missing

### ISSUE THREAD

**Issue by ArtiomL** [F5Networks/f5-azure-arm-templates#69]
## Description
No topology images in: https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/cluster/failover-api/alternate-deployment-topologies.md

## Template
Documentation

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>
5
Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by jsevedge** [comment]
Thanks, This will be resolved in a future release.

**Comment by jsevedge** [comment]
This has been resolved as of v5.1.0.0 release.
