### ISSUE TITLE
documentation: troubleshooting DSC

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-azure-arm-templates#70]
## Description
FYI, saw an issue with a customer where they had an existing UDR on the "internal" subnet that was interfering with DSC communication.  The workaround was to create a /32 route with a nexthop of the self-ip to bypass the subnet route table (x2 for each direction).

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

**Comment by edwoodjrjr** [comment]
Internal issue 1182.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
