### ISSUE TITLE
reconfigure http.iapp loses netmask

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-azure-arm-templates#71]
## Description
When deploying the WAF solutions from the marketplace; if you reconfigure the deployment it will lose the netmask that was applied to the destination.  This is not obvious, the result is that traffic is dropped until you correct the destination mask.  Ideally the http.iapp should recognize that a mask has been applied to the destination and preserve it in the UI.

## Template
For bugs, enter the template with which you are experiencing issues below.

Marketplace WAF template

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity:  4

**Comment by edwoodjrjr** [comment]
Did you reconfigure in basic mode, or advanced?  I tested reconfiguring in advanced mode and it preserved my netmask.  In basic mode, IIRC it applies the template default of 255.255.255.255:

::pool__mask                          {255.255.255.255}

**Comment by chen23** [comment]
basic mode was used.

**Comment by edwoodjrjr** [comment]
If you reconfigure in advanced, the original netmask should be there and be applied.  I think the workaround would be to move the netmask input to basic, but I'm pretty sure that would break backward compatiblity.

Can you tell me what you were tweaking in the iApp that made you want to reconfigure it? Maybe it can be addressed with a variable in the template?

**Comment by chen23** [comment]
The customer wanted to change it from using ALB as the pool to reference the nodes directly

**Comment by chen23** [comment]
If we continue to ship a copy of f5.http; maybe we can modify the input text to add a warning.

```
What IP address do you want to use for the virtual server?
```
to
```
What IP address do you want to use for the virtual server? (WARNING: USE ADVANCED MODE TO MODIFY)
```

**Comment by edwoodjrjr** [comment]
We have 43 variables that are defaulted in advanced mode.  That will probably be too many warnings to add.  

It seems like we may just need to document this behavior everywhere where there's the possibility of reconfiguring a deployment through the UI that was initially done programmatically.  Is that fair?

**Comment by chen23** [comment]
Another option is to explicitly disable strict updates on the iApp and advise against using reconfigure.  Otherwise documentation is the next best alternative.

**Comment by edwoodjrjr** [comment]
Looks like strict updates are already disabled.

**Comment by edwoodjrjr** [comment]
Internal issue 1188.

**Comment by shyawnkarim** [comment]
Closing.

Templates were updated to deploy AS3 instead.
