### ISSUE TITLE
f5.http iapp version

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-azure-arm-templates#72]
## Description
Current version is 1.2.0rc7.  newer versions exist.  Should the templates be updated to leverage the new templates?  Not sure on the impact on the existing install scripts.

## Template
WAF solution templates

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

**Comment by edwoodjrjr** [comment]
I don't see this being much of an issue on the scripts.  However, I think we'd want to make sure that the on-box f5.http had all the nifty features we need first so we can target that, rather than having to onboard the template externally during deployment.

**Comment by chen23** [comment]
I believe that the existing f5.http iApp on box will always be "older", but not 100% sure.

**Comment by edwoodjrjr** [comment]
Looks like the features we needed are present in the 13.1 image.  I will make a note to investigate this for the next update to the WAF solutions.

**Comment by edwoodjrjr** [comment]
Internal issue 1180.

**Comment by shyawnkarim** [comment]
Closing. [AS3](https://github.com/F5Networks/f5-appsvcs-extension) is now used for configuring a BIG-IP system.
