### ISSUE TITLE
support for Azure Availability Zones

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-azure-arm-templates#74]
## Description
Customer inquired whether ARM templates will support Azure Availability Zones in addition to Azure Availability Sets.  Apparently they are mutually exclusive.  https://azure.microsoft.com/en-us/global-infrastructure/availability-zones/ 

## Severity Level

Severity: 5

**Comment by ak-cw** [comment]
Any updates on this? Azure is moving forward to Availabilty Zones as best practice for deployments.

**Comment by edwoodjrjr** [comment]
Created internal issue #893 for tracking this request.  Will update here when we have more information.

**Comment by jsevedge** [comment]
Internal ID 893 was completed and released to master in the v7.x release.
