### ISSUE TITLE
Allow BIG-IP creation from specific VHD image

### ISSUE THREAD

**Issue by HidingUnderMyRock** [F5Networks/f5-azure-arm-templates#75]
## Description
Provide the ability to specify a specific VHD image to deploy the BIG-IP.  This will allow deployment from unreleased images for testing, or from specific images that are part of a standard deployment instead of being forced to the latest build.

## Template
Any of the templates under f5-azure-arm-templates

## Severity Level

Severity: 5 (Trivial)

**Comment by jsevedge** [comment]
Understood, we have had a couple requests along these lines.  It is in our backlog.

**Comment by jsevedge** [comment]
This feature has now been released as of v5.1.0.0, the customImage parameter allows for this.

**Comment by HidingUnderMyRock** [comment]
Thanks!
