### ISSUE TITLE
Failover-api temple issue for Azure China deployment 

### ISSUE THREAD

**Issue by hiruy23** [F5Networks/f5-azure-arm-templates#76]
## Description
We have ordered F5 licence for Azure China and trying to deploy F5 using the failover templet 

## Template
f5-azure-arm-templates/supported/cluster/failover-api/new_stack/BYOL/

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <2>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
This template is not yet supported in Azure China.  See https://github.com/F5Networks/f5-cloud-libs-azure/issues/1

**Comment by csahut** [comment]
You can take the template from github, modify it so you use your own image instead of the marketplace one, upload the VE image to a storage account in Azure China, create an image from it, and reference this image in your deployment. I did it and have a 3nic Active/Standby cluster on 13.1.002 running smoothly in Azure China.

**Comment by csahut** [comment]
@edwoodjrjr no, did I miss something? If I correctly understood the failover mechanism, there is nothing related to Azure API calls. I don't use any mechanism based on tags or UDRs. I have an ALB+ILB in front of the cluster so no moving IPs between nodes. Why should the BigIPs be aware they are on Azure China?

**Comment by csahut** [comment]
Indeed, my template is not exactly this one. It's the BYOL version of /supported/cluster/3nic/existing_stack (v4.4.0.0 to be precise).

**Comment by hiruy23** [comment]
failover-api templet is the one we are trying to get working in azure china .  @edwoodjrjr  can we have a call and work together . We have our MS azure china team to help us support if needed . Once we get this working you can publish it to supported list for azure china . I am sure other customers are going to start asking for this .

**Comment by edwoodjrjr** [comment]
@hiruy23 The code is not yet ready and won't be supported until we publish it here.  I recommend working with F5 professional services on this as they can work with us to get you going.
