### ISSUE TITLE
deploy_via_bash.sh does not support azure cli 2.0 

### ISSUE THREAD

**Issue by depperson** [F5Networks/f5-azure-arm-templates#77]
## Description
Azure CLI command changed from "azure" in 1.0 to "az" in 2.0.  By default 2.0 is installed on MacOS when using "brew install azure-cli".  The deploy_via_bash.sh example only supports azure cli 1.0.  

## Template
All templates. 

## Severity Level
Severity: 4

I will send over a PR for the changes.

**Comment by jsevedge** [comment]
Internal issue created to track this request.

**Comment by jsevedge** [comment]
Clarification: Issue ID is 252

**Comment by jsevedge** [comment]
Duplicate #123 requested the same support.

**Comment by wduongf5** [comment]
This issue is resolved in release v7.0.1.0.
