### ISSUE TITLE
managing autoscale deployed BIG-IPs

### ISSUE THREAD

**Issue by depperson** [F5Networks/f5-azure-arm-templates#79]
## Description
How do I find connection details for BIG-IPs deployed through the autoscale template?  There are no VMs deployed? 

The answer is that the VMs are deployed into an Azure VMSS (Virtual Machine Scale Set) and accessing them goes through NATs automatically set up in the ALB under ext-alb -> Inbound NAT rules. 

Please document this in the autoscale template(s). 

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/solutions/autoscale/ltm/new_stack#post-deployment-application-configuration

## Severity Level
4

**Comment by jsevedge** [comment]
Hello depperson, in all our templates we document how to access SSH as well as the GUI in the deployment outputs.  If deploying via scripting those are in the response when the deployment completes.  If deploying via the portal those can be found by navigating to the resource group and selecting the deployment pane.  Once there select the deployment by name and there should be a plane for outputs.

**Comment by depperson** [comment]
The template I linked does not reference how to SSH to the deployed BIG-IPs or mention at all the ALB inbound NAT rules that make it work.

**Comment by jsevedge** [comment]
The deployment output does provide the connection info for the first VM in the scale set. However i do agree that the readme should call out more details on how to connect.

**Comment by jsevedge** [comment]
Closing the loop, the configuration example was updated to include NAT ports: https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/autoscale/waf/via-lb/1nic/new-stack/payg#configuration-example
