### ISSUE TITLE
bad password if "$" is used - fail licensing BYOL

### ISSUE THREAD

**Issue by dabungis** [F5Networks/f5-azure-arm-templates#8]
I’m launching various supported and experimental templates and noticed that the licensing is not working. I believe this password issue affects all.

Troubleshooting:
I checked /var/log/onboard.log and see that auth is failing. I then grepped for “license” and found the main call pointing to a file:///config/cloud/passwd. Within this file was my password I entered. However, noticed it clipped everything pass the “$” as if it was a word or end-of-string boundary.
 
Example “azureuser”
Template provided password entered during launch = 543xyz*$12345
 
This will get converted to...
Password after launch = 543xyz*
 
As a result, azureuser has a bad password when trying to license.
 
I deleted my resource groups, started all over with a different password such as 543xyz*12345 and all works fine.

**Comment by jsevedge** [comment]
This is resolved as of the v2.0.0.0 tagged release which was merged into master.  Please re-open if you run into it on this release forward, thanks.
