### ISSUE TITLE
Errors in failover when primary self IP address is a substring of secondary IP 

### ISSUE THREAD

**Issue by edwoodjrjr** [F5Networks/f5-azure-arm-templates#80]
## Description
When deploying the failover-api template in an existing/prod stack, if you specify the self IP start address as "192.168.0.10" and the external secondary start address as "192.168.0.100", when failover occurs the failoverProvider.js script will attempt to move both IP configs, resulting in an error:

"Network interface ha-avset-ext0 must have one or more IP configurations."

IP config matching logic in failoverProvider.js should be updated to use an equality operator rather than includes().

## Template
failover-api (existing/prod stack)

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 4

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by jsevedge** [comment]
This was resolved in v5.2.0.0
