### ISSUE TITLE
RFE: Improve failover-api handling of rapid failover events 

### ISSUE THREAD

**Issue by edwoodjrjr** [F5Networks/f5-azure-arm-templates#81]
## Description
In the failover-api templates, when failover is triggered within 5 minutes of a previous failover event that is still in a running or failed state, failoverProvider.js is not called again.  Users must then manually trigger failover to move Azure resources to the active BIG-IP. 

One suggestion is to use the asynchrounous Node SDK calls to get a task ID for updating NICs, and write that ID to the statusdb file while the task is running.  If that ID is present when failover is triggerd from another device, that device will track the task status and then submit its NIC updates after it is complete.

Another possible solution would be to create an agent to reconcile CM status to Azure configuration, using iCall or cron jobs, for example.  This would add a bit more latency to the already-long failover process.

## Template
cluster/failover-api

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 4

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by jmcalalang** [comment]
@edwoodjrjr 

is there a chance to chat with you today/tomorrow about this? we have a large customer that experienced this last week and are looking for ways to continue with HA but have the check implemented so this "Split Brain" scenario doesn't persist. 

@yossi-r

**Comment by jsevedge** [comment]
@jmcalalang Absolutely, will work with you to schedule some time to discuss.

**Comment by edwoodjrjr** [comment]
Closing this issue, it was resolved in release v5.0.0.0.
