### ISSUE TITLE
Assigning Public IP to virtual server prod_stack template

### ISSUE THREAD

**Issue by pdemro** [F5Networks/f5-azure-arm-templates#82]
## Description
Wondering if there is some guidance on assigning/routing a public IP address to a Virtual Server in F5. 

I have assigned a public IP to the external VLAN NIC on the secondary IP associated with my Virtual Server.  

Any clue to next steps would be appreciated.  Do I need an Azure gateway on the subnet?  Is there some additional configuration in the F5?

## Template
prod_stack

## Severity Level
This is a lab environment we are using to prototype potential use in production

**Comment by jsevedge** [comment]
Hello @pdemro ,  your issue states you are using a prod_stack template.  "prod_stack" options specifically remove any public IP's from the deployment, it sounds like what you want is our "existing_stack" options which include public IP's for both mgmt and dataplane traffic.

**Comment by pdemro** [comment]
Thank you for the quick reply @jsevedge!  Is there any way to convert what I have to allow public IPs?  Would like to avoid rebuilding the F5 if possible

**Comment by pdemro** [comment]
I used the Deploy to Azure button on this site earlier this week:

![image](https://user-images.githubusercontent.com/5431128/41467101-20f2cb1c-7073-11e8-8216-b051799f8533.png)

https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/3nic/prod_stack

**Comment by pdemro** [comment]
After doing some testing today it looks like this configuration is very simple using the prod_stack template.  Simply add a public IP to the secondary IP on the NIC associated with the virtual server.

I was having issues originally because blocking/packet interference from my company network.
