### ISSUE TITLE
Clarification on the BIG-IP VE in Azure - HA Cluster (Active/Standby) Template

### ISSUE THREAD

**Issue by ITGem01** [F5Networks/f5-azure-arm-templates#83]
## Description
Describe the problem you're having or the enhancement you'd like to request.
I am not sure if this is the correct forum to ask this question. Regarding this statement, 

"This template supports creating up to 20 additional public/private IP address configurations for the external 'application' NIC to be used for passing traffic to BIG-IP virtual servers."  

I need to know if the template limits the number of VIPs that can be created to 20. 

## Template
For bugs, enter the template with which you are experiencing issues below.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>
5
Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by jsevedge** [comment]
@ITGem01 Hello, the template allows you to deploy up to 20 ip address configurations to be used for app services automatically.  You can however deploy more manually post-deployment.  The readmes provide some example instructions on what needs to be created, such as this readme [here](https://github.com/F5Networks/f5-azure-arm-templates/tree/v5.1.0.0/supported/cluster/failover-api/new_stack#adding-additional-public-ip-addresses-to-the-deployment)

**Comment by ITGem01** [comment]
Thanks. That is helpful. One more question. Do the UDRs have to be customized to send traffic to the F5s as in the case of route domains.

**Comment by jsevedge** [comment]
It is not quite the same as route domains and whether you need to use them depends on the use case.  If you need to route traffic through the BIG-IP(s) or act as a network function in any way then UDR's might be required.  

If using the cluster/failover-api solution it can update UDR's to ensure it is pointed at the active BIG-IP.

**Comment by jsevedge** [comment]
Closing this issue out, if you have further questions please feel free to reopen or open a new issue.
