### ISSUE TITLE
Use Standard LB SKU in all-protocol/all-port ILB deployment

### ISSUE THREAD

**Issue by edwoodjrjr** [F5Networks/f5-azure-arm-templates#85]
## Description
Need to switch to the Standard Azure load balancer SKU when all-protocol ILB is selected.  Right now the template still uses the Basic SKU with the ILB resource defined with preview syntax, which can fail for customers who did not sign up for the all-protocol preview.

## Template
failover-lb

## Severity Level
Severity: 4

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by ecc256** [comment]
> can fail for customers who did not sign up for the all-protocol preview.

Where do I sign up for the "all-protocol ILB" preview exactly?
It’s not listed [here](https://azure.microsoft.com/en-us/services/preview/). I’ve tried to Google it, all results point back to F5Networks/f5-azure-arm-templates

**Comment by edwoodjrjr** [comment]
This is covered in https://github.com/F5Networks/f5-azure-arm-templates/issues/85
