### ISSUE TITLE
Marketplace Big-IQ v6.0 in Azure fails

### ISSUE THREAD

**Issue by cpufxr33** [F5Networks/f5-azure-arm-templates#86]
## Description
I can bring up a Big-IQ web browser but I cannot login with the credentials I put in from the Marketplace.

My deployment fails with this error

  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "OSProvisioningTimedOut",
        "message": "OS Provisioning for VM 'xxxxxxxxx' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later."
      
## Template
For bugs, enter the template with which you are experiencing issues below.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 .

**Comment by jsevedge** [comment]
@cpufxr33 I was able to successfully deploy a BIG-IQ from marketplace and login to the GUI.  Are you able to log in via ssh?

**Comment by cpufxr33** [comment]
Hello James,

No, I get Access denied with my credentials.

I’ve deployed it 5 times with different VM sizes and continue to get the same time out error. Maybe it’s something in the sysprep reading this.
https://social.msdn.microsoft.com/forums/azure/en-us/8dcef022-7e45-4b40-ad30-4434a3c3ce0b/virtual-machine-provisioning-timeout




Thanks,
Derrick

Derrick Washington
IAM Network Engineer (VA Contractor)
Network Support for IAM – TO61

[cid:image001.png@01D1DB62.26BD1960][cid:image002.png@01D2523F.2AD22C80]

3877 Fairfax Ridge Road, Suite 205C
Fairfax, Virginia 22030
Office: 703.268.5525 x156
Mobile: 571.436.3779
derrick.washington1@va.gov<mailto:eduardo.laguerre@va.gov>
dwashington@technatomy.com<mailto:elaguerre@technatomy.com>
www.technatomy.com<http://www.technatomy.com/>
vaww.iam.va.gov<../../../../../slance/Desktop/IAM_2016%20MASTER/Welcome%20Package/Signature%20Block/vaww.iam.va.gov>

**Comment by jsevedge** [comment]
Are you using the same password each time?  My first thought would be to check if the password used contains characters described in this support article: https://support.f5.com/csp/article/K2873

**Comment by cpufxr33** [comment]
No none of those characters are being used. It would give me an error as I’m setting up the USN\PW in the deployment wizard.

Thanks,
Derrick

Derrick Washington
IAM Network Engineer (VA Contractor)
Network Support for IAM – TO61

[cid:image001.png@01D1DB62.26BD1960][cid:image002.png@01D2523F.2AD22C80]

3877 Fairfax Ridge Road, Suite 205C
Fairfax, Virginia 22030
Office: 703.268.5525 x156
Mobile: 571.436.3779
derrick.washington1@va.gov<mailto:eduardo.laguerre@va.gov>
dwashington@technatomy.com<mailto:elaguerre@technatomy.com>
www.technatomy.com<http://www.technatomy.com/>
vaww.iam.va.gov<../../../../../slance/Desktop/IAM_2016%20MASTER/Welcome%20Package/Signature%20Block/vaww.iam.va.gov>

**Comment by cpufxr33** [comment]
It must be failing before the USN\PW is completed in the script since I can’t SSH to it.

Thanks,
Derrick

Derrick Washington
IAM Network Engineer (VA Contractor)
Network Support for IAM – TO61

[cid:image001.png@01D1DB62.26BD1960][cid:image002.png@01D2523F.2AD22C80]

3877 Fairfax Ridge Road, Suite 205C
Fairfax, Virginia 22030
Office: 703.268.5525 x156
Mobile: 571.436.3779
derrick.washington1@va.gov<mailto:eduardo.laguerre@va.gov>
dwashington@technatomy.com<mailto:elaguerre@technatomy.com>
www.technatomy.com<http://www.technatomy.com/>
vaww.iam.va.gov<../../../../../slance/Desktop/IAM_2016%20MASTER/Welcome%20Package/Signature%20Block/vaww.iam.va.gov>

**Comment by cpufxr33** [comment]
James,

I have a colleague deploying it to see if it’s something with my permissions or it’s in our Azure portal.

Thanks for reaching out.

Thanks,
Derrick

Derrick Washington
IAM Network Engineer (VA Contractor)
Network Support for IAM – TO61

[cid:image001.png@01D1DB62.26BD1960][cid:image002.png@01D2523F.2AD22C80]

3877 Fairfax Ridge Road, Suite 205C
Fairfax, Virginia 22030
Office: 703.268.5525 x156
Mobile: 571.436.3779
derrick.washington1@va.gov<mailto:eduardo.laguerre@va.gov>
dwashington@technatomy.com<mailto:elaguerre@technatomy.com>
www.technatomy.com<http://www.technatomy.com/>
vaww.iam.va.gov<../../../../../slance/Desktop/IAM_2016%20MASTER/Welcome%20Package/Signature%20Block/vaww.iam.va.gov>

**Comment by jsevedge** [comment]
One other thought on this, are you by chance deploying into an existing VNET that is using custom DNS?

**Comment by cpufxr33** [comment]
Yes


Thanks,
Derrick

Derrick Washington
IAM Network Engineer (VA Contractor)
Network Support for IAM – TO61

[cid:image001.png@01D1DB62.26BD1960][cid:image002.png@01D2523F.2AD22C80]

3877 Fairfax Ridge Road, Suite 205C
Fairfax, Virginia 22030
Office: 703.268.5525 x156
Mobile: 571.436.3779
derrick.washington1@va.gov<mailto:eduardo.laguerre@va.gov>
dwashington@technatomy.com<mailto:elaguerre@technatomy.com>
www.technatomy.com<http://www.technatomy.com/>
vaww.iam.va.gov<../../../../../slance/Desktop/IAM_2016%20MASTER/Welcome%20Package/Signature%20Block/vaww.iam.va.gov>

**Comment by cpufxr33** [comment]
James,
I think we found the issue in the logs. It may be a Azure fabric issue or DNS. It stays in a continuously loop until it times out. It should only take about 15-15 mins to deploy, not 40 mins as it’s taking now.

Thanks,
Derrick

Derrick Washington
IAM Network Engineer (VA Contractor)
Network Support for IAM – TO61

[cid:image001.png@01D1DB62.26BD1960][cid:image002.png@01D2523F.2AD22C80]

3877 Fairfax Ridge Road, Suite 205C
Fairfax, Virginia 22030
Office: 703.268.5525 x156
Mobile: 571.436.3779
derrick.washington1@va.gov<mailto:eduardo.laguerre@va.gov>
dwashington@technatomy.com<mailto:elaguerre@technatomy.com>
www.technatomy.com<http://www.technatomy.com/>
vaww.iam.va.gov<../../../../../slance/Desktop/IAM_2016%20MASTER/Welcome%20Package/Signature%20Block/vaww.iam.va.gov>

**Comment by cpufxr33** [comment]
The message you tried to open is protected with Information Rights Management and can be opened using Microsoft Office Outlook 2010 or the standard version of Outlook Web App. Download a free trial of Microsoft Office Outlook from http://go.microsoft.com/fwlink/?LinkID=147091&clcid=0x409.

**Comment by jsevedge** [comment]
I believe this is related to custom DNS, which is a known issue affecting BIG-IP deployments.  I believe it could also be what is causing your BIG-IQ deployment to fail.  If you deploy into a VNET without custom DNS does it succeed?

**Comment by cpufxr33** [comment]
Thanks James. This is the Big-IQ log.

Thanks,
Derrick

Derrick Washington
IAM Network Engineer (VA Contractor)
Network Support for IAM – TO61

[cid:image001.png@01D1DB62.26BD1960][cid:image002.png@01D2523F.2AD22C80]

3877 Fairfax Ridge Road, Suite 205C
Fairfax, Virginia 22030
Office: 703.268.5525 x156
Mobile: 571.436.3779
derrick.washington1@va.gov<mailto:eduardo.laguerre@va.gov>
dwashington@technatomy.com<mailto:elaguerre@technatomy.com>
www.technatomy.com<http://www.technatomy.com/>
vaww.iam.va.gov<../../../../../slance/Desktop/IAM_2016%20MASTER/Welcome%20Package/Signature%20Block/vaww.iam.va.gov>

**Comment by cpufxr33** [comment]
James,

We’re having an issue with the template you fixed for us (Jeremiah Fowler).

Can you tell us in this error log where the blob.core.windows.net file is located in the script

Thanks,
Derrick

Derrick Washington
IAM Network Engineer (VA Contractor)
Network Support for IAM – TO61

[cid:image001.png@01D1DB62.26BD1960][cid:image002.png@01D2523F.2AD22C80]

3877 Fairfax Ridge Road, Suite 205C
Fairfax, Virginia 22030
Office: 703.268.5525 x156
Mobile: 571.436.3779
derrick.washington1@va.gov<mailto:eduardo.laguerre@va.gov>
dwashington@technatomy.com<mailto:elaguerre@technatomy.com>
www.technatomy.com<http://www.technatomy.com/>
vaww.iam.va.gov<../../../../../slance/Desktop/IAM_2016%20MASTER/Welcome%20Package/Signature%20Block/vaww.iam.va.gov>

**Comment by jsevedge** [comment]
Hello Derrick,
    Is this related to the BIG-IQ issue.  If i recall that was an update for the BIG-IP failover/via-api solution.

**Comment by cpufxr33** [comment]
Files for Failover

Thanks,
Derrick

Derrick Washington
IAM Network Engineer (VA Contractor)
Network Support for IAM – TO61

[cid:image001.png@01D1DB62.26BD1960][cid:image002.png@01D2523F.2AD22C80]

3877 Fairfax Ridge Road, Suite 205C
Fairfax, Virginia 22030
Office: 703.268.5525 x156
Mobile: 571.436.3779
derrick.washington1@va.gov<mailto:eduardo.laguerre@va.gov>
dwashington@technatomy.com<mailto:elaguerre@technatomy.com>
www.technatomy.com<http://www.technatomy.com/>
vaww.iam.va.gov<../../../../../slance/Desktop/IAM_2016%20MASTER/Welcome%20Package/Signature%20Block/vaww.iam.va.gov>

From: Washington, Derrick L. (Technatomy)
Sent: Monday, July 23, 2018 2:13 PM
To: F5Networks/f5-azure-arm-templates <reply@reply.github.com>; F5Networks/f5-azure-arm-templates <f5-azure-arm-templates@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [EXTERNAL] Re:F5 Big-IP HA Cluster

James,

We’re having an issue with the template you fixed for us (Jeremiah Fowler).

Can you tell us in this error log where the blob.core.windows.net file is located in the script

Thanks,
Derrick

Derrick Washington
IAM Network Engineer (VA Contractor)
Network Support for IAM – TO61

[cid:image001.png@01D1DB62.26BD1960][cid:image002.png@01D2523F.2AD22C80]

3877 Fairfax Ridge Road, Suite 205C
Fairfax, Virginia 22030
Office: 703.268.5525 x156
Mobile: 571.436.3779
derrick.washington1@va.gov<mailto:eduardo.laguerre@va.gov>
dwashington@technatomy.com<mailto:elaguerre@technatomy.com>
www.technatomy.com<http://www.technatomy.com/>
vaww.iam.va.gov<../../../../../slance/Desktop/IAM_2016%20MASTER/Welcome%20Package/Signature%20Block/vaww.iam.va.gov>

**Comment by kbetts-stratumtech** [comment]
I am running into this same issue. I can deploy the LTM on a vnet with default DNS, but not on a vnet with custom DNS. Is there a specialized template that can be used?

**Comment by JeffGiroux** [comment]
My customer is hitting same issue. Is there a workaround?

**Comment by carpedm13** [comment]
@JeffGiroux  
I was able to get a deployment successfully working by configuring the individual NIC with the default deployment of Azure DNS at 168.63.129.16.
Deployed via ARM adding the following to the Network Interface Resource Properties

`"dnsSettings": {
        "dnsServers": [
            "168.63.129.16"
        ]
}`
This allowed me to get the device functional. I was able to change the DNS back to inherited from the VNET after deployment, and successfully login.

**Comment by jsevedge** [comment]
To summarize this thread, BIG-IQ may run into provisioning issue when using custom DNS.  To work around this in the template you can add `"dnsSettings": { "dnsServers": [ "168.63.129.16" ] }` to the MGMT nic (which applies to both BIG-IP and BIG-IQ affected version): https://github.com/F5Networks/f5-azure-arm-templates/blob/master/experimental/bigiq/licenseManagement/standalone/2nic/existing-stack/byol/azuredeploy.json

To track templates using a fixed version of BIG-IQ and/or adding workaround into the BIG-IQ template directly, ID 1193 created for that specifically.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
