### ISSUE TITLE
RFE: write template version to big-ip for qkview

### ISSUE THREAD

**Issue by depperson** [F5Networks/f5-azure-arm-templates#87]
## Description
We can't tell what version of the template someone used by just looking at the BIG-IP. 

Please write the template details to a file on BIG-IP that is collected by qkview, such as /var/log/cloud/template_details.log 

## Template
All templates.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

**Comment by jsevedge** [comment]
Internal ID 1196 created to track this.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
