### ISSUE TITLE
Clarification on UDR configuration

### ISSUE THREAD

**Issue by ecc256** [F5Networks/f5-azure-arm-templates#89]
## Description
Not a bug, looking for clarification on UDR configuration only.

## Template
Template [Deploying the BIG-IP VE in Azure - HA Cluster (Active/Standby)](https://github.com/F5Networks/f5-azure-arm-templates/tree/v5.2.0.0/supported/failover/same-net/via-api/n-nic/existing-stack/byol#post-deployment-configuration)
Paragraph [Customizing the Next Hop of Azure User-Defined Routes](https://github.com/F5Networks/f5-azure-arm-templates/tree/v5.2.0.0/supported/failover/same-net/via-api/n-nic/existing-stack/byol#customizing-the-next-hop-of-azure-user-defined-routes)
suggests using **managedRoutes** to update **tagged** UDRs on failover event to point to active BIG-IP VE **local** Self IP.
Why **floating** Self IP cannot be used instead (or not recommended)?
No UDRs update is needed on failover event then…

## Severity Level
Severity: null

**Comment by jsevedge** [comment]
@ecc256 Floating self IP's can actually be used, and are supported in the latest release.  However one of the reasons UDRs are preferred is it only takes 5 seconds or so to move a UDR via API call as opposed to 2+ minutes to move a ip configuration on a NIC (which would correspond to a floating self IP).  Improving the time to move ip configuration objects is something we have made Microsoft aware of and are actively working with them on.

**Comment by ecc256** [comment]
James,
Got it,
Thanks a lot for clarification!
