### ISSUE TITLE
password that starts with "#" will not allow azureuser to login

### ISSUE THREAD

**Issue by dabungis** [F5Networks/f5-azure-arm-templates#9]
Various templates. Entering a user password that begins with "#" (no quotes) will essentially break login. This is a valid password on a normal F5 to begin with #. However, entering # in the Azure Template wizard will result in the azureuser NOT being able to login. There is no way to recover password.

This seems like an Azure issue. However, is there something in the template that can check and verify that the password doesn't start with "#" then error to user?

**Comment by seattlevine** [comment]
Can you give us one of the specific templates with this issue and tell us which branch/tag you are using.

**Comment by dabungis** [comment]
Probably all templates as I have run into this issue in the past too. I just now tried the supported 1nic template for standalone. Below is my test password, tags, and path to github template.

#abcABC123123


https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/1nic

"{\"environment\":\"ENV\",\"application\":\"APP\",\"cost\":\"COST\",\"group\":\"GROUP\",\"owner\":\"OWNER\"}"

Azure shows successful deployment. I can access the web GUI login page, but I get login failed when attempting to login with azureuser and password provided above. If I use something that does NOT start with "#", then azureuser works successfully.

**Comment by jsevedge** [comment]
Hi dabungis,
     At this time based on testing in the recent past we believe that this is a problem with Azure's handling of these special characters within the template once it reaches the custom script extension.  We will add a note in each of the readme's to specify characters that should not be used in the password field in the interim until a resolution can be reached.
