### ISSUE TITLE
customMetrics/F5_TMM_CPU' is not supported for resource - dns autoscale

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#91]
## Description
Hi, testing the new 1nic DNS autoscale LTM template. I tried selecting TMM throughput as a scaling event, but I received an error. I then created a new template deployment and chose CPU this time, but I still received an error. The actual F5 instances to indeed boot up, they add themselves to my GTM pool, and everything else appears to be working. Why does the Azure template say it failed? What else is broken? Does this mean my autoscale triggers didn't create?

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/autoscale/ltm/via-dns/1nic/new-stack/bigiq

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 3

**Comment by jsevedge** [comment]
If you take a look at /var/log/cloud/azure/install.log does anything jump out?  If not feel free to provide the (scrubbed) log here.

If that log does not exist check stdout or stderr in the same location.

**Comment by jsevedge** [comment]
This issue has been resolved with the release tagged v5.3.1.0.
