### ISSUE TITLE
RFE: Support for Azure Network Acceleration (NA)

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/f5-azure-arm-templates#92]
## Description
Request from customer to support Azure Network Acceleration (NA).
Most likely this support should be done for High Perf VEs to go beyond the 10Gbps.
https://azure.microsoft.com/en-us/blog/azure-networking-announcements-for-ignite-2017/

## Severity Level

Severity: 5

**Comment by ArtiomL** [comment]
Based on:
https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli

NA is supported for`CentOS v7.4` or greater.
Seems this needs to be a wider effort, as TMOS v14.0 runs `CentOS v6.8`.

**Comment by jmcalalang** [comment]
+1 I have a customer name that would like this feature as well, also I do have the RM for it if needed.

**Comment by jsevedge** [comment]
This is an improvement in the BIG-IP VE image itself, tracked via internal requirement 0003076.  The templates support the latest BIG-IP images, so once the high-per image is available it will be made available in the templates (even before that if you use the customImage parameter).

Closing this out, please feel free to reopen or open a new issue if further questions arise..
