### ISSUE TITLE
url in readme goes to a 404

### ISSUE THREAD

**Issue by mycahb2** [F5Networks/f5-azure-arm-templates#93]
## Description
Describe the problem you're having or the enhancement you'd like to request.

404 error when clicking to follow url under configuring management port.

Found in:
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/autoscale/ltm/via-lb/1nic/existing-stack/payg/README.md#changing-the-big-ip-configuration-utility-gui-port
May be in other readme's as well.

404 Link:
https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-ve-setup-msft-azure-12-0-0/2.html#GUID-3E6920CD-A8CD-456C-AC40-33469DA6922E

## Severity Level

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by jsevedge** [comment]
Thanks @mycahb2 , we will resolve this in a future release

**Comment by jsevedge** [comment]
This is being tracked internally as ID 557, it is targeted for the upcoming release.

**Comment by jsevedge** [comment]
Resolved in v5.4.0.0 release.
