### ISSUE TITLE
Deploying BIG-IP using v5.3.2.0 templates failed with validation errors.

### ISSUE THREAD

**Issue by mototwister** [F5Networks/f5-azure-arm-templates#94]
## Description
Deploying BIG-IP using v5.3.2.0 templates failed with validation errors.

## Template
Supported v5.3.2.0 templates

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by ArtiomL** [comment]
Hi,

Please specify the exact template (with links), validation error text and deployment method (CLI / portal / Terraform / other).

Thanks.

**Comment by mototwister** [comment]
Hi,
I found the error when using the following template, but looks like that all f5 templates have the same situation according to my customer.  
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/3nic/new-stack

Attached the error message.

![screen shot 2018-09-20 at 18 34 44](https://user-images.githubusercontent.com/19423344/45809849-39ada400-bd04-11e8-9004-46469a953396.png)

Thanks for your help!

**Comment by jsevedge** [comment]
Did you happen to not fill in the parameter ‘dnsLabel’, if it is left blank it will result in an error similar to the above.

**Comment by mototwister** [comment]
You are right. If 'dnslabel' is fill out at first, that error doesn't show up.

**Comment by jsevedge** [comment]
Ok cool, closing this issue out since that resolved it.
