### ISSUE TITLE
I would like to have support to IPv6 addresses on Internal and External Interfaces.  I tried entering valid IPv6 IPs during template deployment into an Azure IPv6 supporing VNet (Preview feature) but it failed. F5 seems to be validating IP addresses as only v4 CIDR notated.

### ISSUE THREAD

**Issue by stdistef** [F5Networks/f5-azure-arm-templates#95]
## Description
IPv6 Address Support for Internal and External interfaces

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol

## Severity Level
Medium based on a workaround to use PowerShell to modify after deployed as IPv4, which has yet to be successful.
Severity: 3

**Comment by smooth-alg** [comment]
thanks for reporting.  For help with roadmap prioritization, would this be a dual stack (IPV4 and IPV6) or just IPV6? What template/deployment type are you interested in?

**Comment by stdistef** [comment]
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol

**Comment by smooth-alg** [comment]
thank you!

**Comment by jmcalalang** [comment]
@smooth-alg sm is there a priority assigned to this already?

**Comment by edwoodjrjr** [comment]
Internal issue 1177.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
