### ISSUE TITLE
Password not being set

### ISSUE THREAD

**Issue by rellington71** [F5Networks/f5-azure-arm-templates#96]
## Description
Describe the problem you're having or the enhancement you'd like to request.

I've tried numerous times to deploy this ARM template and no matter what I choose the password to be it doesn't set it and I'm left with an appliance which I cannot log into. I've also tried all of the standard F5 default user/pass combinations.

Here are the parameters I'm using (I'll change the password so I can paste it here):

        "authenticationType": {
            "value": "password"
        }, 
        "adminPasswordOrKey": {
            "value": "Zb27esQ9nDZb27esQ9nD"
        }, 

## Template
Standalone 2-nic existing stack supported

## Severity Level
2

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by namhly** [comment]
Hello,

Could you tell me what template have you tried? 
I used your supplied password to deploy this template and it was successful:
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/standalone/2nic/existing-stack/payg/azuredeploy.json

Here are the statuses of deployed VM and scripts:

{
    "id": "xxxxxxxx",
    "operationId": "xxxxxx",
    "properties": {
      "provisioningOperation": "Create",
      "provisioningState": "Succeeded",
      "timestamp": "2018-10-19T15:51:59.8698189Z",
      "duration": "PT3M42.2364398S",
      "trackingId": "xxxxxxxxx",
      "statusCode": "OK",
      "targetResource": {
        "id": "xxxxxx",
        "resourceType": "Microsoft.Compute/virtualMachines/extensions",
        "resourceName": "f5vm01/start"
      }
    }
  },
  {
    "id": "xxxxxx",
    "operationId": "xxxxxx",
    "properties": {
      "provisioningOperation": "Create",
      "provisioningState": "Succeeded",
      "timestamp": "2018-10-19T15:48:17.1322492Z",
      "duration": "PT5M4.4086836S",
      "trackingId": "xxxzxzx",
      "statusCode": "OK",
      "targetResource": {
        "id": "xxxxx",
        "resourceType": "Microsoft.Compute/virtualMachines",
        "resourceName": "f5vm01"
      }
    }
  }

Thanks,

**Comment by namhly** [comment]
Since we couldn't reproduce the error and haven't heard from you for a month, we will close this issue.
Thanks.
