### ISSUE TITLE
F5 Code Change

### ISSUE THREAD

**Issue by kantkrish** [F5Networks/f5-azure-arm-templates#97]
## Description
Describe the problem you're having or the enhancement you'd like to request.
I had previously deployed a cluster using the Active/Active 3-NIC template which is using 13.1.02 Build 0.0.6 but current deployment is using 13.1.1 Build 0.0.4.

How can I use a previously deployed image while deploying a template?

## Template
For bugs, enter the template with which you are experiencing issues below.
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/standalone/3nic/production-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>
3

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by namhly** [comment]
I would suggest you to apply customImage parameter in the template:

"If you would like to deploy using a local BIG-IP image, provide either the full URL to the VHD in Azure storage or the full resource ID to an existing Microsoft.Compute image resource. Note: Unless specifically required, leave the default of OPTIONAL."

**Comment by namhly** [comment]
Since we haven't heard back from you for more than a month, we will close this issue.
Thanks,
